midwayjs/midway

packages/midway-web/package.json, packages/midway-web/src/decorators/requestMapping.ts, packages/midway-web/src/loader/webLoader.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/base-app-router/package.json, packages/midway-web/test/fixtures/enhance/base-app-router/src/app/controller/home.ts, packages/midway-web/test/fixtures/enhance/base-app-router/src/config/config.default.ts, packages/midway-web/test/fixtures/enhance/base-app-router/src/config/config.unittest.ts
支持多路由绑定到同一个方法上
```
@get('/')
@get('/home')
@get('/poster')
async index(ctx) {
ctx.body = 'hello';
}
```
=> refactor: different router and get same result

docs/ioc.md, packages/context/src/base/ObjectCreator.ts, packages/context/src/factory/container.ts, packages/context/src/utils/reflectTool.ts, packages/context/test/fixtures/class_sample.ts, packages/context/test/unit/container.test.ts, packages/context/test/unit/factory/utils/reflectTool.test.ts
Fixes #53
https://github.com/midwayjs/midway/blob/cd9e5fc1d8b2a7c3eded1426c8a034d575700f8d/packages/context/src/factory/container.ts#L65-L76
此处应该是获取原型及其原型链上所有的 metaData，所以使用 `recursiveGetMetadata(TAGGED_PROP, target)`替换
https://github.com/midwayjs/midway/blob/cd9e5fc1d8b2a7c3eded1426c8a034d575700f8d/packages/context/src/base/ObjectCreator.ts#L73-L84
https://github.com/midwayjs/midway/blob/cd9e5fc1d8b2a7c3eded1426c8a034d575700f8d/packages/context/src/base/ObjectCreator.ts#L147-L164
新增 reflectTool.ts 文件，对外提供两个方法
- `recursiveGetPrototypeOf(target) ` 获取 target 的所有原型，返回 target 原型组成的数组
- `recursiveGetMetadata(metadataKey, target, propertyKey)`  获取 target 原型和其原型链上的metaData 值，返回 metaData 组成的数组
新增 `should inject attributes that on the prototype chain and property` 测试用例
修复 `doConstructAsync` 和 …
=> fix: not only inject properties that declared on the property

packages/midway-web/src/loader/webLoader.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/loader-duplicate/package.json, packages/midway-web/test/fixtures/enhance/loader-duplicate/src/app.ts, packages/midway-web/test/fixtures/enhance/loader-duplicate/src/app/controller/my.ts, packages/midway-web/test/fixtures/enhance/loader-duplicate/src/config/config.default.ts, packages/midway-web/test/fixtures/enhance/loader-duplicate/src/config/config.unittest.ts, packages/midway-web/test/fixtures/enhance/loader-duplicate/src/io/controller/chat.ts
由于 egg-socket.io 重复调用了 loadControlelr 导致控制器重复注册了定义。
=> fix: fix invoke loadController repeatedly

packages/midway-web/package.json, packages/midway-web/src/loader/webLoader.ts, packages/midway-web/src/loading.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/package.json, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/src/app/controller/api.ts, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/src/app/controller/my.ts, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/src/app/router.ts, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/src/config/config.default.ts, packages/midway-web/test/fixtures/enhance/base-app-controller-default-export/src/config/config.unittest.ts, packages/midway-web/test/fixtures/enhance/base-app-default-scope/src/app/controller/api.ts
外部传入的 directory 带了 controller 后缀导致查询的时候可能触发找不到 controller 的问题。
=> fix: change default search directory

packages/context/src/factory/applicationContext.ts, packages/context/src/factory/common/ManagedResolverFactory.ts, packages/context/src/utils/errorFactory.ts, packages/context/test/unit/container.test.ts, packages/context/test/unit/factory/utils/errorFactory.test.ts
Fixes #66 
https://github.com/midwayjs/midway/blob/c0d58b72e044397f83f1b1e3a5f05843948b0044/packages/context/src/factory/common/ManagedResolverFactory.ts#L383-L389
https://github.com/midwayjs/midway/blob/c0d58b72e044397f83f1b1e3a5f05843948b0044/packages/context/src/factory/common/ManagedResolverFactory.ts#L450-L456
改写了注入不存在属性名时的错误提示信息
当依赖注入的属性与类的构造函数中给实例增加的属性重名时，在控制台打印警告信息，但最终注入的属性依然会覆盖在构造函数增加的属性。
```TypeScript
@provide()
class UserController {
@inject('userService')
service;
constructor() {
this.service = 'test';
}
}
const userController = new UserController();
```
`userController.service`是通过注入得到的`userService`实例，并非'test'字符串。
将以上两处向实例增加属性的语句放入`try...catch`，在`catch`中判断出错的信息，发现是注入不存在的属性名时，增加当前出错的类名。
错误信息提示始终是出错类的类名，当在类上用了`@provider('my')`装饰器时，出错信息依然提供的是类名
=> add class name when inject preperty error

packages/context/src/factory/common/ManagedResolverFactory.ts, packages/context/test/fixtures/app/lib/ctor/obj7.js, packages/context/test/fixtures/app/resources/construction.xml, packages/context/test/unit/factory/xml/XmlApplicationContext.test.ts
* 不缓存definition.id为空时的对象，表示该对象需要取用时创建
=> ManagedResolverFactory创建单例对象缓存时增加判断逻辑

docs/guide.md, packages/midway-schedule/lib/load_schedule.ts, packages/midway-schedule/package.json, packages/midway-schedule/test/fixtures/worker-non-default-class/package.json, packages/midway-schedule/test/fixtures/worker-non-default-class/src/lib/schedule/interval.ts, packages/midway-schedule/test/schedule.test.ts
Fixes #60 
Before
```typescript
// src/lib/schedule/task1.ts
import { schedule } from 'midway';
@schedule({ ... })
export default class Task1 {
async exec(ctx) {
// ...
}
}
// src/lib/schedule/task2.ts
import { schedule } from 'midway';
@schedule({ ... })
export default class Task2 {
async exec(ctx) {
// ...
}
}
```
After
```typescript
// src/lib/schedule/task.ts
import { schedule } from 'midway';
@schedule({ ... })
export  /* no default */  class Task1 {
async exec(ctx) {
// ...
}
}
@schedule({ ... })
export /* no default */ class Task2 {
async exec(ctx) {
// ...
}
}
```
If use `export default` midway-schedule will only load the default task.
=> feat: support non-default class for midway-schedule

packages/midway-schedule/package.json
Due to https://github.com/eggjs/egg-schedule/pull/44, timer was removed. There is a breaking change. First thing to do, we would lock the egg-schedule version, then waiting plan to upgrade.
=> fix: lock egg-schedule version to avoid breaking change in midway-schedule

docs/guide.md, packages/midway-init/lib/command.js
fix #88 
windows 从远端下载可能有点问题，跟网络也有关，由于 midway 的模板都是内置的，其实也不需要拉 egg 的模板，这里就删除了。
=> fix: remove pull template from github and add doc for windows

packages/tslint-midway-contrib/tslint.json
```
import {a,b,c ,} from ''  // c 后面的逗号太奇怪了
```
=> chore: update comma lint

packages/midway-definition/index.d.ts, packages/midway-definition/package.json, packages/midway-definition/typings/egg/index.d.ts, packages/midway/package.json, packages/midway/src/index.ts
- 增加新包 @midwayjs/definition，用于存放外部的定义，包括egg，插件等非 midway 内置的定义。
- midway 原来导出的定义考虑可以移除了，但是这个属于 breaking change，之前的包是6天前发布的。。。
=> feat: add egg definition

docs/en/guide.md, docs/guide.md, docs/tool_set.md, packages/midway-decorator/src/interface.ts, packages/midway-decorator/src/web/controller.ts, packages/midway-decorator/src/web/requestMapping.ts, packages/midway-init/package.json, packages/midway-web/src/interface.ts, packages/midway-web/src/loader/webLoader.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/base-app-middleware/src/web/controller/my.ts, packages/midway-web/test/fixtures/enhance/base-app-middleware/src/web/middleware/api.ts, packages/midway-web/test/fixtures/enhance/base-app-middleware/src/web/middleware/home.ts
#167
```ts
const mw = async (ctx, next) => {
await next();
};
const newMiddleware = (data) => {
return async (ctx, next) => {
await next();
};
};
@provide()
@controller('/', {middleware: ['homeMiddleware', mw]})
export class My {
@inject()
ctx;
@get('/', {middleware: ['apiMiddleware', newMiddleware('5555')]})
async index() {
}
}
```
支持在 `@controller/@get/@post` 等装饰器的 middleware 属性中直接添加 koa middleware
=> refactor: support set koa middleware directly

packages/midway-init/.autod.conf.js, packages/midway-init/package.json
新版本 yargs 在默认值上和旧版本不同，ci 报错，做降级处理。
=> fix: fix midway-init ci error

packages/midway-core/src/container.ts, packages/midway-core/src/loader.ts, packages/midway-core/test/loader.test.ts
在 container 扫描目录前额外增加模块参数，用于不在目录中的模块，但是却又要放入 ioc 的场景。
=> refactor: add preload exports modules in container load

.travis.yml
=> ci: add node_js v12 instead of v9 for travis-ci

packages/midway-web/src/loader/webLoader.ts, packages/midway-web/src/utils.ts
ref: #258
给 packages/midway-web/src/utils.ts 增加类型
=> feat(types): update types of utils.ts

packages/midway-web/src/loader/webLoader.ts, packages/midway-web/src/utils.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/base-app-decorator/src/app/controller/config.ts, packages/midway-web/test/fixtures/enhance/base-app-decorator/src/config/config.default.ts
=> feat: @config(opt) decorator opt accept dot notation

packages/midway-web/src/loader/webLoader.ts
- midway-web
Use `Set` to avoid duplicate `lookupDirs`
=> perf(web): use set to avoid duplicate lookup

packages/midway/cluster/utils.js
社区 midway 都为 typescript 版本，默认就设置 true，否则在没有 ts 依赖的情况下无法判断。
#341
=> chore: set default typescript options true

packages/midway-bin/README.md, packages/midway-bin/lib/cmd/build.js, packages/midway-bin/package.json, packages/midway-bin/test/lib/cmd/build.test.js
`midway-bin`
Add bundle support with command line option `midway-bin build --entrypoint <entry-file>`. Out dir and source map support were automatically inferred from `tsconfig.json`.
While ncc is used currently, it doesn't mean rollup could not be an option.
=> feat(midway-bin): add bundle support

packages/midway-bin/lib/cmd/build.js, packages/midway-bin/lib/cmd/doc.js
`midway-bin`
Prevent conflicts while inspecting the midway-bin process and the forked build process also been populated with the same exec argv.
=> feat(midway-bin): do not populate exec argv to child processes

packages/midway-bin/package.json, packages/midway-web/src/loader/webLoader.ts
如果仓库里有前端项目，由于默认值为 true，会自动扫描到前端仓库。修复方法为强制传入 false，不影响社区版本。
=> fix: fix ts mode value is empty for non-ts items

packages/midway-bin/lib/cmd/build.js, packages/midway-bin/package.json
`midway-bin`
Allow usage of the multi-package project to share node_modules and generate source-maps with correct modules source file reference.
=> fix: executing midway-bin build at arbitrary directory

packages/midway-bin/lib/cmd/build.js
=> feat: add tsConfig.json to tsc cmd line support

packages/midway-core/src/context/configuration.ts
configuration.load 函数无法指定 baseDir ，上层框架使用时可能会有问题，现将 baseDir 作为可选参数
=> 透传 baseDir 参数

packages/midway-mock/src/mock.ts
如果使用 @ali/midway 的 test 功能的话，每次执行都会报 warning
因为 defaultFramework 每次都立刻执行了
=> fix: lazy get default framework

packages/midway-mock/app/extend/application.js, packages/midway-mock/src/app/extend/application.ts, packages/midway-mock/src/interface.ts, packages/midway-mock/src/mock.ts, packages/midway-mock/test/index.test.ts, packages/midway-web/test/enhance.test.ts, packages/midway-web/test/fixtures/enhance/base-app/src/lib/service.ts
- 1、mm.app() 的默认参数可以为空
- 2、fix #433 ，mockContext() 返回合并后的 Context
- 3、fix #438 把midway-mock 增加到 egg 的 load 插件中
=> fix: mock fn

packages/midway-bin/lib/cmd/build.js, packages/midway-bin/package.json, packages/midway-bin/test/fixtures/ts-dir-tsconfig-comments/src/index.ts, packages/midway-bin/test/fixtures/ts-dir-tsconfig-comments/tsconfig.json, packages/midway-bin/test/lib/cmd/build.test.js, packages/midway-bin/test/lib/util.test.js
fix #423 : 修复midway-bin build的时候，如果tsconfig.json是通过tsc --init创建出来的。
=> fix: can midway build when tsconfig.json has comments

packages/midway/cluster/master.js
cluster
The egg is not in dependencies list of midway, and it is not necessary to print egg version information in midway. It's broken on resolving modules with `npm install --legacy-bundling`.
=> chore(cluster): remove printing egg versions

lerna.json, package.json, packages/eslint-midway-contrib/package.json
- eslint
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
lerna.json hoist not need @typescript-eslint/*
ref: https://github.com/typescript-eslint/typescript-eslint/pull/2105
升级 top eslint 为 v7，从而不需修改 lerna.json 添加 hoist 条目。
同时升级 typescript-eslint ，即便 eslint v6 时也不会出现无法加载 @typescript-eslint/* 插件问题。
=> chore(devDeps): upgrade for eslint

packages/midway-web/config/config.default.js
新版本已经移除了 globby，放开 node_modules 的限制。不然老的 container 中无法加载 node_modules 的模块。
=> chore: remote node_modules for custom container loader

packages/egg-layer/framework/config/plugin.js, packages/egg-layer/test/fixtures/eaas-fc/config/plugin.js, packages/egg-layer/test/fixtures/eaas-scf/config/plugin.js, packages/faas-cli-command-core/src/plugin.ts, packages/faas-cli-plugin-aws/src/index.ts, packages/faas-cli-plugin-fc/src/index.ts, packages/faas-cli-plugin-package/src/index.ts, packages/faas-cli-plugin-package/test/package-app.test.ts, packages/faas-cli-plugin-scf/src/index.ts, packages/serverless-spec-builder/wrapper_app.ejs
app（egg） 迁移方案会不知道为何在冷启动时初始化多次。报错如下：
```json
{
"errorMessage": "EMFILE: too many open files, open '/code/package.json'",
"errorType": "Error",
"stackTrace": [
"at openSync (fs.js:457:3)",
"at readFileSync (fs.js:359:35)",
"at exports.readJSONSync (/code/node_modules/utility/lib/json.js:19:24)",
"at EggLoader (/code/node_modules/egg-core/lib/loader/egg_loader.js:45:24)",
"at AgentWorkerLoader (/code/node_modules/@midwayjs/egg-layer/node_modules/egg/lib/loader/agent_worker_loader.js:9:1)",
"at EggCore (/code/node_modules/egg-core/lib/egg.js:118:19)",
"at EggApplication (/code/node_modules/@midwayjs/egg-layer/node_modules/egg/lib/egg.js:46:5)",
"at Agent (/code/node_modules/@midwayjs/egg-layer/node_modules/egg/lib/agent.js:22:5)",
"at LayerWrapper …
```
=> fix: add lock init for egg app

packages/faas-cli-plugin-package/src/index.ts, packages/faas-cli-plugin-package/test/package.test.ts
close #634 
由于发布到 serverless 平台时会根据具体的平台来生成最终的serverless.yml文件与原yml文件格式内容不一致导致一些运行时的具体逻辑判断失效。所以需要额外保留一份原本的yml文件，这里统一命名为 `f.origin.yml`
=> chore: backup orginal yml file

packages/bootstrap/package.json, packages/core/jest.config.js, packages/core/src/context/applicationContext.ts, packages/core/src/context/configuration.ts, packages/core/src/context/container.ts, packages/core/src/context/managedResolverFactory.ts, packages/core/src/context/midwayContainer.ts, packages/core/src/interface.ts, packages/core/test/context/requestContainer.test.ts, packages/core/test/fixtures/app-with-configuration-global-inject/base-app-decorator/package.json, packages/core/test/fixtures/app-with-configuration-global-inject/base-app-decorator/src/configuration.ts, packages/core/test/fixtures/app-with-configuration-global-inject/sql/package.json, packages/core/test/fixtures/app-with-configuration-global-inject/sql/src/configuration.ts, packages/core/test/fixtures/app-with-configuration-global-inject/sql/src/home.ts, packages/core/test/loader.test.ts, packages/faas/jest.config.js, packages/faas/package.json, packages/faas/test/index.test.ts, packages/mock/package.json, packages/mock/src/utils.ts, packages/web/test/.setup.js
在手动调用 registerObject 的时候把 key 存起来，bind 的时候判断是否增加前缀。修复在组件中注入baseDir等找不到对象的问题。
=> fix: component inject global object and add case

packages/core/src/baseFramework.ts, packages/core/src/context/midwayContainer.ts, packages/core/test/baseFramework.test.ts, packages/core/test/fixtures/base-app-aspect/src/aspect/a.ts, packages/core/test/fixtures/base-app-aspect/src/aspect/c.ts, packages/core/test/fixtures/base-app-aspect/src/home.ts, packages/core/test/loader.test.ts, packages/mock/src/utils.ts, packages/web/test/fixtures/issue/base-app-aspect-throw/package.json, packages/web/test/fixtures/issue/base-app-aspect-throw/src/aspect/testThrow.ts, packages/web/test/fixtures/issue/base-app-aspect-throw/src/config/config.default.ts, packages/web/test/fixtures/issue/base-app-aspect-throw/src/config/config.unittest.ts, packages/web/test/fixtures/issue/base-app-aspect-throw/src/controller/User.ts, packages/web/test/issue.test.ts
fixed: #683 
尝试了多种方式，均无法解决描述符的多次加载问题。现阶段处理为：
- 1、拦截器在一个进程，多个 container 中只加载一次（这样才不会重复加载）
- 2、随之而来的问题就是拦截器中注入的 app/logger 等，引用会固定在第一个容器上，如果有注入的情况，会出现上下文错乱的问题（文档指引，不允许使用）
=> fix: aspect bind missing ctx

packages/core/src/baseFramework.ts, packages/core/src/context/midwayContainer.ts, packages/core/src/context/requestContainer.ts, packages/core/src/interface.ts, packages/core/src/loader.ts, packages/core/test/baseFramework.test.ts, packages/core/test/fixtures/base-app-aspect/src/aspect/a.ts, packages/core/test/fixtures/base-app-aspect/src/aspect/b.ts, packages/core/test/fixtures/base-app-aspect/src/aspect/c.ts, packages/core/test/loader.test.ts, packages/decorator/src/util/index.ts, packages/decorator/src/web/requestMapping.ts, packages/mock/src/utils.ts, packages/web/jest.config.js, packages/web/package.json, packages/web/test/fixtures/issue/base-app-aspect-throw/src/aspect/testThrow.ts, packages/web/test/fixtures/issue/base-app-aspect-throw/src/controller/User.ts
使用新的方法重构拦截器。老的修改 descriptor.value，直接改到原型上，新的绑定到容器上，每个容器进行了隔离，理论上老的方案对性能影响较小，但是无法做到隔离性，以及注入会有问题，新的方案，虽然对性能有些影响，但是更干净，隔离性和注入也都没问题。
做个benchmark。
- 每个 case 做10次，平均对比
- 前 5 次老的先执行，后 5 次新的先执行
**普通情况下（不拦截）**
<table>
<tr>
<th>old
<td>303,837 ops/sec ±1.51%
<td>301,375 ops/sec ±1.60%
<td>292,021 ops/sec ±1.35%
<td>303,102 ops/sec ±0.65%
<td>296,131 ops/sec ±1.25%
<td>307,447 ops/sec ±0.95%
<td>279,391 ops/sec ±0.65%
<td>284,551 ops/sec ±5.90%
<td>303,720 ops/sec ±1.19%
<td>278,311 ops/sec ±1.57% 
<tr>
<th>new
<td>287,145 ops/sec ±1.47%
<td>282,594 ops/sec ±0.61%
<td>281,689 ops/sec ±2.36% 
<td>292,187 ops/sec ±0.53%
<td>288,832 ops/sec ±0.66%
<td>291,384 ops/sec ±0.66%
<td>280,037 ops/sec ±11.77%
<td>276,774 ops/sec ±1.92%
<td>289,160 ops/sec ±0.99%
<td>292,276 ops/sec ±0.74%
</table>
**一个拦截器** …
=> refactor: modify the implementation of aspect

packages-serverless/serverless-fc-starter/src/runtime.ts
=> fix: fc egg app body parse

packages/web-express/src/framework.ts, packages/web-express/test/fixtures/base-app/src/controller/api.ts, packages/web-express/test/index.test.ts, packages/web-koa/src/framework.ts, packages/web-koa/test/fixtures/base-app/src/controller/api.ts, packages/web-koa/test/index.test.ts, packages/web/test/feature.test.ts, packages/web/test/fixtures/feature/base-app/src/controller/api.ts
fix: #736  @wang-ran
- koa 当手动设置了 body，返回为空的时候，必须显示调用 set body
- express 提前调用 send 之后 不能设置任何头或者再次 send 了
=> fix: return ctx.body and set header after send

packages/core/src/context/applicationContext.ts, packages/core/src/interface.ts, packages/core/test/fixtures/fun_sample.ts, packages/midway/src/index.ts
增加 get 和 getAsync 的类参数定义支持。现在参数为 class 拿到的返回值，可以被正确推导出类型。
=> fix: definition for getAsync and get

packages-serverless/egg-layer/index.js, packages/core/src/baseFramework.ts, packages/core/src/interface.ts, packages/core/test/baseFramework.test.ts, packages/faas/src/framework.ts, packages/logger/src/container.ts, packages/logger/src/index.ts, packages/logger/test/index.test.ts, packages/logger/test/util.ts, packages/mock/src/utils.ts, packages/web/src/interface.ts, packages/web/src/logger.ts, packages/web/src/utils.ts, packages/web/test/logger.test.ts, packages/web/test/utils.ts
处理几个问题
- 1、给 app 和 framework 都增加 getCoreLogger 方法
- 2、在本地开发的时候，ts-node 会出现扩展 egg 定义找不到的情况，原因是 ts-node 不认 tsconfig 中的 tsRoot，而编辑器和 tsc 则认识，导致只会在 run dev 的时候报错，但是如果提前 require 了对应的定义文件，则不会出现此问题，由于 midway 在文档里中推荐将定义放到 interface.ts 中，那么，在本地 dev 启动的时候，我们提前去 require 该文件即可。
- 3、由于现在的日志是个大池子，其他框架也会和 egg 复用日志对象，在这种场景下，如果和 egg 复用（socket）Logger，那么池子里存在的，可能只有 fileLogger，不会输出控制台日志。
- 4、~新版本在使用 egg-layer 时，需要处理日志的问题，比如把 file transport 删除。~ 没有问题，因为 egg-layer 写到临时目录里去了
=> fix: definition fix for getLogger and getCoreLogger

packages/logger/src/logger.ts, packages/mock/src/utils.ts, packages/web/src/logger.ts
处理 windows 下日志的问题
- 1、软链在windows 底下无法生成
- 2、egg 日志备份有问题，在 windows 底下一般只会用于开发，且不会生成软链，就不备份了
- 3、本地测试的时候删除日志的功能，在 windows 底下就不删了（fs-extra 也有问题，管理员模式是好的，try是不行的，所以跳过了）
=> fix: remove error and symbol link in windows

packages/web/config/plugin.js, packages/web/src/logger.ts
现有 egg 日志切割依旧在启用，会造成下面的错误，由于 midway 日志自带了日志切割处理，为避免问题和 midway 框架统一，禁止 egg 的切割。
```
2021-01-10 01:23:00,012 ERROR 7405 nodejs.Error: [egg-logrotator] rename /Users/harry/project/application/my_midway_app/logs/my_midway_project/midway-web.log, found exception: targetFile /Users/harry/project/application/my_midway_app/logs/my_midway_project/midway-web.log.2021-01-09 exists!!!
at renameOrDelete (/Users/harry/project/application/my_midway_app/node_modules/egg-logrotator/app/lib/rotator.js:63:17)
at async DayRotator.rotate (/Users/harry/project/application/my_midway_app/node_modules/egg-logrotator/app/lib/rotator.js:28:9)
at async Object.task (/Users/harry/project/application/my_midway_app/node_modules/egg-logrotator/app/schedule/rotate_by_file.js:17:7)
```
=> fix: disable logrotator and avoid file exists error

packages-serverless/serverless-fc-starter/src/runtime.ts, packages-serverless/serverless-fc-starter/test/fixtures/http/index.ts, packages-serverless/serverless-fc-starter/test/index.test.ts
修复在 fc http 触发器下，ctx.originContext 属性为空的问题。
=> fix: missing originContext property  in http trigger

packages/logger/package.json, packages/logger/test/util.ts, packages/web/package.json, packages/web/src/utils.ts, packages/web/test/utils.test.ts
由于时区的问题，获取当前时间会有不对的可能，在第一次做 egg 日志备份的时候，如果正好跨天了，可能会出现去获取前一天的情况。
ps: 部分单测也有影响（这也是为什么凌晨提交有问题，到早上跑就好了的原因）
=> fix: date string error in ISO pattern

packages/c-mongoose/.gitignore, packages/c-mongoose/.npmignore, packages/c-mongoose/jest.config.js, packages/c-mongoose/package.json, packages/c-mongoose/src/config/config.default.ts, packages/c-mongoose/src/configuration.ts, packages/c-mongoose/src/index.ts, packages/c-mongoose/src/interface/config.type.ts, packages/c-mongoose/src/service/mongoose.ts, packages/c-mongoose/test/.setup.js, packages/c-mongoose/test/fixtures/base-app/package.json, packages/c-mongoose/test/fixtures/base-app/src/config/config.default.ts, packages/c-mongoose/test/fixtures/base-app/src/configuration.ts, packages/c-mongoose/test/fixtures/base-app/src/service/test.ts, packages/c-mongoose/test/index.test.ts, packages/c-mongoose/tsconfig.json
使用方法：
1、安装npm install @midwayjs/mongoose --save
2、导入模块：
**src/configuration.ts**
```
import { Configuration } from '@midwayjs/decorator';
import * as mongoose from '@midwayjs/mongoose';
@Configuration({
imports: [mongoose]
})
export class AutoConfiguration {
}
```
3、业务代码中定义对象类型
定义mongodb数据的对象类型：
```
import { prop, getModelForClass } from "@midwayjs/mongoose";
export class User {
@prop()
public name?: string;
@prop({ type: () => [String] })
public jobs?: string[];
}
export const UserModel = getModelForClass(User);
```
4、业务代码中的增删改查：
```
@Provide()
export class TestService{
async getTest(){
const { _id: id } = await UserModel.create({ name: 'JohnDoe', jobs: ['Cleaner'] } as User); //此处增加数据
const user = await UserModel.findById(id).exec();//查询数据
console.log(user)
}
}
```
=> feat: add component mongoose

packages/web/config/config.local.js
=> fix: add info level for core logger in local env

packages/logger/src/interface.ts, packages/logger/src/logger.ts, packages/logger/test/index.test.ts, packages/web/app/extend/context.js, packages/web/config/config.default.js, packages/web/config/plugin.js, packages/web/src/framework/web.ts, packages/web/src/index.ts, packages/web/src/interface.ts, packages/web/src/logger.ts, packages/web/test/fixtures/apps/mock-dev-app-egg-logger/package.json, packages/web/test/fixtures/apps/mock-dev-app-egg-logger/src/config/config.default.ts, packages/web/test/fixtures/apps/mock-dev-app-logger/src/config/config.default.ts, packages/web/test/fixtures/apps/mock-dev-app/src/config/config.default.ts, packages/web/test/fixtures/apps/mock-production-app-do-not-force/src/config/config.default.ts, packages/web/test/fixtures/apps/mock-production-app/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-component-config/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-middleware/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-plugin-inject/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-use-custom-egg/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app/src/config/config.default.ts, packages/web/test/logger.test.ts
- 1、将 egg logger 和 midway logger 分离，增加开关 fix: #822 
- 2、给 logger 增加动态修改文件 level 和控制台输出 level
- 3、去除默认 info 输出的绿色字体
- 4、原来是 midway 日志，改为使用 egg logger 之后，预先删除软链
=>  fix: midway logger and mixin egg logger will be missing log

packages/web-express/src/framework.ts, packages/web-koa/src/framework.ts, packages/web/config/config.local.js, packages/web/src/framework/web.ts, packages/web/src/logger.ts, packages/web/test/feature.test.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/package.json, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/config/config.unittest.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/configuration.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/controller/api.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/logger.ts
- 1、本地日志还是输出太多，和默认 egg 启动保持一致，不再输出 core logger 的日志。如有需求，可以使用 app.logger 或者调整日志解决
- 2、midway logger 之前未适配 egg 部分配置
- 3、修复 contextLogger 未覆盖成功的错误
=> fix: disable coreLogger info console output in local env

packages/logger/src/format.ts, packages/logger/test/index.test.ts
原来 
```
async home() {
throw new Error('bbb');
}
```
修复前
修复后
=> fix: stack missing in context logger

packages/web/agent.js, packages/web/app.js, packages/web/app/extend/agent.js, packages/web/src/framework/web.ts, packages/web/test/feature.test.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/agent.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/app.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/configuration.ts, packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/logger.ts, packages/web/test/utils.ts
修复egg 框架继承的情况下，提前使用 ctx.logger 输出报错 "[winston] Unknown logger level: INFO" 的情况。错误如截图。
=> fix: ctx logger overwrite in egg extend

packages/web/src/logger.ts, packages/web/test/logger.test.ts
修复这个问题
```
2021-02-09 14:38:06,377 ERROR 95067 TypeError: _a.disableConsole is not a function
at Map.disableConsole (/Users/harry/project/gitlab/std-service-market/node_modules/_@midwayjs_web@2.7.3@@midwayjs/web/dist/logger.js:177:66)
at /Users/harry/project/gitlab/std-service-market/node_modules/_@midwayjs_web@2.7.3@@midwayjs/web/dist/logger.js:203:21
at /Users/harry/project/gitlab/std-service-market/node_modules/_get-ready@2.0.1@get-ready/index.js:73:53
at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
=> fix: loggers with egg logger instance and invoke disableConsole method

packages/faas/src/starter.ts
用于在一体化环境中指定代码目录为 `/src/apis` 这样的路径。
在原有逻辑中，会根据是否为ts环境来在 `appDir` 后面添加 src 或 dist，但是这在一体化项目中无法满足，导致 configuration.ts 等依赖于 `baseDir` 配置的内容无法被加载。
=> fix: support user config code dir

packages/decorator/src/common/decoratorManager.ts, packages/decorator/test/annotation/inject.test.ts
如果属性明确标识了 class 类型，则取 class 的 provideId 做为 key。比如
```ts
@Provode()
class UserService {}
@Provide()
class UserController {
@Inject()
service: UserService;   // 这里因为标识的是class，那么注入的就是这个类型
}
老代码这样写，由于获取的是属性名，所以会报错，但是新代码下可以成功注入。
但是在下面的代码下，是 breaking change。
```ts
@Provide()
class InjectParent {
}
@Provide()
class InjectChild extends InjectParent {
}
class Test {
@Inject()
child: InjectParent;
@Inject()
InjectChild: InjectParent;
}
```
这里有个 breaking change，如果类型显示是父类，按照新逻辑，注入的实例就会是父类，而不是子类，但是老的场景下就会是子类。
=> feat: support inject by class

packages/core/src/service/configService.ts, packages/core/test/services/configService.test.ts, packages/core/test/services/fixtures/compatible_production/config.default.ts, packages/core/test/services/fixtures/compatible_production/config.prod.ts, packages/core/test/services/fixtures/compatible_production/config.unittest.ts, packages/core/test/services/fixtures/default_case/config.default.ts, packages/core/test/services/fixtures/default_case/config.local.ts
兼容原来 egg 的用户习惯：
- config.prod 在 production 依旧会读取
- config.unittest 在 test 下依旧会读取
=> feat: compatible read config.prod and config.unittest

packages/cache/.gitignore, packages/cache/package.json, packages/cache/src/config/config.default.ts, packages/cache/src/configuration.ts, packages/cache/src/index.ts, packages/cache/src/service/cache.ts, packages/cache/test/cache.test.ts, packages/cache/test/fixtures/cache-manager/package.json, packages/cache/test/fixtures/cache-manager/src/configuration.ts, packages/cache/test/fixtures/cache-manager/src/service/user.service.ts, packages/cache/tsconfig.json, packages/core/src/index.ts
Midway Cache描述：
Midway为不同的cache存储的provider提供了统一的api。内置的是一个memory方式的缓存模块。同时我们可以方便的切换到更全面的解决方案，例如使用redis等方式。
使用方法：
1、安装依赖: 
```
$ npm install cache-manager -S
$ npm install @types/cache-manager -D 
$ npm install @midwayjs/cache -S
```
2、导入component
在configuration.ts中：
```
import { Configuration, App } from '@midwayjs/decorator';
import { Application } from '@midwayjs/koa';
import * as bodyParser from 'koa-bodyparser';
import * as cacheComponent from '@midwayjs/cache';
import { join } from 'path'
@Configuration({
imports: [
cacheComponent
],
importConfigs: [
join(__dirname, 'config')
]
})
export class ContainerLifeCycle {
}
```
3、使用方法：
```
import { Inject, Provide } from '@midwayjs/decorator';
import { IUserOptions } from '../interface';
import { Cache } from '@midwayjs/cache';
@Provide() …
```
=> feat: add midway cache

packages/mock/src/utils.ts
固定框架查找顺序，防止 grpc 先于 web 框架生效。
fix: #945
=> fix: framework find and sort

packages/consul/README.md, packages/consul/jest.config.js, packages/consul/jest.setup.js, packages/consul/package.json, packages/consul/src/config/config.default.ts, packages/consul/src/configuration.ts, packages/consul/src/controller/consul.ts, packages/consul/src/index.ts, packages/consul/src/interface.ts, packages/consul/src/lib/balancer.ts, packages/consul/src/lib/provider.ts, packages/consul/src/service/balancer.ts, packages/consul/test/consul.framework.ts, packages/consul/test/fixtures/base-app/package.json, packages/consul/test/fixtures/base-app/src/config/config.default.ts, packages/consul/test/fixtures/base-app/src/configuration.ts, packages/consul/test/fixtures/base-app/src/controller/test.ts, packages/consul/test/fixtures/mock.data.ts, packages/consul/test/index.test.ts, packages/consul/tsconfig.json, packages/consul/usage.md
register to consul server and deregister when shutdown, but both are optional, also lookup the services which registered on the consul server, get the service instance with injected balancer, the origin consul object is managed by the IoC container also.
dependency:
- the hashicorp consul server(except unittest)  
- npm consul package  
---
```shell
npm i @midwayjs/consul -S
npm i @types/consul -D
```
```
import * as consul from '@midwayjs/consul'
@Configuration({
imports: [
consul
],
importConfigs: [join(__dirname, 'config')]
})
export class ContainerConfiguration {}
```
```
consul: {
provider: {
// 注册本服务
register: true,
// 应用正常下线反注册
deregister: true,
// consul server 主机
host: '192.168.0.10',
// consul server 端口
port: 8500,
// 调用服务的策略(默认 random 具有随机性)
strategy: 'random',
},
service: { …
```
=> feat(consul): register to consul server and lookup service with balancer

packages/bootstrap/src/bootstrap.ts, packages/bootstrap/test/fixtures/mix-app/bootstrap.js, packages/bootstrap/test/fixtures/mix-app/src/configuration.ts, packages/bootstrap/test/fixtures/mix-app/src/index.ts, packages/bootstrap/test/fixtures/mix-app/src/service/remoteConfigService.ts, packages/core/src/baseFramework.ts, packages/core/src/context/midwayContainer.ts, packages/core/src/context/requestContainer.ts, packages/core/src/interface.ts, packages/core/src/loader.ts, packages/core/src/service/aspectService.ts, packages/core/src/service/configService.ts, packages/core/src/util/emptyFramework.ts, packages/web/app.js, packages/web/src/interface.ts
fix: #969 
close: #958
示例如下：
```js
Bootstrap
.load(globalConfig => {
// 加载主 web 框架
const framework = new WebFramemwork();
framework.configure(globalConfig.cluster);
return framework;
})
.load(globalConfig => {
// 加载副 socket.io 框架
const framework = new SocketFramemwork();
framework.configure();
return framework;
})
.before(async (container) => {
const configService = await container.getAsync('remoteConfigService');
const data = await configService.getRemoteConfig();
container.getConfigService().addObject(data);
})
.run();
```
=> fix: load config once and support load singleton service before framework start

packages/logger/src/container.ts, packages/logger/src/interface.ts, packages/logger/src/logger.ts, packages/logger/test/index.test.ts, packages/mock/src/utils.ts, packages/mock/test/new.test.ts
在频繁 createApp/close 的场景下，由于日志 flush 会有一定时间，如果持续创建和删除，在创建 app 时有一定概率会创建失败，移除默认测试后删除日志的功能。
在需要删除的场景，可以通过参数指定删除（业务测试概率不高，且有日志也容易排查问题）
=> refactor: disable remove logs dir when testing

packages/core/src/context/configuration.ts
在[configuration.ts](https://github.com/midwayjs/midway/blob/2.x/packages/core/src/context/configuration.ts)中，存在一处路径硬拼接问题。可通过以下步骤重现：
于windows平台
1. `npm init midway -- --type=web my_midway_app`
2. `npm run dev`
3. 报错了
此提交改为path.join拼接路径
=> fix: configuration file path join on windows

packages-serverless/runtime-engine/src/lib/logger.ts, packages-serverless/runtime-engine/test/lib/logger.test.ts
* 日志轮转时如果写入频率高， stream 的 fd 为空，会导致轮转判断出错
=> fix: serverless logger rotator error

packages/bootstrap/src/bootstrap.ts
修复 bootstrap 在 stop 的时候，把 logger 清掉导致关闭的时候会出现一个 logger 为空的报错。
=> fix: remove reset bootstrap logger

packages-serverless/runtime-engine/src/engine.ts, packages-serverless/runtime-engine/test/perf-events.test.ts
Fixes Node.js v16 compatibility
=> test: perf_hooks observers no longer receive events immediately

packages-serverless/serverless-scf-starter/src/runtime.ts
处理腾讯云消息返回后， 继续等待 event loop 直至超时的问题。
=> fix: disable wait event loop in tencent serverless

packages/logger/package.json, packages/logger/src/interface.ts, packages/logger/src/logger.ts, packages/logger/src/rotate.ts, packages/logger/test/memory-stream.ts, packages/logger/test/random-string.ts, packages/logger/test/rotate.test.ts
由于 winston-daily-rotate-file 里直接依赖了 tar 包导致私有环境可能无法下载，将 winston-daily-rotate-file 代码直接合并进 logger。
把 logger.query 方法去掉了，目前没有用到。
=> fix: remove winston-daily-rotate-file

packages/typegoose/package.json
mongoose 的定义已经从 @types/mongoose 变为自带，需要移除。
=> chore: remove types for mongoose

packages-serverless/runtime-engine/src/lightRuntime.ts, packages/logger/src/format.ts, packages/logger/src/logger.ts, packages/logger/test/index.test.ts
支持 logger 在多个参数时候的输出问题。
比如
```ts
logger.info('test', 'test1', 'test2', new Error('xxx'));
```
=> fix: logger parameter join output

.github/workflows/nodejs.yml, packages-serverless/serverless-fc-starter/src/runtime.ts, packages-serverless/serverless-fc-starter/test/index.test.ts, packages-serverless/serverless-scf-starter/src/runtime.ts, packages-serverless/serverless-scf-starter/test/index.test.ts, packages/typegoose/test/index.test.ts
- 1、在线上抛出带堆栈的错误时，隐藏用户的真实错误信息
- 2、在非 http 触发器场景增加 ctx.originEvent
=> fix: hide real error when user code throw error

packages/core/src/util/webRouterCollector.ts, packages/core/test/fixtures/base-app-func-router/src/function/index.ts, packages/core/test/util/webRouterCollector.test.ts, packages/faas/test/fixtures/base-app-new/src/index.ts
* 修复 @Fun 装饰器支持 bug
```
@Provide()
@Fun('index.handler')
class XXX {
}
```
=> fix: @Func decorator with empty metadata

packages/orm/src/configuration.ts, packages/orm/src/index.ts, packages/orm/test/fixtures/base-fn-multiple-db/src/configuration.ts, packages/orm/test/fixtures/base-fn-multiple-db/src/model/onlyTestLoadLog.ts
* 修复 typeorm 配置多数据库时， 初始化加载全部实体问题
* 新增 EntityModel装饰器 新增一个connectionName 参数 指定哪个配置加载该实体
=> feat: Optimize typeorm to initialize loading entities

packages/faas/src/interface.ts
支持函数下 `app.use(await this.app.generateMiddlware(xxxx))`  直接传入依赖注入类。
=> chore: support use class in middleware

packages/midway-schedule/tsconfig.json, packages/web-express/src/framework.ts, packages/web-express/src/interface.ts, packages/web-koa/src/framework.ts, packages/web-koa/src/interface.ts, packages/web/src/framework/singleProcess.ts
- web
- web-koa
- web-exporess
add support hostname to http server listening, then user can custom hostname by self
=> feat: add support hostname to http-listening

packages-serverless/serverless-vercel-starter/package.json, packages/web/app/extend/context.js
=> fix: task redefine context logger

packages/task/src/config/config.default.ts, packages/task/src/configuration.ts, packages/task/test/fixtures/base-app/src/config/config.default.ts
=> feat: queue support concurrency config

packages/midway-schedule/agent.ts
midway-schedule
将`midway`生成的`schedule`注册进`egg`的`schedule`中。确保`schedule`可以被找到，避免只能通过`agent.schedule.closed`的方式才能关停`schedule`，而导致所有`schedule`都关闭。
=> fix: midway-schedule can't find schedule by key

packages/core/src/context/managedResolverFactory.ts, packages/core/test/baseFramework.test.ts, packages/core/test/fixtures/app-with-component-inject-with-class/circular/package.json, packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/a.ts, packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/b.ts, packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/circularService.ts, packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/configuration.ts, packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/index.ts, packages/core/test/fixtures/app-with-component-inject-with-class/main/src/configuration.ts
在组件中使用循环依赖会导致程序卡死，2.13.0版本增加了providerUUId之后出现的问题，之前版本正常
=> fix: circular inject for provide uuid

packages-serverless/runtime-engine/src/engine.ts, packages-serverless/runtime-engine/src/lib/performance.ts, packages-serverless/runtime-engine/src/runtime.ts
- runtime-engine
- disable marks on invoke handlers. we do only care about timings on start.
=> fix: disable performance marking for invoke handlers

packages/core/src/util/webRouterCollector.ts, packages/core/test/util/router.js, packages/core/test/util/webRouterCollector.test.ts
=> fix: router sort

packages/validate/index.d.ts, packages/validate/src/config.default.ts, packages/validate/src/configuration.ts, packages/validate/src/decorator/validate.ts, packages/validate/test/check.test.ts
=> fix: validate typing and config

packages-serverless/serverless-app/src/utils.ts
serverless-app
`findNpmModule` always returns `false` when using yarn pnp. This PR detects pnp environment and uses `require.resolve` in pnp.
=> fix(serverless-app): fix findNpmModule in pnp

site/docs/extensions/sequelize.md
None.
Fix the wrong identifiers `UserModel` for the Sequelize examples, should use `Photo` instead.
=> doc: fix wrong identifier for the sequelize examples.

packages/web/src/interface.ts
修复 `@deprecated` 注释后面 `@scope`  IDE 渲染容易让人混淆问题
=> chore(web): fix style of @deprecated comment

packages/decorator/src/interface.ts
fix the missing enable parameter of serverless timer trigger.
=> fix:(core) fix the missing enable parameter of serverless timer trigger

site/docs/extensions/socketio.md
A syntax error in modifying the number of namespace connections obtained in socketIO.
=> doc: update socketio.md

site/docs/req_res_app.md
在midway v3文档中`this.ctx.getAttr()`的示例接收了2个参数.但是代码里的类型定义中,该方法只接受一个参数.
`this.ctx.getAttr()`的类型定义: https://github.com/midwayjs/midway/blob/413ec44ea309077ce482fe55db3819aaab45894a/packages/core/src/interface.ts#L378
=> docs(Context): fix ctx.getAttr() syntax error

site/docs/req_res_app.md
在midway v3文档中`this.app.getAttr()`的示例接收了2个参数.但是代码里的类型定义中,该方法只接受一个参数.
`this.app.getAttr()`的类型定义如下: https://github.com/midwayjs/midway/blob/413ec44ea309077ce482fe55db3819aaab45894a/packages/core/src/interface.ts#L509-L514
=> docs(Application): fix app.getAttr() syntax error

packages/web/src/cluster.ts
fix: https://github.com/midwayjs/midway/issues/1827
=> fix: missing appDir value with egg-scripts cluster mode

packages/core/src/util/index.ts, packages/core/src/util/pathToRegexp.ts, packages/decorator/src/util/uuid.ts, packages/processAgent/src/configuration.ts, packages/prometheus/src/configuration.ts, packages/swagger/src/swaggerExplorer.ts
- core
- processAgent
- prometheus
- swagger
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

packages/web/src/logger.ts
While the readFileSync got a file size reach the size limit, which is 0x1fffffe8 (512MB), the V8 will throw a new Error: `Cannot create a string longer than 0x1fffffe8 characters`.
Thus, I recommend use `statSync` instead of `readFileSync` to check if the file is empty or not.
This bad case (while log file is over 512MB) will block the midway core startup process.
Using `statSync` instead of `readFileSync` to check if the file is empty or not. This may bring a litte speed up, and more robustness.
=> fix: logger create failed cause file size too large to create V8 string

packages/orm/src/index.ts
Error: TS Error: Module '"./dist/index"' has no exported member 'ConnectionOptions'.(node_modules/_@midwayjs_orm@3.1.6@@midwayjs/orm/index.d.ts)
=> fix: fix ts build error (orm)

packages/core/src/baseFramework.ts, packages/core/src/index.ts, packages/core/src/service/mockService.ts, packages/core/src/setup.ts, packages/core/test/fixtures/base-app-ctx-mock/package.json, packages/core/test/fixtures/base-app-ctx-mock/src/configuration.ts, packages/core/test/service/mockService.test.ts, packages/core/test/util.ts, packages/mock/src/index.ts, packages/mock/src/mock.ts, packages/mock/test/fixtures/base-app-koa/src/controller/hone.ts, packages/mock/test/new.test.ts, packages/web-express/src/framework.ts, packages/web/src/cluster.ts
=> refactor: add mock support

packages/web/src/logger.ts
=> fix: close logger before egg app close

packages/swagger/src/interfaces/index.ts, packages/swagger/src/swaggerExplorer.ts, packages/swagger/src/swaggerMiddleware.ts, site/docs/extensions/swagger.md
* 修复 装饰器中声明数组类型判断出错bug
* 增加 displayOptions
#2074
=> feat: add display options and fix array bug

packages/redis/src/manager.ts, packages/redis/test/fixtures/base-app-bad-client/package.json, packages/redis/test/fixtures/base-app-bad-client/src/config.default.ts, packages/redis/test/fixtures/base-app-bad-client/src/configuration.ts, packages/redis/test/index.test.ts
=> fix: use redis client before it's ready, most likely to occur during unit test

site/docs/extensions/validate.md
二号标题中 校验参数 的示例， @Validate 装饰器的使用，应该在头部引入 import { Validate } from '@midwayjs/validate'; 否则新手会不清楚 @Validate 装饰器从哪里来。
=> docs: update validate.md

packages/view-nunjucks/src/config/config.default.ts, packages/view-nunjucks/src/engine.ts, packages/view-nunjucks/src/interface.ts
=> fix(view-nunjucks): add autoescape config && add ts interface

packages/core/src/interface.ts
fixes #2241
tsconfig 开启 `strictFunctionTypes` 时，方法参数必须逆变。以下为一示例：
```ts
interface Obj {
f: (n: number) => any;
g: (n?: number) => any;
}
class O1 implements Obj {
f: () => 1; // Ok
g: () => 1; // Ok
}
class O2 implements Obj {
f: (n: number) => 1; // Ok
g: (n: number) => 1; // Error, 类型“O2”中的属性“g”不可分配给基类型“Obj”中的同一属性
}
```
=> fix: IMiddleware interface

packages/axios/src/configuration.ts, packages/axios/src/serviceManager.ts, packages/core/src/common/serviceFactory.ts, packages/core/src/service/configService.ts, packages/core/test/common/serviceFactory.test.ts, packages/core/test/error/error.test.ts, packages/core/test/error/http.test.ts, packages/core/test/service/configService.test.ts, packages/cos/src/manager.ts, packages/cos/test/index.test.ts, packages/mongoose/src/manager.ts, packages/mongoose/test/index.test.ts, packages/oss/src/manager.ts, packages/oss/test/index.test.ts, packages/redis/src/manager.ts, packages/redis/test/index.test.ts, packages/tablestore/src/manager.ts, packages/tablestore/test/index.test.ts, site/docs/extensions/axios.md
=> fix: service factory client & clients merge

site/docs/controller.md
目的: 完善说明和代码模块,添加了egg声明方式的代码,修改了koa的代码
背景: 原代码写的不够清晰,是按照 export cosnt koa写出来的, 容易导致误会,感觉只有koa才有globalPrefix,并且没有说明不同组件时,要声明在对应组件config下,cli创建的模板都是按照函数 export default export default (appInfo: MidwayAppInfo) => {}),所以更改为函数式的config,比较贴合大部分用户理解
没有任何影响,只是丰富文档
1.添加了egg声明globalPrefix方式的代码,
2.修改了koa添加globalPrefix的代码
=> docs: update global prefix descriptions

packages/midway-schedule/app.ts
当有 schedule 跳过了某个环境后，此处原 return 逻辑可能会导致其它未被遍历的 schedule 一并被跳过，而忽略他们的实际 env 配置状态。
当有 schedule 跳过了某个环境后，此处原 return 逻辑可能会导致其它未被遍历的 schedule 一并被跳过，而忽略他们的实际 env 配置状态。
比如共有 a, b, c 3 个 schedule，并在 for of 中按这个顺序遍历，a 跳过了生产环境，原逻辑会直接 return，导致后续 b，c 直接也跟着失效。
=> fix(pkg/midway-schedule/app): 修复 schedule 非预期跳过的问题

packages/i18n/src/config/config.default.ts, packages/i18n/src/interface.ts, packages/i18n/src/middleware.ts, packages/i18n/test/fixtures/base-app-express-req-locals/package.json, packages/i18n/test/fixtures/base-app-express-req-locals/src/configuration.ts, packages/i18n/test/fixtures/base-app-express-req-locals/src/user.ts, packages/i18n/test/fixtures/base-app-koa-ctx-locals/package.json, packages/i18n/test/fixtures/base-app-koa-ctx-locals/src/configuration.ts, packages/i18n/test/fixtures/base-app-koa-ctx-locals/src/user.ts, packages/i18n/test/index.test.ts, packages/view/src/contextView.ts, packages/view/src/viewManager.ts, packages/view/test/index.test.ts, packages/web-koa/src/framework.ts, packages/web-koa/test/fixtures/base-app-state-locals/package.json, packages/web-koa/test/fixtures/base-app-state-locals/src/config/config.default.ts, packages/web-koa/test/fixtures/base-app-state-locals/src/config/config.unittest.ts, packages/web-koa/test/fixtures/base-app-state-locals/src/configuration.ts, packages/web-koa/test/fixtures/base-app-state-locals/src/controller/home.ts, packages/web-koa/test/index.test.ts
related: #2287
调整了下，locals 里加了 i18n 函数，模板里可以直接用
```
{{ i18n('hello', user) }}
```
=> feat: support add locals and add case

packages/bull/package.json, site/docs/tool/sequelize_generator.md
模块包 bull 4.10.0版本不支持 redisurl 初始化配置，已经在 bull 仓库提交pr并且发布最新包，需要将依赖升级到4.10.1解决这个问题
=> chore: upgrade bull to bull redis url config

packages/core/src/context/container.ts, packages/core/src/interface.ts, packages/core/src/service/frameworkService.ts, packages/core/src/setup.ts, packages/core/test/baseFramework.test.ts, packages/core/test/fixtures/app-with-multi-framework-sequence-error/package.json, packages/core/test/fixtures/app-with-multi-framework-sequence-error/src/a.ts, packages/core/test/fixtures/app-with-multi-framework-sequence-error/src/b.ts, packages/core/test/fixtures/app-with-multi-framework-sequence-error/src/c.ts, packages/core/test/fixtures/app-with-multi-framework-sequence-error/src/configuration.ts, packages/core/test/util.ts
修复 import 顺序不一致，导致主框架获取错误的情况。
比如：
```ts
import * as bull from '@midwayjs/bull';
import * as koa from '@midwayjs/koa';
@Configuration({
imports: [koa, bull]
})
export class MainConfiguration {}
```
由于内部初始化是使用 require 的属性，即使 imports 的顺序固定，实际 bull 的 application 还是会变为 mainApp，这个时候去引入中间件，都会加到 bull 上，而不是 koa 上。
=> fix: framework loaded by import sequence

site/src/components/Splash.tsx
change h in Github to uppercase, Github should be GitHub since this is a proper noun..
=> docs: change h in Github to uppercase in web page button

site/docs/container.md
the paymentservice example contains a typo in method call (payMoney, which is misspelld as  payMonety)
correct the method call typo in the paymentservice in container.md
=> docs(site): fix typo in container.md

packages/bull/package.json
@types/bull: This is a stub types definition. bull provides its own type definitions, so you do not need this installed.
=> chore(bull): remove @types/bull

site/docs/serverless/serverless_dev.md
修复 [Serverless - 基础 - 开发函数](https://www.midwayjs.org/docs/serverless/serverless_dev) 文档中 `[f.yml 的定义](https://www.midwayjs.org/docs/serverless_yml#YoMeC)` 链接失效问题。
=> docs: fix serverless_yml link path

site/docs/legacy/orm.md
=> docs(orm):  add OrmConnectionHook example for legacy orm.md

packages/axios/src/serviceManager.ts, packages/core/src/common/serviceFactory.ts, packages/core/src/interface.ts, packages/core/test/common/serviceFactory.test.ts, packages/cos/src/manager.ts, packages/oss/src/manager.ts, packages/redis/src/manager.ts, packages/tablestore/src/manager.ts
=> feat: serviceFactory support default client name

packages/core/src/common/serviceFactory.ts, packages/core/src/decorator/common/inject.ts, packages/core/src/decorator/constant.ts, packages/core/src/interface.ts, packages/core/src/service/frameworkService.ts, packages/core/test/baseFramework.test.ts, packages/core/test/fixtures/base-app-service-factory-inject/package.json, packages/core/test/fixtures/base-app-service-factory-inject/src/configuration.ts
为 ServiceFactory 类型添加一个 @InjectClient 装饰器，方便客户端的选择注入。
比如 redis
原来：
```ts
import { RedisServiceFactory } from '@midwayjs/redis';
import { join } from 'path';
@Provide()
export class UserService {
@Inject()
redisServiceFactory: RedisServiceFactory;
async save() {
const redis1 = this.redisServiceFactory.get('instance1');
const redis2 = this.redisServiceFactory.get('instance3');
//...
}
}
```
现在
```ts
import { RedisServiceFactory } from '@midwayjs/redis';
import { join } from 'path';
@Provide()
export class UserService {
@InjectClient(RedisServiceFactory, 'instance1')
redisClient1: RedisService;
async save() {
}
}
```
=> feat: add @injectClient for service factory

packages/web-express/src/config/config.default.ts, packages/web-koa/src/config/config.default.ts, packages/web/src/config/config.default.ts
=> fix: use ctx.traceId with otel

packages/mock/src/creator.ts
=> fix: output error when running test in jest environment

packages/faas/src/framework.ts, packages/faas/src/interface.ts, packages/faas/test/fixtures/base-app-custom-response/package.json, packages/faas/test/fixtures/base-app-custom-response/src/configuration.ts, packages/faas/test/fixtures/base-app-custom-response/src/func.ts, packages/faas/test/fixtures/base-app-custom-response/src/index.ts, packages/faas/test/new.test.ts, packages/mock/src/creator.ts
=> feat: add custom response args

packages/core/src/config/config.default.ts
- 1、调整默认 logger level 为 info（原来开发环境 info，服务器 warn）
- 2、调整 coreLogger level，开发环境 info，服务器 warn
=> chore: change level for default logger level

packages/core/src/interface.ts, packages/core/src/service/loggerService.ts, packages/core/test/service/loggerService.test.ts, packages/core/test/util.ts, packages/typeorm/src/configuration.ts, packages/typeorm/src/dataSourceManager.ts, packages/typeorm/src/logger.ts
- 1、当未配置 typeorm logger 时，默认添加了一个 typeormLogger，用于输出 sql 信息
- 2、loggerService 的配置，支持 lazyLoad，这样即使有配置，也会等到 getLogger 时才创建 logger
=> feat: add typeorm logger and logger lazy create

package.json, packages/consul/package.json, packages/consul/src/configuration.ts, packages/consul/src/lib/provider.ts, packages/core/src/service/slsFunctionService.ts
=> fix(deps): update dependency consul to v1

packages/core/src/service/decoratorService.ts
自己某个项目跑 CI 时遇到了
```
TypeError: Cannot read properties of undefined (reading 'impl')
at EventEmitter.<anonymous> (/__w/midway-components/midway-components/node_modules/@midwayjs/core/dist/service/decoratorService.js:37:34)
```
=> fix(core): variable options may undefined when use custom decorator

packages/cross-domain/src/jsonp.ts, packages/cross-domain/test/express.test.ts, packages/cross-domain/test/koa.test.ts
```
import { JSONPMiddleware } from '@midwayjs/cross-domain';
Impact scope: JSONPMiddleware
```
Determine if a callback exists before performing JSONP content conversion, return original content if it doesn't exist
=> fix: repair the impact of JSONP on normal requests(#2692)

packages/core/src/service/decoratorService.ts, packages/validate/src/constants.ts, packages/validate/src/decorator/rule.ts, packages/validate/test/check.test.ts
=> fix: @valid with other decorator

packages/core/src/interface.ts, packages/core/src/service/middlewareService.ts, packages/core/src/util/index.ts, packages/core/test/service/middlewareService.test.ts
支持中间件的 match /ignore 属性写为字符串，正则，函数回调形式，以及支持以上属性的数组和动态添加形式。
字符串
```ts
class TestMiddleware {
// ...
match = '/test';
}
```
正则
```ts
class TestMiddleware {
// ...
match = /^\/test/;
}
```
方法
```ts
class TestMiddleware {
// ...
match(ctx) {
// ...
}
}
```
混合
```ts
class TestMiddleware {
// ...
match = ['/123', /^\/test/, (ctx) => {})]
}
```
动态（一般用于组件中定义中间件，需要用户配置合并的情况）
```ts
class TestMiddleware {
@Config('test.match')
testMatchConfig: [];
match = [];
@Init()
async init() {
this.match.push('/123');
this.match.push(...this.tesetMatchConfig);
}
}
```
=> feat: support match and ignore property with array

packages/cron/README.md, packages/cron/index.d.ts, packages/cron/jest.config.js, packages/cron/jest.setup.js, packages/cron/package.json, packages/cron/src/configuration.ts, packages/cron/src/constants.ts, packages/cron/src/decorator.ts, packages/cron/src/framework.ts, packages/cron/src/index.ts, packages/cron/src/interface.ts, packages/cron/test/fixtures/base-app-err/package.json, packages/cron/test/fixtures/base-app-err/src/configuration.ts, packages/cron/test/fixtures/base-app-err/src/task/hello.task.ts, packages/cron/test/fixtures/base-app/package.json, packages/cron/test/fixtures/base-app/src/configuration.ts, packages/cron/test/fixtures/base-app/src/task/hello.task.ts, packages/cron/test/index.test.ts, packages/cron/tsconfig.json
=> feat: add cron component

packages/core/src/interface.ts, packages/core/src/service/aspectService.ts, packages/core/test/service/aspectService.test.ts
indicate aop proceed whether AsyncFunction or not
判断 经过aop 包裹后的方法是否异步函数比较麻烦，添加一个属性来表明方法异步性
=> chore(core): add boolean property JoinPoint['proceedIsAsyncFunction']

packages/socketio/src/framework.ts, packages/socketio/test/fixtures/base-app-middleware/src/middleware/conn.middleware.ts
socketio
修复由于连接中间件执行时间长，而导致随机地无法收到客户端初始发送的若干消息的问题。
同时保证了客户端连接后按照如下的顺序执行：`Controller中间件` -> `OnWSConnection中间件和切面方法` -> `OnWSMessage中间件和切面方法`。
=> fix: fixed missing initial messages (#2847)

packages-legacy/serverless-app/src/framework.ts, packages-legacy/serverless-app/src/interface.ts
在 ```midway-bin dev``` 下，应用在本地开发时也可以快速使用 ```--ssl --https.key=./ssl/key.pem --https.cert=./ssl/cert.pem ```指定私钥及证书文件来启动 https 服务 #2900
=> feat: support app enable ssl custom certificate in dev mode

packages/mock/src/creator.ts, packages/mock/src/interface.ts
现在 mock 的 close 方法支持 bootstrap 和普通 app 两种，统一了 api
=> fix: bootstrap close entry

packages/code-dye/src/html.ts, packages/code-dye/src/middleware.ts, packages/code-dye/test/fixtures/koa/src/index.ts, packages/code-dye/test/koa.test.ts
codeDye在使用html模式输出的时候，如果一个异步函数未执行完成，在渲染html的时候会因找不到call.end而报错。
本次修改：
1. 判断了end是否存在，如果不存在则在函数返回值位置展示一个【未结束】的说明。
2. 将只输出第一个call修改为遍历输出所有call的callchain图像
测试用例截图：
=> feat(code-dye): outputType-html support show not end async call

packages/core/src/util/httpclient.ts, packages/core/test/util/httpclient.test.ts
如果 makeHttpRequest 发送post 请求时，包含自定义header, 比如
```js
makeHttpRequest(url, {
method: 'POST',
header: { token },
})
```
这样计算得来的 Content-Type, Content-Length 等 header 都将失败，导致 body 数据无法正常发送
修复：将 headers 从 otherOptions 中拿出
=> fix: makeHttpRequest failed when post with custom headers

packages/swagger/src/swaggerExplorer.ts, packages/swagger/test/__snapshots__/index.test.ts.snap, packages/swagger/test/fixtures/cats/src/cats.controller.ts
=> fix: swagger @ApiHeader @ApiHeaders only read one header

packages/oss/src/interface.ts
oss
在某些情况下，不引用OSS的返回值类型的时候会报[TS2742错误](https://typescript.tv/errors/#TS2742)。
这个补丁导出了`@midwayjs/oss`内的原生`OSS`对象和类型，可以避免上述问题，同时也避免引入额外的`ali-oss`依赖。
```typescript
import { OSS, OSSService } from '@midwayjs/oss';
import { Inject } from '@midayjs/core';
@Provide()
export class MyService {
@Inject()
ossService: OSSService;
async deleteMulti(keys: string[]): Promise<OSS.DeleteMultiResult> {
// 如果不声明返回值类型会报TS2742错误
return await this.ossService.deleteMulti(keys, { quiet: true });
}
}
```
=> feat: expose native OSS from package

packages/web-koa/index.d.ts, packages/web-koa/src/framework.ts, packages/web-koa/test/fixtures/base-app-forward/package.json, packages/web-koa/test/fixtures/base-app-forward/src/configuration.ts, packages/web-koa/test/index.test.ts, packages/web/app/extend/context.js, packages/web/index.d.ts, packages/web/test/feature.test.ts, packages/web/test/fixtures/feature/base-app-forward/package.json, packages/web/test/fixtures/feature/base-app-forward/src/config/config.default.ts, packages/web/test/fixtures/feature/base-app-forward/src/configuration.ts, packages/web/test/fixtures/feature/base-app-forward/src/controller/api.ts
=> feat: add ctx.forward api

packages/core/src/util/httpclient.ts, packages/core/test/util.ts, packages/core/test/util/httpclient.test.ts
core
允许`HttpClient`使用所有HTTP Method，而不仅限于GET和POST
=> feat: support all http methods

packages/core/src/decorator/faas/serverlessTrigger.ts
```target.constructor``` is not required because ```target``` is compatible with function ```attachClassMetadata```
=> chore(decorator): opt code in serverlessTrigger

packages/web/app/extend/request.js, packages/web/package.json, packages/web/test/feature.test.ts
use qs to replace querystring if config.egg.queryParseMode = 'simple'
=> fix: use qs to replace querystring to solve #2162 issue

packages/jwt/index.d.ts, packages/jwt/package.json, packages/jwt/src/jwt.ts, packages/jwt/test/fixtures/base-app-2/package.json, packages/jwt/test/fixtures/base-app-2/src/configuration.ts, packages/jwt/test/index.test.ts
jwt
这个Patch解决了JWT的几个问题：
1. 只识别`sign`的`expiresIn`参数，其它参数例，如`algorithm`，必须每次通过调用传入，而不能使用配置；
2. 原`verify`和`decode`不能提供默认配置，必须每次调用通过`options`参数指定；
3. 修复了`sign`和`verify`的参数识别问题，当提供了第二参数为密钥，且不提供第三个参数`options`时，原来的实现会错误地将密钥当作`options`，导致缺失密钥参数。
在兼容原有配置格式的基础上，新增以下配置方式:
```javascript
{
jwt: {
sign: {
// 签名参数
},
verify: {
// 验证参数
},
decode: {
// 解码的参数
},
secret: '密钥' // 私钥/公钥，取决于仅用于验证还是同时验证和签名
}
}
```
=> feat: config separated options for verify & decode and bug fixes

site/docs/extensions/jwt.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/jwt.md
Fix a bug in the documentation example where `jwtService` is not retrieved from `this`.
=> docs(jwt): Fix a bug in the documentation example where `jwtService` is not retrieved from `this`.

packages/web/app/extend/request.js, packages/web/src/interface.ts, packages/web/test/feature.test.ts, packages/web/test/fixtures/feature/base-app-query-parser/src/config/config.default.ts, site/docs/extensions/egg.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
web
通过增加simple模式的解析参数，修复 #3447 。
例如：在`config.default.ts`中，设置：
```typescript
export default {
web: {
queryParseMode: 'simple', // 指定使用qs作为解析器
queryParseOptions: {
arrayLimit: 100, // 设置将array的解析元素上限为100
}
}，
// ... 其它参数
}
```
=> fix: parsing array of size > 20 in query (#3447)

packages/web/src/config/config.default.ts, packages/web/src/logger.ts, site/docs/logger.md, site/i18n/en/docusaurus-plugin-content-docs/current/logger.md
在使用 v2 版本的 logger 时，如果使用 egg cluster 模式，midway-web.log 会变成 midway-app.log !!!!!!
=> fix(web): default app logger name error  in cluster mode

packages/core/src/util/httpclient.ts
=> feat: export http client options typings

packages/session/src/interface.ts, packages/session/src/lib/context.ts, packages/session/src/lib/session.ts, packages/session/test/fixtures/change-session-key/src/configuration.ts, packages/session/test/index.test.ts
=> fix: add regenerate method for session security

packages/mock/src/creator.ts
=> fix: serverless catch error when throw error

packages/leoric/package.json, packages/leoric/src/configuration.ts, packages/leoric/test/fixtures/logger/package.json, packages/leoric/test/fixtures/logger/src/config/config.default.ts, packages/leoric/test/fixtures/logger/src/configuration.ts, packages/leoric/test/fixtures/logger/src/controller/user.ts, packages/leoric/test/fixtures/logger/src/model/post.ts, packages/leoric/test/fixtures/logger/src/model/user.ts, packages/leoric/test/fixtures/logger/src/service/user.ts, packages/leoric/test/index.test.ts, packages/leoric/test/logger.test.ts
enable `options.logger.logQuery()`
- packages/leoric
return subclass of models when accessing leoric models with InjectModel decorator, which enables the logQuery option
the subclassing implementation works like the one in egg-orm <https://github.com/eggjs/egg-orm/blob/master/lib/loader.js#L30>, just without the Proxy
=> feat: inject ctx and app to leoric models

packages-legacy/serverless-worker-starter/src/interface.ts, packages-legacy/serverless-worker-starter/src/runtime.ts
1. 主要影响 @midwayjs/serverless-worker-starter ,支持新的 noslated-event-invoke。
=> feat(serverless-worker-starter): support noslate event

packages/swagger/src/ui/render.ts, site/blog/2024-01-13-release-3.14.md, site/docs/extensions/caching.md, site/docs/service_factory.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/caching.md, site/i18n/en/docusaurus-plugin-content-docs/current/service_factory.md
=> fix: swagger render json not match path

packages/mikro/package.json, packages/mikro/src/configuration.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/configuration.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/controller/m1.controller.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/entity/author.entity.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/entity/user.entity.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/index.ts, packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/service/book.service.ts, packages/mikro/test/fixtures/multi-enitymanager/src/config/config.default.ts, packages/mikro/test/fixtures/multi-enitymanager/src/config/config.unittest.ts, packages/mikro/test/fixtures/multi-enitymanager/src/configuration.ts, packages/mikro/test/fixtures/multi-enitymanager/src/controller/home.controller.ts, packages/mikro/test/fixtures/multi-enitymanager/src/entity/book.entity.ts, packages/mikro/test/fixtures/multi-enitymanager/src/interface.ts, packages/mikro/test/fixtures/multi-enitymanager/src/mikro-orm.config.ts, packages/mikro/test/index.test.ts
=> fix: entityManager chaos under multiple instances

packages/mock/app.js, packages/mock/function.js
=> fix: app throw initialize error when invoke close method

packages/swagger/src/swaggerExplorer.ts, packages/swagger/test/parser.test.ts
=> fix: ignore custom param decorator in swagger

packages/passport/package.json, packages/passport/src/passport/passport.service.ts, packages/passport/test/fixtures/passport-koa-bearer-fail/package.json, packages/passport/test/fixtures/passport-koa-bearer-fail/src/config/config.default.ts, packages/passport/test/fixtures/passport-koa-bearer-fail/src/configuration.ts, packages/passport/test/fixtures/passport-koa-bearer-fail/src/controller/test.controller.ts, packages/passport/test/index.test.ts
passport.service 用了 ctx.setHeader, 但是 koa 版本的实现没有提供 setHeader
=> fix: passport missing ctx.setHeader

site/docs/extensions/casbin.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/casbin.md
in the path: site-docs-extension-casbin. the basic_policy.csv file content error fixed.
=> the dosc fix of extension casbin

packages/cron/package.json
=> fix: remove typings from the cron module since it includes its own types

packages/bull-board/src/board.middleware.ts
改动点：保存 createBullBoard 的返回值，供项目内使用。
原因：主要为了解决 bull board 在动态创建队列的情况下不更新的问题，参考这个 [issue](https://github.com/felixmosh/bull-board/issues/368#issuecomment-1017291532)，需要使用 createBullBoard 返回值的 addQueue 进行手动增加队列
=> feat(bull-board): save the result of createBullBoard

site/docs/extensions/orm.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/orm.md
Add Different path support for DataSource
=> docs: update orm.md

packages/web-koa/src/framework.ts, packages/web-koa/test/index.test.ts
=> fix: make request.query writeable

packages/upload/src/config/config.default.ts, packages/upload/src/interface.ts, packages/upload/src/middleware.ts, packages/upload/src/parse.ts, packages/upload/test/fixtures/koa-function-duplicate-fields/src/configuration.ts, packages/upload/test/koa.test.ts
=> feat: add allowFieldsDuplication options

site/docs/awesome_midway.md, site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
添加 `@mwcp/pgmq` 组件 , [PGMQ] 基于 [PG] 数据库的消息队列，原生支持消息持久化和延迟消息， 类似 `AWS SQS` 或  `RSMQ`
=> docs(awesome_midway): add @mwcp/pgmq

.gitignore, packages/busboy/src/error.ts, packages/busboy/src/interface.ts, packages/busboy/src/middleware.ts, packages/busboy/src/utils.ts, packages/busboy/test/clean.test.ts, packages/busboy/test/express.test.ts, packages/busboy/test/fixtures/koa-file/src/configuration.ts, packages/busboy/test/fixtures/koa-stream/src/configuration.ts, packages/busboy/test/index.test.ts, packages/busboy/test/koa.test.ts, packages/core/src/util/webRouterParam.ts, site/blog/2024-08-29-release-3.17.md, site/docs/extensions/busboy.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/busboy.md
=> feat: busboy support async generator mode

packages-legacy/cache/src/service/cache.ts, packages/cache-manager/package.json, packages/cache-manager/test/index.test.ts, packages/swagger/src/common/enum.utils.ts, packages/swagger/src/decorators/api-exclude-controller.decorator.ts, packages/swagger/src/decorators/api-extra-model.decorator.ts, packages/swagger/src/swaggerExplorer.ts, packages/swagger/test/__snapshots__/parser.test.ts.snap, packages/swagger/test/parser.test.ts, packages/swagger/test/util.test.ts
=> fix: ensure compatibility with Swagger response schema and fix the parsing of enum types

site/docs/awesome_midway.md, site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
midway ParadeDb 组件。首个基于 Postgres 的 Elasticsearch 开源替代，采用 Rust 编写, 旨在提供快速的全文检索、语义检索和混合检索能力，适用于搜索场景     
official: https://www.paradedb.com/
link: https://pigsty.cc/zh/blog/pg/paradedb/
=> docs(awesome_midway.md): add @mwcp/paradedb

site/docs/awesome_midway.md, site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
supports gRPC (Unary) additional
=> docs(awesome_midway.md): update @mwcp/otel

packages/core/src/response/sse.ts
按照 [whatwg](https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream) 规范 ，修复之前 sse 第一次传递对象的情况，改为正常的带冒号注释。
=> fix: wrong object format for sse response

packages/info/src/config.default.ts, packages/info/src/infoService.ts, packages/info/src/interface.ts, packages/info/test/__snapshots__/index.test.ts.snap, packages/info/test/index.test.ts
=> feat: Add ignoreKey configuration, support setting key to hide the entire line of info information

packages/bull/test/fixtures/base-app/src/task/limit.task.ts, packages/bullmq/CHANGELOG.md, packages/bullmq/README.md, packages/bullmq/index.d.ts, packages/bullmq/jest.config.js, packages/bullmq/jest.setup.js, packages/bullmq/package.json, packages/bullmq/src/config/config.default.ts, packages/bullmq/src/configuration.ts, packages/bullmq/src/constants.ts, packages/bullmq/src/decorator.ts, packages/bullmq/src/framework.ts, packages/bullmq/src/index.ts, packages/bullmq/src/interface.ts, packages/bullmq/test/fixtures/base-app/package.json, packages/bullmq/test/fixtures/base-app/src/configuration.ts, packages/bullmq/test/fixtures/base-app/src/task/hello.task.ts, packages/bullmq/test/fixtures/base-app/src/task/limit.task.ts, packages/bullmq/test/fixtures/base-app/src/task/queue.task.ts, packages/bullmq/test/index.test.ts, packages/bullmq/tsconfig.json, packages/bullmq/typedoc.json
- 任务队列支持使用 bullmq 来支持更多新的队列 api，参数基本与 midwayjs/bull 一致
- 有改写 bull-board 来支持前端显示队列状态，但因为没有 pacakge 写不了依赖，没有提在这个 pr
=> feat: add package bullmq

packages/core/src/interface.ts, packages/typeorm/src/dataSourceManager.ts
=> feat: support custom data source

.github/workflows/nodejs.yml, packages/axios/index.d.ts, packages/axios/src/http-service.ts, packages/axios/src/index.ts, packages/axios/src/interface.ts, packages/mqtt/scripts/mosquitto.conf, packages/mqtt/scripts/start.sh, packages/mqtt/test/fixtures/base-app/src/configuration.ts, packages/mqtt/test/index.test.ts, site/docs/extensions/axios.md, site/i18n/en/docusaurus-plugin-content-docs/current/extensions/axios.md
=> feat: add custom axios config typings merge

packages/rabbitmq/src/framework.ts, packages/rabbitmq/src/interface.ts
> @midwayjs/rabbitmq@3.20.4 test
> node --require=ts-node/register ../../node_modules/.bin/jest --runInBand
2025-04-17 19:10:42.590 INFO 9332 Message Queue connected!
2025-04-17 19:10:43.741 INFO 9332 Rabbitmq server start success
2025-04-17 19:10:43.748 INFO 9332 test output => something to do
2025-04-17 19:10:48.189 INFO 9332 Message Queue connected!
2025-04-17 19:10:48.191 INFO 9332 Rabbitmq server start success
2025-04-17 19:10:50.810 INFO 9332 Message Queue connected!
2025-04-17 19:10:51.718 INFO 9332 Rabbitmq server start success
2025-04-17 19:11:00.700 INFO 9332 Message Queue connected!
2025-04-17 19:11:03.096 INFO 9332 Rabbitmq server start success
2025-04-17 19:11:03.283 INFO 9332 test output2 => Hello World!
2025-04-17 19:11:03.284 INFO 9332 test output1 => Hello World! …
=> feat(rabbitmq): add msg into rabbitmq ctx

site/docs/extensions/static_file.md
如果配置的静态目录不存在，则服务会报500错误，并且没有任何提醒，也不会进入到路由，虽然这个问题不常见，但还是提醒一下比较好
如果使用staticFile配置的静态目录不存在，则服务可能会抛出500错误，请确保您配置的静态目录已被正确创建。
=> docs: update static_file.md for static directory not found
