- packages/midway-mock/package.json
- packages/midway-mock/src/index.ts
> Export mock def

- packages/midway-core/src/loader.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/app/controller/home.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/app/controller/user.ts
- packages/midway-mock/bootstrap.js
- packages/midway-mock/src/index.ts
- packages/midway-mock/test/fixtures/base-app-decorator/src/app/controller/api.ts
- packages/midway-mock/test/fixtures/base-app-decorator/src/app/router.ts
- packages/midway-mock/test/index.test.ts
> Fix mm app

- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/src/loading.ts
- packages/midway-web/test/enhance.test.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/package.json
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/src/app/controller/api.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/src/app/controller/my.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/src/app/router.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/src/config/config.default.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-conflicts/src/config/config.unittest.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller/src/app/controller/my.ts
* 修复controller加载是class重复导致路由出错问题
* 解决方案，出现重复的class name报错
> fix: add controller class name as id conflicts error

- scripts/cov.sh
> 升级 scripts/cov.sh

- packages/midway-mock/bootstrap.d.ts
add typing.
add define for unit test for using app.applicationContext.
> feat: midway-mock, add typing of app.applicationContext

- docs/guide.md
add test section for midway guide
> doc: add test section for guide.md

- packages/midway/cluster/utils.js
- packages/midway/test/fixtures/apps/master-worker-started/package.json
- packages/midway/test/fixtures/midway/index.js
- packages/midway/test/fixtures/midway/package.json
- packages/midway/test/master.test.ts
- packages/midway/test/utils.ts
add unittest for test midway package
> test: add unittest for master/app&agent_worker

- packages/midway-core/test/loader.test.ts
- packages/midway-mock/test/index.test.ts
> test: add midway-mock .clusetr call

- AUTHORS
- packages/midway-mock/bootstrap.js
- packages/midway-mock/test/index.test.ts
> fix mm not a function bug

- AUTHORS
- docs/.vuepress/config.js
- package.json
- scripts/deploy.sh
- typedoc.js
> doc: add api reference with typedoc

- packages/midway-mock/src/interface.ts
To avoid tslint error like:
baseDir is not required params.
> chores: update mm.contariner params declare

- packages/midway-web/src/loading.ts
- packages/midway-web/test/enhance.test.ts
- packages/midway-web/test/utils.test.ts
> test: midway-web app#xxx & src/utils

- AUTHORS
- packages/context/package.json
- packages/context/src/base/ObjectDefinition.ts
- packages/context/src/factory/applicationContext.ts
- packages/context/src/factory/common/ManagedResolverFactory.ts
- packages/context/src/factory/container.ts
- packages/context/src/factory/requestContainer.ts
- packages/context/src/factory/xml/XmlObjectDefinition.ts
- packages/context/src/interfaces.ts
- packages/context/test/fixtures/complex_injection/dbAPI.ts
- packages/context/test/fixtures/complex_injection/userController.ts
- packages/context/test/fixtures/complex_injection/userService.ts
- packages/context/test/unit/container.test.ts
- packages/midway-core/src/loader.ts
- packages/midway-core/test/fixtures/base-app-function/src/config/plugin.ts
- packages/midway-core/test/loader.test.ts
- packages/midway-web/src/midway.ts
- packages/midway-web/test/enhance.test.ts
> Add dep map

- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/test/app/controller/home.test.ts
- packages/midway-init/package.json
`packages/midway-init`
- Make sure the generated app scaffold could pass lint & test.
- Tuning generated package.json.
> fix: lint & test failed

- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/app/public/README.md
更新初始化目录结构   https://github.com/midwayjs/midway/issues/50
> add default static file directory

- packages/midway-web/src/decorators/application.ts
[interval](https://eggjs.org/zh-cn/basics/schedule.html#interval) 字符串'5s'会通过ms转换成毫秒
[cron](https://eggjs.org/zh-cn/basics/schedule.html#cron)
[其他参数](https://eggjs.org/zh-cn/basics/schedule.html#其他参数)
> fix: Increase cron and interval and other parameter expansion

- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json
> add egg-scripts to devDependencies

- README.md
- packages/midway-core/src/loader.ts
- packages/midway-init/lib/command.js
- packages/midway-web/config/config.default.js
- packages/midway-web/src/loader/loader.ts
- packages/midway/README.md
> fix: override alinode default path

- CONTRIBUTING.md
- README.md
Fixed some typos and grammatical errors in CONTRIBUTE.md and README.md. 
Hope that helps! ;)
> <fix> proofread CONTRIBUTING.md and README.md

- docs/ioc.md
> doc:fix demo code error

- package.json
- packages/midway-mock/bootstrap.d.ts
- packages/midway-mock/src/index.ts
- packages/midway-mock/src/interface.ts
扩展更多 MidwayMockApplication 的定义。
bootstrap 的定义也一并修改。
> Add mock type

- packages/midway-schedule/app.ts
> fix: app.runSchedule task key

- docs/guide.md
> doc: remove next

- packages/midway-web/config/config.default.js
- packages/midway-web/package.json
> fix: fix default logdir for alinode plugin

- packages/midway-bin/lib/cmd/dev.js
PR for https://github.com/midwayjs/midway/issues/68#issuecomment-460015056
> feat: support process.env.PORT in dev command

- docs/.vuepress/config.js
- docs/en/README.md
- docs/en/guide.md
- docs/en/ioc.md
- docs/en/tool_set.md
- docs/en/ts_start.md
> doc: fix en website view

- packages/midway/src/index.ts
- 统一增加导出 Logger 类型，方便使用 #145 #79
> chore: add logger definition

- packages/midway-core/src/container.ts
- packages/midway-web/package.json
- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/test/enhance.test.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/package.json
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/app/controller/my.tsx
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/config/config.default.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/config/config.unittest.ts
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/shared/App.css
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/shared/App.tsx
- packages/midway-web/test/fixtures/enhance/base-app-controller-tsx/src/shared/components/Header.tsx
- packages/midway-web/tsconfig.json
> refactor: support load tsx files

- packages/midway-core/src/loader.ts
- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/src/utils.ts
之前 loadDir 默认的是应用根目录，上一次重构的时候变成了 /src 中，现在做恢复。
> Fix loaddir

- packages/midway-web/src/index.ts
- packages/midway-web/test/fixtures/enhance/base-app-middleware/src/web/middleware/api.ts
- packages/midway-web/test/fixtures/enhance/base-app-middleware/src/web/middleware/home.ts
重构完没有导出 interface，同时用例没有覆盖到。现将用例进行修改。
> chore: export interface from web

- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/client/config/config.js
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/client/package.json
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/config/config.local.ts
> midway-ant-design-pro 模版配置规范

- packages/midway-bin/lib/cmd/build.js
> Fix copy files by src dir

- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/app/controller/home.ts
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/app/controller/user.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/app/controller/home.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/app/controller/user.ts
导入 `Context` 类型用于 controller 中类方法的入口参数 `ctx`
> feat(types): import and use Context for boilerplate

- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/.vscode/settings.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/settings.json
> feat(vscode): add launch.json for vscode debug

- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/.vscode/tasks.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/tasks.json
> chore: update launch.json

- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/tsconfig.json
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/client/tsconfig.json
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/tsconfig.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/tsconfig.json
1. 格式化键名排序
2. `declaration` 改为 false。项目级别工程不需要生成 .d.ts 文件（npm 模块级别工程才需要生成，供其它项目导入，因为发布包不包含 .ts 源码文件）
3. 当 `module` 为 `commonjs` 时不需要额外设置 `moduleResolution`
4. 开启 `noFallthroughCasesInSwitch` 避免 switch-case 穿透
5. 启用所有严格类型检查选项 （对于any不便可通过关闭 `noImplicitAny` 解决）
6. 其它变动
> chore: update tsconfig.json

- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/package.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json
1. the path to the tsconfig.json via "-p tsconfig.json"
2. fixes linting errors for select rules via "--fix"
3. error style via "-t stylish"
更新 tslint 执行参数
1. the path to the tsconfig.json via "-p tsconfig.json"
2. fixes linting errors for select rules via "--fix"
3. pretty error style via "-t stylish"
> chore(scripts): update lint for tslint

- packages/midway-web/src/loader/webLoader.ts
> change private to public

- packages/midway-core/src/container.ts
- packages/midway-core/src/loader.ts
- packages/midway-core/test/loader.test.ts
- packages/midway-core/test/midwayContainer.test.ts
> refactor: add target for register hook

- packages/midway-decorator/src/web/controller.ts
- packages/midway-web/src/loader/webLoader.ts
> feat: controller opt support sensitive opt

- packages/midway-web/src/loader/webLoader.ts
> fix(webloader): remove routerArgs concat

- docs/ioc.md
none
Fix typo, gradson -> grandson.
> docs: fix typo

- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-demo-boilerplate/boilerplate/src/config/plugin.ts
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/config/config.local.ts
- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/config/plugin.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/config/plugin.ts
> chore(boilerplate): update export syntax of configurations

- packages/midway-core/package.json
* injection 将 xmldom 作为弱依赖之后，修复 midway 测试用例问题
> fix xmldom test case error

- docs/en/guide.md
- docs/guide.md
> docs(midway-init): add demo for `--type <boilerplate>` argv

- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/app/home/home.controller.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/config/config.modal.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/middleware/api.ts
- split modal to config/config.modal.ts
- add ApiMiddleware demo used by HomeController
- ApiMiddleware use new exported type Middleware according to #269
> feat(boilerplate): update midway-ts-strict

- packages/midway-schedule/.npmignore
- packages/midway-schedule/package.json
> fix(build): filter unnecessary files #277

- packages/midway-bin/lib/cmd/dev.js
增加一个新包支持 for https://github.com/alibaba/ice/pull/2437
> chore: add midway-mirror support

- packages/midway-web/src/index.ts
> feat: 导出 egg 的 Service 和 Boot 类供用户继承

- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/app/home/home.controller.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/test/app/home/home.test.ts
process response text with date string appended by middlware
因为 api 中间件附加了日期字符串，test 里面需要处理下判断。
> test(boilerplate): fix home.test.ts of midway-ts-strict

- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/src/config/config.default.ts
> bug: more quotations

- packages/midway-bin/lib/cmd/debug.js
Similar to #280, this PR supports the debug command.
> Add midway-mirror support for debug command

- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/settings.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_.gitignore
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/tsconfig.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.eslintrc.yml
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.vscode/settings.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/_.gitignore
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/test/.eslintrc.yml
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/test/tsconfig.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/tsconfig.json
> Update and fix boilerplates

- packages/midway-bin/package.json
- packages/midway-core/package.json
- packages/midway-init/package.json
- eslint to ^6.1.0
- fs-extra to ^8.1.0
- globby to ^10.0.1
> chore(deps): update deps for midway-bin, midway-core, midway-init

- packages/midway-init/boilerplate/midway-ts-ant-design-pro-boilerplate/boilerplate/server/package.json
- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/_package.json
> fix: @types/mocha has a wrong version: 6.0.0

- packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/.vscode/settings.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.vscode/settings.json
> fix(boilerplate): missing comma in .vscode/settings.json

- packages/midway-mock/package.json
> fix: app/extend 没有发布到 npm

- packages/midway-init/bin/midway-init.js
Suggest to introduce `husky` and `lint-staged` to help your team keep the code clean.
BTW, I think the `commit message follows commit guidelines` is not necessary, as you can use `squach and rebase` instead of `merge` to handle PRs.
> style(init): lint code

- packages/midway-mock/src/index.ts
- packages/midway-web/src/loader/webLoader.ts
> refactor: add monorepo path

- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.eslintignore
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.eslintrc.yml
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/src/config/config.default.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/test/.eslintrc.yml
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/tsconfig.eslint.json
update @waiting/eslint-config to v2.1 with @typescript-eslint v2.0.0
see: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0
lint 速度有提升。
> chore(deps): update eslint config for midway-ts-strict-boilerplate

- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.vscode/launch.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/.vscode/settings.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/_package.json
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/test/app/home/home.test.ts
- packages/midway-init/boilerplate/midway-ts-strict-boilerplate/boilerplate/tsconfig.eslint.json
- 可以在 vscode 中正常断点跑 mocha test 了 （必须执行单独的命令，不能是组合命令）
- powerassert 输出日志正确格式
- 其它问题
> chore(boilerplate): update midway-ts-strict-boilerplate

- packages/midway-bin/lib/cmd/debug.js
- packages/midway-bin/lib/cmd/dev.js
- packages/midway-bin/lib/util.js
- packages/midway-bin/test/lib/util.test.js
> fix: module path under mono repo

- README.md
又精简了下表格，删除了图片的 alt 文字。
- 徽标图片有指向链接， 鼠标 hover 时显示的也是前者。所以图片 alt 文字意义不大
- 保持精简格式方便以后增加 pkg
> docs: pretty README.md

- packages/midway-bin/index.js
- packages/midway-bin/lib/util.js
- packages/midway-mock/src/mock.ts
> fix(midway-bin): use resolveModule() instead of findFramework() (#344)

- docs/en/guide.md
- docs/guide.md
- docs/tool_set.md
- packages/midway-init/boilerplate.json
- packages/midway-init/lib/command.js
> refactor: add method

- packages/midway-web/config/config.default.js
> run 目录生成路径改成固定为项目根目录

- docs/en/guide.md
- docs/guide.md
- packages/midway-bin/package.json
> docs: 增加 Jest 使用文档

- packages/midway-bin/lib/cmd/build.js
> fix(midway-bin): log message grammar

- packages/midway-init/package.json
- chalk to ^3.0.0
- yargs to ^15.0.0
> chore(midway-init): update dependencies

- packages/midway-bin/lib/cmd/build.js
- packages/midway-bin/lib/cmd/clean.js
- packages/midway-bin/lib/cmd/debug.js
- packages/midway-bin/lib/cmd/dev.js
- packages/midway-bin/lib/cmd/doc.js
- packages/midway-bin/lib/cmd/test.js
- packages/midway-bin/test/lib/cmd/build.test.js
- packages/midway-bin/test/lib/cmd/clean.test.js
- packages/midway-bin/test/lib/cmd/doc.test.js
- packages/midway-bin/test/lib/cmd/index.test.js
> feat(midway-bin): use async-await instead of generator

- packages/midway-bin/lib/cmd/debug.js
- packages/midway-bin/lib/cmd/dev.js
> fix: use co wrap generator for egg-bin run method

- packages/midway-core/package.json
- packages/midway-decorator/package.json
- packages/midway-mock/package.json
- packages/midway-schedule/package.json
- packages/midway-web/package.json
> chore: upgrade injection version

- packages/midway-core/tsconfig.json
- packages/midway-decorator/tsconfig.json
- packages/midway-definition/tsconfig.json
- packages/midway-mock/tsconfig.json
- packages/midway-schedule/tsconfig.json
- packages/midway-web/tsconfig.json
- packages/midway/tsconfig.json
- packages/tslint-midway-contrib/tsconfig.json
> chore: upgrade tsconfig es version

- packages/midway-core/src/common/util.ts
- packages/midway-core/src/context/applicationContext.ts
- packages/midway-core/src/context/configuration.ts
- packages/midway-core/src/context/container.ts
- packages/midway-core/src/context/managedResolverFactory.ts
- packages/midway-core/src/context/midwayContainer.ts
- packages/midway-core/src/context/requestContainer.ts
- packages/midway-core/src/definitions/functionDefinition.ts
- packages/midway-core/src/definitions/objectDefinition.ts
- packages/midway-core/src/interface.ts
- packages/midway-core/src/service/configService.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/articleManager.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/articleManager.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/articleManager.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/configuration.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/configuration.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/configuration.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/replaceManager.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/replaceManager.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/dist/replaceManager.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/midway-plugin-mod/package.json
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/lib/service.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/midway-plugin-mock/tsconfig.json
- packages/midway-core/test/fixtures/app-with-configuration-namespace/midway-plugin-ok/package.json
- packages/midway-core/test/fixtures/app-with-configuration/base-app-decorator/src/lib/service.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-ok/src/configuration.ts
- packages/midway-core/test/loader.test.ts
- packages/midway-decorator/src/annotation/inject.ts
- packages/midway-decorator/src/interface.ts
* 解决扩展包类可能与业务代码互相冲突问题
* 重构了 configuration 加载方式，限制只加载一层，扩展中不能再添加扩展
* 修复测试用例问题
> feat: add namespace feature

- packages/midway-bin/lib/cmd/build.js
- packages/midway-bin/package.json
> fix(deps): add terser to depenencies

- packages/midway-bin/lib/cmd/build.js
- packages/midway-bin/test/fixtures/ts-dir-no-config/a.ts
- packages/midway-bin/test/lib/cmd/build.test.js
> fix: build-tsConfig

- packages/midway-web/src/index.ts
- packages/midway-web/test/issue.test.ts
> Remove core export

- package.json
- packages/eslint-midway-contrib/.eslintrc.yml.sample
- packages/eslint-midway-contrib/README.md
- packages/eslint-midway-contrib/base.js
- packages/eslint-midway-contrib/eslintrc.json
- packages/eslint-midway-contrib/index.js
- packages/eslint-midway-contrib/package.json
- packages/eslint-midway-contrib/plugins/import.yml
- packages/eslint-midway-contrib/recommended.js
- packages/eslint-midway-contrib/strict.js
- packages/eslint-midway-contrib/test/basic.js
- packages/eslint-midway-contrib/tsconfig.eslint.json.sample
- packages/eslint-midway-contrib/tsconfig.json
> feat(eslint-midway-contrib): add pkg for js and ts

- packages/midway-core/src/context/configuration.ts
- packages/midway-core/src/context/midwayContainer.ts
- packages/midway-core/src/interface.ts
- packages/midway-core/test/fixtures/app-with-configuration/base-app-decorator/src/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration/base-app-decorator/src/lib/service.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-mock/src/configuration.ts
- packages/midway-core/test/loader.test.ts
* 修复 configuration 扫描路径配置错误bug(未添加 pkg.main 目录问题)
* 增加遗留 importObjects 注册支持
> fix: configuration bugs

- packages/midway-core/src/common/util.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/articleManager.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/articleManager.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/articleManager.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/configuration.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/configuration.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/configuration.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/replaceManager.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/replaceManager.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/replaceManager.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/package.json
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/lib/userManager.ts
- packages/midway-core/test/loader.test.ts
> fix: namespace @ bugfix

- packages/midway-core/src/context/configuration.ts
- packages/midway-core/src/context/midwayContainer.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.default.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.default.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.default.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.local.d.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.local.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/config.local.js.map
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/node_modules/@midwayjs/midway-plugin-atmod/dist/configuration.js
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/config.default.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/config.local.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/base-app-decorator/src/lib/service.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/midway-plugin-mock/src/config.default.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/midway-plugin-mock/src/config.local.ts
- packages/midway-core/test/fixtures/app-with-configuration-namespace/midway-plugin-mock/src/configuration.ts
- packages/midway-core/test/loader.test.ts
* 修复 configuration 加载 config.*.ts 文件路径bug问题
* 修复重复 load 当前代码目录问题
> fix: configuration load config bug

- packages/eslint-midway-contrib/base.js
to solve "'describe' is not defined  no-undef"
env 变量中添加 mocha
> chore(eslint-midway-contrib): add mocha into env

- packages/midway-core/src/requestContainer.ts
> feat: MidwayRequestContainer 增加泛型标注

- .github/workflows/nodejs.yml
- packages/eslint-midway-contrib/base.js
- packages/midway-mock/app/extend/application.js
- packages/midway-mock/package.json
- packages/midway-mock/src/app/extend/application.ts
用 ts 实现 app/extend/application， 原 app/extend/application.js 作为入口文件来导入编译结果文件 dist/app/extend/application.js
> refactor: Midway mock refactor

- packages/midway-core/src/container.ts
> fix: disable follow symbolic link

- packages/midway-core/src/context/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration/base-app-no-package-json/src/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration/base-app-no-package-json/src/lib/service.ts
- packages/midway-core/test/fixtures/app-with-configuration/base-app-no-package-json/src/lib/userManager.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-no-pkg-json/dist/config/config.default.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-no-pkg-json/dist/config/config.local.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-no-pkg-json/dist/configuration.ts
- packages/midway-core/test/fixtures/app-with-configuration/midway-plugin-no-pkg-json/dist/replaceManager.ts
- packages/midway-core/test/loader.test.ts
> fix: modified configuration load logic

- packages/midway-core/src/context/managedResolverFactory.ts
- packages/midway-core/test/context/container.test.ts
- packages/midway-core/test/fixtures/circular_dependency.ts
> fix: 修复循环引用bug

- packages/midway-core/package.json
- packages/midway-core/src/context/applicationContext.ts
- packages/midway-core/src/context/midwayContainer.ts
- packages/midway-core/src/definitions/objectCreator.ts
- packages/midway-core/src/interface.ts
- packages/midway-core/test/context/applicationContext.test.ts
- packages/midway-core/test/context/container.test.ts
- packages/midway-core/test/context/midwayContainer.test.ts
- packages/midway-core/test/definitions/objectCreator.test.ts
- packages/midway-web/package.json
- packages/midway-web/src/index.ts
- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/src/midway.ts
- packages/midway-web/test/enhance.test.ts
- packages/midway-web/test/fixtures/complex_injection/dbAPI.ts
- packages/midway-web/test/fixtures/complex_injection/userController.ts
- packages/midway-web/test/fixtures/complex_injection/userService.ts
- packages/midway-web/test/loader.test.ts
- 1、move graphviz to web package
- 2、remove xmldom
- 3、remove co，unsupport generator function
> Core package code simplified

- docs/guide.md
> docs: add the config keyword

- packages/eslint-midway-contrib/base.js
- packages/eslint-midway-contrib/package.json
bump:
- @typescript-eslint/*
- eslint-plugin-unicorn
remove:
- @typescript-eslint/eslint-plugin-tslint （不使用 tslint 规则，则无需安装此插件）
> chore：Midway eslint contrib

- packages/eslint-midway-contrib/package.json
- packages/eslint-midway-contrib/plugins/import.yml
规则 `import/order` 增加 `alphabetize` 选项，实现（自动）对导入模块的按字母排序功能
> chore: midway eslint contrib

- packages/midway-decorator/src/faas/fun.ts
- packages/midway-decorator/test/faas/fun.test.ts
> refactor: @Func support class member method

- packages/midway-decorator/src/faas/fun.ts
> fix: @Func return type

- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/src/midway.ts
> refactor: add router dump config

- packages/midway-core/package.json
- packages/midway-core/src/common/lodashWrap.ts
- packages/midway-core/src/context/managedResolverFactory.ts
- packages/midway-core/test/context/requestContainer.test.ts
- packages/midway-core/test/fixtures/circular_dependency.ts
- packages/midway-web/test/enhance.test.ts
- packages/midway-web/test/fixtures/enhance/base-app-decorator/src/app/controller/circular.ts
- packages/midway-web/test/fixtures/enhance/base-app-decorator/src/lib/circular.ts
- packages/midway-web/test/fixtures/enhance/base-app-decorator/src/lib/fun.ts
- packages/midway-web/test/fixtures/enhance/base-app-decorator/src/lib/planA.ts
> fix: fix dfs circular

- packages/midway-core/src/loader.ts
- packages/midway-core/test/loader.test.ts
> refactor: disable conflicts check

- packages/midway-decorator/src/faas/handler.ts
- packages/midway-decorator/test/faas/fun.test.ts
- packages/midway-decorator/test/faas/handler.test.ts
> refactor: handler decorator compatible

- docs/en/guide.md
- docs/guide.md
通过midway-init生成的项目service没有在lib文件夹下，而是和app同层
> docs: fix service path

- .gitpod.yml
- README.md
- README.zh-CN.md
this commit adds support for Gitpod.io, a free automated
dev environment that makes contributing and generally working on GitHub
projects much easier. It allows anyone to start a ready-to-code dev
environment for any branch, issue and pull request with a single click.
> Add gitpod config

- .editorconfig
- docs/en/guide.md
- docs/guide.md
- packages/midway-bin/jest/env.js
- packages/midway-mock/src/bootstrap.ts
> fix: jest support

- packages/midway-core/src/common/constants.ts
- packages/midway-core/src/context/midwayContainer.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/config.default.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/config/config.daily.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/config/config.local.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/config/config.pre.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/config/config.prod.ts
- packages/midway-core/test/fixtures/app-with-configuration-config-dir/src/configManager.ts
- packages/midway-core/test/loader.test.ts
- packages/midway-decorator/src/framework/config.ts
- 1、增加配置 `export default` 和函数返回形式下的测试
- 2、增加全局注入配置能力
```ts
// 以固定 key
@Config(MIDWAY_ALL_CONFIG)
allConfig;
```
这种情况下，会注入所有整个 config 对象。
> refactor: support inject all config

- .githooks/pre-commit/filter.sh
- package.json
> refactor: Remove git hooks

- packages/midway-decorator/src/faas/fun.ts
- packages/midway-decorator/src/faas/handler.ts
> fix: fun typing

- packages/midway-web/src/utils.ts
> feat: add env switch to disable ts

- packages/midway-core/src/interface.ts
- packages/midway-core/test/fixtures/base-app-forbindapp/src/configuration.ts
- packages/midway-web/src/loader/webLoader.ts
- packages/midway-web/src/midway.ts
> Add app def

- lerna.json
- package.json
- packages/eslint-midway-contrib/recommended.js
- packages/midway-bin/package.json
- packages/midway-init/package.json
- fix: lerna nohoist config for eslint-midway-contrib
- upgrade top typescript to ^3.9.3
- upgrade pkg/* eslint to 7
- update eslint-midway-contrib rules
> fix: lerna nohoist config for eslint-midway-contrib

- README.md
- packages/midway-core/package.json
- packages/midway-core/src/container.ts
- packages/midway-init/test/init.test.js
> refactor: replace glob module

- .github/workflows/nodejs.yml
- packages/midway-core/test/context/midwayContainer.test.ts
- packages/midway-decorator/src/annotation/objectDef.ts
- packages/midway-decorator/src/common/decoratorManager.ts
- packages/midway-decorator/test/fixtures/decorator/customClass.ts
- packages/midway-decorator/test/web/controller.test.ts
- packages/midway-init/test/init.test.js
* 修复 controller 继承导致 router 覆盖 bug
> fix: 2.x extends bug

- README.md
> doc: remove dead links

- packages/faas/src/starter.ts
- packages/faas/test/fixtures/base-app-inject-logger/package.json
- packages/faas/test/fixtures/base-app-inject-logger/src/index.ts
- packages/faas/test/fixtures/base-app-inject-logger/src/logger.ts
- packages/faas/test/index.test.ts
> fix: fix inject sington logger

- packages/faas-cli-plugin-create/src/index.ts
- packages/gateway-common-http/src/common.ts
- packages/serverless-spec-builder/src/wrapper.ts
- packages/serverless-spec-builder/wrapper.ejs
+ http common support method match
> fix: http support method match

- packages/faas/src/starter.ts
- packages/faas/test/fixtures/base-app-inject-logger/src/index.ts
修复上下文设置值过于靠后，导致如果没传 logger 无法正确赋值的问题。
> fix: fix logger set after ioc set

- packages/faas-cli-plugin-invoke/src/index.ts
- packages/faas-cli-plugin-package/src/index.ts
- packages/serverless-spec-builder/wrapper.ejs
> chore: JSON 输出时自动格式化，确保可读性

- packages/serverless-spec-builder/src/fc/builder.ts
- packages/serverless-spec-builder/src/interface.ts
- packages/serverless-spec-builder/test/fc.test.ts
- packages/serverless-spec-builder/test/fixtures/fc/f-event-name.yml
> feat: add  name for fc event

- package.json
- scripts/sync.js
- scripts/sync_status.js
> chore: faster sync script

- packages/faas/src/hooks.ts
- packages/faas/src/interface.ts
- packages/faas/src/starter.ts
- packages/faas/test/fixtures/midway-hooks/f.yml
- packages/faas/test/fixtures/midway-hooks/package.json
- packages/faas/test/fixtures/midway-hooks/src/config.ts
- packages/faas/test/fixtures/midway-hooks/src/config/config.daily.ts
- packages/faas/test/fixtures/midway-hooks/src/config/config.default.ts
- packages/faas/test/fixtures/midway-hooks/src/config/config.local.ts
- packages/faas/test/fixtures/midway-hooks/src/config/config.pre.ts
- packages/faas/test/fixtures/midway-hooks/src/configuration.ts
- packages/faas/test/fixtures/midway-hooks/src/index.ts
- packages/faas/test/fixtures/midway-hooks/src/inject.ts
- packages/faas/test/fixtures/midway-hooks/src/instance.ts
- packages/faas/test/fixtures/midway-hooks/src/logger.ts
- packages/faas/test/index.test.ts
> feat: add builtin hooks

- packages/serverless-fc-trigger/src/http.ts
> fix: curl in windows

- packages/runtime-engine/src/lib/logger.ts
There is problem while file was renamed, but here can't check this situation.
> fix: log rotate failed

- packages/express-layer/index.js
- packages/express-layer/test/fixtures/app-fc/app.js
- packages/koa-layer/index.js
- packages/koa-layer/test/fixtures/app-fc/app.js
- packages/runtime-engine/src/lib/parser.ts
- packages/runtime-engine/src/lightRuntime.ts
> fix: support async  entry for  koa/express

- packages/express-layer/index.js
> fix: update header after gizp

- packages/decorator/src/web/controller.ts
- packages/decorator/src/web/requestMapping.ts
- packages/decorator/test/annotation/configuration.test.ts
- packages/decorator/test/annotation/inject.test.ts
- packages/decorator/test/annotation/objectDef.test.ts
- packages/decorator/test/annotation/pipeline.test.ts
- packages/decorator/test/annotation/priority.test.ts
- packages/decorator/test/annotation/provide.test.ts
- packages/decorator/test/annotation/schedule.test.ts
- packages/decorator/test/common/decoratorManager.test.ts
- packages/decorator/test/common/utils.test.ts
- packages/decorator/test/faas/fun.test.ts
- packages/decorator/test/faas/handler.test.ts
- packages/decorator/test/framework/app.test.ts
- packages/decorator/test/framework/config.test.ts
- packages/decorator/test/framework/logger.test.ts
- packages/decorator/test/framework/plugin.test.ts
- packages/decorator/test/rpc/hsf.test.ts
- packages/decorator/test/web/controller.test.ts
- packages/decorator/test/web/paramMapping.test.ts
- packages/decorator/test/web/requestMapping.test.ts
> refactor: add swagger description meta for swagger

- packages/web-express/test/fixtures/base-app/src/controller/api.ts
- packages/web-express/test/index.test.ts
> chore: add express case

- packages/web/src/application.ts
- packages/web/test/fixtures/issue/base-app-delay-load/package.json
- packages/web/test/fixtures/issue/base-app-delay-load/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-delay-load/src/config/config.unittest.ts
- packages/web/test/fixtures/issue/base-app-delay-load/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-delay-load/src/controller/home.ts
- packages/web/test/issue.test.ts
> fix: delay loader.load after midway bootstrap init

- packages/web/src/application.ts
- packages/web/src/framework.ts
- packages/web/test/fixtures/issue/base-app-configuration-plugin/package.json
- packages/web/test/fixtures/issue/base-app-configuration-plugin/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-configuration-plugin/src/config/config.unittest.ts
- packages/web/test/fixtures/issue/base-app-configuration-plugin/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-configuration-plugin/src/controller/home.ts
- packages/web/test/issue.test.ts
> fix: trigger lifecycle after egg load

- packages/faas/src/hooks.ts
> feat(hooks): use app hooks

- packages/midway-schedule/app.ts
> fix: first schedule ignore stop other schedule

- packages-serverless/runtime-engine/src/interface.ts
- packages-serverless/runtime-engine/src/runtime.ts
- packages-serverless/runtime-engine/test/runtime.test.ts
- packages-serverless/serverless-aws-starter/src/runtime.ts
- packages-serverless/serverless-aws-starter/test/index.test.ts
- packages-serverless/serverless-fc-starter/src/runtime.ts
- packages-serverless/serverless-fc-starter/test/index.test.ts
- packages-serverless/serverless-scf-starter/src/runtime.ts
- packages-serverless/serverless-scf-starter/test/index.test.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/test/fixtures/base-app-middleware/src/index.ts
- packages/faas/test/index.test.ts
support fc, scf and aws lambda
> feat: add getFunctionName() and functionSerivceName() method to runtime and faas framework

- packages/web/src/base.ts
修复在不同的 monorepo cwd 场景下，启动 eggjs 的问题。
> fix: monorepo use different cwd

- README.md
There goes a few typos and grammatical errors in README.
I've got them correct.
> chore: correct typos and grammatical errors

- .github/workflows/nodejs.yml
- drop nodejs v13
- add nodejs v15
> chore(ci): update nodejs.yml nodejs

- packages/mock/src/client/rabbitMQ.ts
fix: #787 修复rabbitmq client被覆盖的问题
> fix: 修复rabbitmq client mock

- packages/web-express/src/framework.ts
- packages/web-express/test/fixtures/base-app/src/controller/api.ts
- packages/web-express/test/index.test.ts
修复：https://github.com/midwayjs/midway/issues/803
> fix: express router missing

- packages/mock/src/interface.ts
- packages/mock/src/utils.ts
> fix: mockClassFunction missing

- packages/logger/src/transport.ts
related issue https://github.com/namshi/winston-graylog2/pull/84
> fix: winston-transport build error when enable esModuleInterop

- packages/mock/src/utils.ts
> fix: optional options

- packages/web/src/logger.ts
- packages/web/test/fixtures/apps/mock-dev-app-logger/package.json
- packages/web/test/fixtures/apps/mock-dev-app-logger/src/config/config.default.ts
- packages/web/test/logger.test.ts
> fix: file transport context formatter missing

- packages/rabbitmq/package.json
- packages/rabbitmq/src/config/config.default.ts
- packages/rabbitmq/src/configuration.ts
- packages/rabbitmq/src/index.ts
- packages/rabbitmq/src/interface.ts
- packages/rabbitmq/src/logger.ts
- packages/rabbitmq/src/service/rabbitmqProducer.ts
- packages/rabbitmq/test/fixtures/base-app/src/configuration.ts
功能描述：rabbitmq component
使用方法：
```
import * as rabbitmq from '@midwayjs/rabbitmq';
// 在configuration.ts中，import：rabbitmq这个component
```
方法调用：
```
import { RabbitmqProducer } from '@midwayjs/rabbitmq';
// 然后通过inject('rabbitmq:rabbitmqProducer'); 然后内部会暴露getChannel()方法获取channel，getConnection()获取connection
```
配置：
```
// 在配置文件中，config.rabbitmq = { url: 'amqp://localhost'}，进行配置
```
> feat: rabbitmq component

- packages/web/src/framework/web.ts
> fix: context logger mixin

- packages/typegoose/package.json
- packages/web/app.js
- packages/web/package.json
- packages/web/src/base.ts
- packages/web/test/fixtures/issue/base-app-socketio/package.json
- packages/web/test/fixtures/issue/base-app-socketio/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-socketio/src/config/plugin.ts
- packages/web/test/fixtures/issue/base-app-socketio/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-socketio/src/controller/home.ts
- packages/web/test/issue.test.ts
> fix: egg socket io missing session middleware

- packages/logger/src/format.ts
- packages/logger/src/interface.ts
- packages/logger/src/logger.ts
- packages/logger/test/index.test.ts
- packages/logger/test/util.ts
支持了 logger.write 方法，write 方法忽略所有的格式，只输出 message。
> feat: add logger.write method

- packages/core/src/logger.ts
- packages/logger/src/format.ts
- packages/logger/src/interface.ts
- packages/logger/src/logger.ts
- packages/logger/test/index.test.ts
1、增加方法
```ts
expect(logger.isEnableConsole()).toBeTruthy();
expect(logger.isEnableFile()).toBeTruthy();
expect(logger.isEnableError()).toBeFalsy();
```
2、请求作用域对象下，info 增加 ctx。
> feat: add enable method

- packages-serverless/serverless-http-parser/src/request.ts
- packages-serverless/serverless-http-parser/test/index.test.ts
- packages-serverless/serverless-http-parser/test/resource/fc_apigw_post_json_https.json
> fix: add request secure

- packages/decorator/src/microservice/provider.ts
- packages/grpc/src/comsumer/clients.ts
- packages/grpc/src/comsumer/configuration.ts
- packages/grpc/src/comsumer/type/duplex-request.ts
- packages/grpc/src/comsumer/type/readable-request.ts
- packages/grpc/src/comsumer/type/unary-request.ts
- packages/grpc/src/comsumer/type/writeable-request.ts
- packages/grpc/src/interface.ts
- packages/grpc/src/provider/framework.ts
- packages/grpc/src/util.ts
- packages/grpc/test/fixtures/base-app-multiple-service/src/interface.ts
- packages/grpc/test/fixtures/base-app-multiple-service/src/provider/hero.ts
- packages/grpc/test/fixtures/base-app-stream/package.json
- packages/grpc/test/fixtures/base-app-stream/src/configuration.ts
- packages/grpc/test/fixtures/base-app-stream/src/interface.ts
- packages/grpc/test/fixtures/base-app-stream/src/provider/math.ts
- packages/grpc/test/fixtures/base-app/src/provider/greeter.ts
- packages/grpc/test/fixtures/proto/math.proto
- packages/grpc/test/index.test.ts
- 1、支持 grpc 流式调用和服务
- 2、重写客户端 API
> feat: support gRPC stream API

- packages/core/src/util/webRouterParam.ts
- packages/decorator/src/web/paramMapping.ts
- packages/web-koa/package.json
- packages/web-koa/test/fixtures/base-app/src/configuration.ts
- packages/web-koa/test/fixtures/base-app/src/controller/param.ts
- packages/web-koa/test/index.test.ts
- packages/web/test/enhance.test.ts
- packages/web/test/fixtures/enhance/base-app-decorator/src/app/controller/param.ts
> feat: support queries decorator

- packages/web/src/logger.ts
- packages/web/test/logger.test.ts
- scripts/show_version.js
> fix: remove file options

- packages/grpc/src/provider/framework.ts
- packages/grpc/test/fixtures/base-app-stream/src/provider/math.ts
- packages/grpc/test/index.test.ts
移除 grpc 发布服务时必传的 url，服务端默认就是 localhost。
> refactor: remove required parameter

- packages/core/src/baseFramework.ts
- packages/core/src/context/midwayContainer.ts
- packages/core/src/functional/configuration.ts
- packages/core/src/interface.ts
- packages/core/src/loader.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-functional-component/src/configuration.ts
> refactor: lifecycle add app

- .gitignore
- packages/core/src/common/reflectTool.ts
- packages/core/src/context/midwayContainer.ts
- packages/core/src/context/resolverHandler.ts
- packages/core/src/definitions/functionDefinition.ts
- packages/core/src/definitions/objectDefinition.ts
- packages/core/src/interface.ts
- packages/core/test/context/container.test.ts
- packages/core/test/fixtures/class_sample.ts
- packages/decorator/src/common/decoratorManager.ts
> fix: property decorator and class decorator extends

- packages/web-express/test/fixtures/base-app-wildcard/package.json
- packages/web-express/test/fixtures/base-app-wildcard/src/config/config.default.ts
- packages/web-express/test/fixtures/base-app-wildcard/src/config/config.unittest.ts
- packages/web-express/test/fixtures/base-app-wildcard/src/configuration.ts
- packages/web-express/test/fixtures/base-app-wildcard/src/controller/home.ts
- packages/web-express/test/index.test.ts
- packages/web-koa/src/framework.ts
- packages/web-koa/test/fixtures/base-app-wildcard/package.json
- packages/web-koa/test/fixtures/base-app-wildcard/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-wildcard/src/config/config.unittest.ts
- packages/web-koa/test/fixtures/base-app-wildcard/src/configuration.ts
- packages/web-koa/test/fixtures/base-app-wildcard/src/controller/home.ts
- packages/web-koa/test/index.test.ts
> fix: koa-router support wildcard

- README.md
> doc: update cn readme

- packages-serverless/serverless-app/src/index.ts
- packages-serverless/serverless-app/src/interface.ts
- packages-serverless/serverless-app/src/platform.ts
- packages-serverless/serverless-app/src/utils.ts
> fix: serverless app layers support

- packages/logger/src/interface.ts
- packages/logger/src/logger.ts
- packages/logger/test/index.test.ts
with type LoggerCustomInfoHandler
ref PR: https://github.com/midwayjs/midway/pull/897/
> chore(logger): add ReturnType of MidwayBaseLogger.customInfoHandler

- packages/web/app.js
- packages/web/src/base.ts
- packages/web/test/fixtures/issue/base-app-egg-router/package.json
- packages/web/test/fixtures/issue/base-app-egg-router/src/app/controller/eggTest.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/app/router.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/config/config.unittest.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/config/plugin.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/controller/home.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/interface.ts
- packages/web/test/fixtures/issue/base-app-egg-router/src/middleware/client_checker.ts
- packages/web/test/issue.test.ts
> fix: load egg router before midway container ready

- packages/decorator/src/annotation/rule.ts
- packages/decorator/test/annotation/check.test.ts
> fix: validator class extends

- packages/grpc/src/comsumer/clients.ts
- packages/grpc/src/comsumer/configuration.ts
- packages/grpc/src/util.ts
- packages/grpc/test/fixtures/base-app-multiple-package/package.json
- packages/grpc/test/fixtures/base-app-multiple-package/src/configuration.ts
- packages/grpc/test/fixtures/base-app-multiple-package/src/interface.ts
- packages/grpc/test/fixtures/base-app-multiple-package/src/provider/greeter.ts
- packages/grpc/test/fixtures/proto/hello_world.proto
- packages/grpc/test/index.test.ts
> fix: multi package name in grpc client

- README.md
- packages-serverless/serverless-app/package.json
- packages-serverless/serverless-app/src/index.ts
- packages-serverless/serverless-app/src/interface.ts
- packages-serverless/serverless-app/src/platform.ts
- packages-serverless/serverless-app/src/utils.ts
- packages-serverless/serverless-app/test/intergration-v2.test.ts
> fix: serverless app layers

- packages/core/src/interface.ts
- add IMidwayLogger as instead
- escape '@' for pretty hint
> chore(core): update comments of IMidwayLogger

- packages-serverless/express-layer/index.js
- packages-serverless/koa-layer/index.js
- packages/core/src/interface.ts
- packages/core/src/logger.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/logger.test.ts
> fix: create log dir in serverless environment

- packages-serverless/serverless-app/package.json
- packages-serverless/serverless-app/src/index.ts
- packages-serverless/serverless-app/src/start.ts
- packages-serverless/serverless-app/src/utils.ts
- packages-serverless/serverless-app/test/faas-v2.test.ts
- packages-serverless/serverless-app/test/fixtures/faas-v2/src/controller.ts
> fix: /user/ => /user

- packages-serverless/egg-layer/framework/config/config.default.js
- packages-serverless/egg-layer/index.js
- packages-serverless/egg-layer/test/fixtures/eaas-fc/app/controller/home.js
- packages-serverless/egg-layer/test/fixtures/eaas-fc/app/router.js
- packages-serverless/egg-layer/test/fixtures/eaas-scf/app/controller/home.js
- packages-serverless/egg-layer/test/fixtures/eaas-scf/app/router.js
- packages-serverless/egg-layer/test/index.test.js
- packages-serverless/express-layer/index.js
- packages-serverless/express-layer/test/fixtures/app-scf/app.js
- packages-serverless/express-layer/test/index.test.js
- packages-serverless/koa-layer/index.js
- packages-serverless/koa-layer/test/fixtures/app-fc/app.js
- packages-serverless/koa-layer/test/fixtures/app-scf/app.js
- packages-serverless/koa-layer/test/index.test.js
- packages-serverless/static-layer/index.js
> fix: client ip proxy to real server

- packages/bootstrap/src/bootstrap.ts
- packages/mock/src/utils.ts
- packages/web/src/framework/singleProcess.ts
- packages/web/src/index.ts
- 1、修复 bootstrap 启动循环了多次，导致内存里多了几个示例，在本地开发的时候 cli 识别会出问题
- 2、移除了一些多余的老代码
- 3、调整了一下单进程 web 框架的名字，更方便识别
> fix: bootstrap cache error framework

- packages-serverless/runtime-mock/src/trigger.ts
- packages-serverless/serverless-app/index.d.ts
- packages-serverless/serverless-app/package.json
- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/test/faas-v2.test.ts
- packages-serverless/serverless-app/test/fixtures/faas-v2/src/event.ts
- packages-serverless/serverless-fc-trigger/package.json
- packages-serverless/serverless-fc-trigger/src/base.ts
- packages-serverless/serverless-fc-trigger/src/cdn.ts
- packages-serverless/serverless-fc-trigger/src/mns.ts
- packages-serverless/serverless-fc-trigger/src/oss.ts
- packages-serverless/serverless-fc-trigger/src/sls.ts
- packages-serverless/serverless-fc-trigger/src/tableStore.ts
- packages-serverless/serverless-fc-trigger/src/timer.ts
- packages-serverless/serverless-fc-trigger/test/index.test.ts
- packages-serverless/serverless-scf-trigger/package.json
- packages-serverless/serverless-scf-trigger/src/apiGateway.ts
- packages-serverless/serverless-scf-trigger/src/base.ts
- packages-serverless/serverless-scf-trigger/src/ckafka.ts
- packages-serverless/serverless-scf-trigger/src/cmq.ts
- packages-serverless/serverless-scf-trigger/src/cos.ts
- packages-serverless/serverless-scf-trigger/src/timer.ts
- packages/decorator/src/interface.ts
- packages/faas/src/interface.ts
> fix: serverless event test

- packages/core/src/context/midwayContainer.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/book/package.json
- packages/core/test/fixtures/app-with-component-inject-with-class/book/src/bookService.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/book/src/configuration.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/book/src/index.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/main/package.json
- packages/core/test/fixtures/app-with-component-inject-with-class/main/src/configuration.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/main/src/controller/user.ts
> chore: add private meta

- packages-serverless/serverless-app/test/faas-v2.test.ts
- packages-serverless/serverless-app/test/fixtures/faas-v2/src/func.ts
- packages/decorator/src/interface.ts
- packages/grpc/package.json
- packages/midway-schedule/package.json
- packages/mock/package.json
- packages/prometheus/package.json
- packages/typegoose/package.json
> chore: support more definition

- packages-serverless/serverless-app/src/platform.ts
> fix: scf starter name error

- packages/bootstrap/src/bootstrap.ts
- packages/midway-schedule/agent.ts
- packages/midway-schedule/test/schedule.test.ts
- packages/midway-schedule/test/utils.ts
- packages/mock/src/utils.ts
- packages/rabbitmq/src/framework.ts
- packages/socketio/src/framework.ts
- packages/web/package.json
- packages/web/src/base.ts
- packages/web/src/framework/singleProcess.ts
- packages/web/test/logger.test.ts
- 1、在 egg-cluster 和 layer 模式下，就不延迟 load 了
- 2、优化了 egg 的测试，现在测试不再会 force exit
> fix: delay load without layer and egg-cluster

- packages-serverless/serverless-app/jest.config.js
- packages-serverless/serverless-app/package.json
- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/src/start.ts
- packages-serverless/serverless-app/src/utils.ts
- packages-serverless/serverless-app/test/faas-start-end.test.ts
- packages-serverless/serverless-app/test/fixtures/faas-start-end/f.yml
- packages-serverless/serverless-app/test/fixtures/faas-start-end/package.json
- packages-serverless/serverless-app/test/fixtures/faas-start-end/src/configuration.ts
- packages-serverless/serverless-app/test/fixtures/faas-start-end/src/event.ts
- packages-serverless/serverless-app/test/fixtures/faas-start-end/tsconfig.json
> fix: serverless app stop

- packages/bootstrap/src/bootstrap.ts
- packages/bootstrap/test/fixtures/mix-app/src/configuration.ts
- packages/core/src/index.ts
- packages/core/src/util/contextUtil.ts
- packages/core/test/baseFramework.test.ts
> feat: support getCurrentApplicationContext API

- packages-serverless/egg-layer/package.json
- packages-serverless/egg-layer/test/.setup.js
- packages-serverless/egg-layer/test/fixtures/midway-fc/f.yml
- packages-serverless/egg-layer/test/fixtures/midway-fc/index.js
- packages-serverless/egg-layer/test/fixtures/midway-fc/package.json
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/config/config.default.ts
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/config/config.unittest.ts
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/configuration.ts
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/controller/api.ts
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/service/user.ts
- packages-serverless/egg-layer/test/index.test.js
- packages/decorator/src/common/decoratorManager.ts
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
- scripts/build.sh
- 1、为之前的 bug 增加 midway 的case，防止后续再出现问题
- 2、给 decoratorManager 增加全局警告，防止多个 decoratorManager 实例
> fix: add midway case for egg-layer and add warn for DecoratorManager

- packages-serverless/serverless-app/package.json
> fix: serverless app typings missing

- packages/core/src/util/webRouterCollector.ts
- packages/core/test/router.js
- packages/core/test/webRouterCollector.test.ts
> fix: router sort

- packages/mock/src/utils.ts
> chore: add bootstrap test timeout value

- packages-serverless/serverless-app/src/framework.ts
> fix: serverless app support serverless dev

- packages/core/src/baseFramework.ts
- packages/core/src/context/midwayContainer.ts
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/src/loader.ts
- packages/core/src/logger.ts
- packages/core/src/service/configService.ts
- packages/core/src/service/environmentService.ts
- packages/core/src/service/informationService.ts
- packages/core/src/util/index.ts
- packages/core/test/services/configService.test.ts
- packages/core/test/services/fixtures/default_case/package.json
- packages/core/test/services/informationService.test.ts
- packages/faas/src/framework.ts
- packages/web/src/framework/web.ts
> fix: load functional config

- packages/core/src/baseFramework.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-component-inject-with-class/bookstr/src/configuration.ts
> fix: lifecycle missing container when run onStop method

- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-configuration-config/custom.default.js
- packages/core/test/fixtures/app-with-configuration-config/src/configuration.ts
> test: add outer config case

- packages-serverless/runtime-engine/src/lib/logger.ts
- packages-serverless/runtime-engine/src/runtime.ts
- packages-serverless/runtime-engine/test/lib/logger.test.ts
> fix: serverless logger close when runtime stop

- packages/decorator/src/faas/fun.ts
- packages/web/src/framework/web.ts
- packages/web/test/feature.test.ts
- packages/web/test/fixtures/feature/base-app-egg-logger/package.json
- packages/web/test/fixtures/feature/base-app-egg-logger/src/config/config.default.ts
- packages/web/test/fixtures/feature/base-app-egg-logger/src/config/config.unittest.ts
- packages/web/test/fixtures/feature/base-app-egg-logger/src/configuration.ts
> fix: use egg-logger got empty logger

- packages/core/src/util/triggerCollector.ts
- packages/core/src/util/webRouterCollector.ts
- packages/core/test/util/triggerCollector.test.ts
将 all 这个协议，在 serverless 场景下，分解变为 [get, post, delete] 等真实协议。
> fix: change all requestMethod to real method for serverless http request

- packages-serverless/serverless-app/src/framework.ts
> fix: support aliyun fc cors in local env

- packages/prometheus/package.json
- packages/prometheus/src/configuration.ts
- packages/prometheus/src/utils/utils.ts
- packages/web/src/framework/singleProcess.ts
> fix(prometheus): bootstrap for egg

- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/src/interface.ts
> fix: serverless app layer

- packages/logger/src/index.ts
> chore: add export

- packages/web/app.js
> chore(web): check this.app.middlewares[name] is function

- packages/core/package.json
- packages/core/src/baseFramework.ts
- packages/core/src/interface.ts
- packages/core/src/module.d.ts
- packages/web/src/interface.ts
> chore(web): add generics parameter of IMidwayWebContext

- packages/core/src/util/webRouterCollector.ts
- packages/core/test/util/triggerCollector.test.ts
> refactor: export applicationContext for analyze

- packages/core/src/util/webRouterCollector.ts
- packages/core/test/fixtures/app-with-serverless-trigger/src/function/hello_aliyun.ts
- packages/core/test/util/triggerCollector.test.ts
- packages/decorator/src/constant.ts
- packages/decorator/src/faas/fun.ts
- packages/decorator/src/interface.ts
- packages/decorator/test/faas/__snapshots__/fun.test.ts.snap
- packages/decorator/test/faas/fun.test.ts
> feat: add decorator metadata

- packages/task/src/service/queueService.ts
> chore: add deprecated flag

- .github/workflows/nodejs.yml
- package.json
- packages-serverless/serverless-app/test/faas-v2.test.ts
- packages-serverless/serverless-app/test/intergration-v2.test.ts
- packages/consul/package.json
- packages/consul/test/consul.framework.ts
- packages/consul/test/index.test.ts
- packages/core/test/fixtures/app-with-duplicate-router/src/configuration.ts
- packages/core/test/fixtures/app-with-serverless-trigger/src/configuration.ts
- packages/logger/src/rotate.ts
- packages/midway-schedule/package.json
- packages/task/test/index.test.ts
- packages/typegoose/package.json
- packages/typegoose/src/configuration.ts
- packages/typegoose/test/fixtures/base-app/src/config/config.default.ts
- packages/typegoose/test/fixtures/base-app/src/configuration.ts
- packages/typegoose/test/index.test.ts
- packages/typegoose/test/util.ts
> chore: upgrade jest

- packages/consul/src/configuration.ts
- packages/consul/src/interface.ts
@midway/consul
新增通过配置 check=false 关闭 consul 健康检查的功能
> feat: support close consul service check

- packages/task/src/configuration.ts
- packages/task/src/service/queueService.ts
修复开发环境，分布式任务，当用户修改了cron后，老的定时任务没有清理掉的情况。
> chore: fix dev env remove old task

- packages/orm/src/configuration.ts
- packages/orm/src/index.ts
- packages/orm/test/fixtures/base-fn-multiple-db/src/event.ts
- packages/orm/test/fixtures/base-fn/src/event.ts
> feat: support EventSubscriberModel with provide

- packages/ws/src/framework.ts
- packages/ws/test/fixtures/base-app/src/socket/api.ts
> fix: remove emit required parameter

- packages/logger/src/interface.ts
- packages/logger/src/logger.ts
> feat: add date pattern parameter

- packages/bootstrap/src/bootstrap.ts
- packages/bootstrap/test/index.test.ts
> fix: add uncaughtException handler

- packages-serverless/serverless-fc-starter/src/index.ts
- packages/faas/src/framework.ts
- packages/logger/package.json
- packages/logger/src/container.ts
- packages/logger/src/logger.ts
- packages/logger/test/index.test.ts
> fix: replace ctx.logger in fc serverless environment

- packages/prometheus/src/configuration.ts
it will cause mock.close(app) fail when unit test
> fix(prometheus): this.http_server may undefined onStop

- packages/core/src/util/webRouterParam.ts
- packages/core/test/paramMapping.test.ts
- packages/web-express/test/fixtures/base-app/src/controller/api.ts
- packages/web-express/test/index.test.ts
- packages/web-koa/test/fixtures/base-app/src/controller/api.ts
- packages/web-koa/test/index.test.ts
> fix: uppercase for header decorator

- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/src/utils.ts
> refactor: serverless app optimise

- packages/logger/src/logger.ts
- packages/logger/test/index.test.ts
> fix: get complete origin args

- packages-serverless/serverless-app/src/start.ts
> fix: serverless app invoke args

- packages-serverless/serverless-http-parser/src/http/req.ts
- packages/core/src/service/configService.ts
> fix: add target parameter

- packages/ws/src/framework.ts
> fix: remove port with other framework

- packages-serverless/static-layer/index.js
- packages-serverless/static-layer/package.json
- packages-serverless/static-layer/rewrite.js
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/build/api.html
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/build/index.html
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/build/static/index.html
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/f.yml
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/index.js
- packages-serverless/static-layer/test/fixtures/app-fc-rewrite/package.json
- packages-serverless/static-layer/test/index.test.js
> fix: support ignore dsl

- packages/decorator/src/common/decoratorManager.ts
@midway/decorator
Added missing arg "groupBy?" at exported attachPropertyDataToClass in decoratorManager.
> fix: add missing arg "groupBy?" at exported attachPropertyDataToClass in decoratorManager

- packages/core/src/context/midwayContainer.ts
- packages/core/src/context/requestContainer.ts
> chore: add get context method for requestContainer

- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/src/utils.ts
> fix: cors and trigger bugs in serverless

- packages/web/src/utils.ts
> fix: find baseDir in egg

- packages/core/src/context/configuration.ts
支持通过环境变量 process.env.MIDWAY_ENABLE_CONFLICT_CHECK 开启冲突检查。
> chore: enable conflict check

- .github/workflows/nodejs.yml
- packages-serverless/serverless-worker-starter/CHANGELOG.md
- packages-serverless/serverless-worker-starter/README.md
- packages-serverless/serverless-worker-starter/jest.config.js
- packages-serverless/serverless-worker-starter/jest.setup.js
- packages-serverless/serverless-worker-starter/package.json
- packages-serverless/serverless-worker-starter/src/http-request.ts
- packages-serverless/serverless-worker-starter/src/index.ts
- packages-serverless/serverless-worker-starter/src/runtime.ts
- packages-serverless/serverless-worker-starter/test/index.test.ts
- packages-serverless/serverless-worker-starter/tsconfig.json
> feat: add serverless worker starter

- packages/web/test/enhance.test.ts
> fix: test error

- packages/web-express/src/interface.ts
> fix: add generateMiddleware definition for express app

- packages/socketio/src/framework.ts
> fix: socket listen sequelize

- packages/prometheus/package.json
- packages/prometheus/src/service/dataService.ts
> chore: allow user to define data

- packages/cache/src/service/cache.ts
- packages/cache/test/cache.test.ts
支持其他类型，原来的value只能是string。
#1103
> feat: enhance cache for #1103

- packages/oss/jest.setup.js
- packages/oss/src/manager.ts
- packages/oss/test/index.test.ts
- packages/oss/test/sts_config.ts
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
- packages/web/src/framework/singleProcess.ts
> fix: server hostname args

- packages/oss/test/index.test.ts
- packages/oss/test/sts_client.ts
> chore: sts timeout

- packages-serverless/serverless-app/src/platform.ts
- packages-serverless/serverless-vercel-starter/README.md
- packages-serverless/serverless-vercel-starter/jest.config.js
- packages-serverless/serverless-vercel-starter/jest.setup.js
- packages-serverless/serverless-vercel-starter/package.json
- packages-serverless/serverless-vercel-starter/src/index.ts
- packages-serverless/serverless-vercel-starter/src/runtime.ts
- packages-serverless/serverless-vercel-starter/test/fixtures/http/index.ts
- packages-serverless/serverless-vercel-starter/test/index.test.ts
- packages-serverless/serverless-vercel-starter/tsconfig.json
- packages-serverless/serverless-vercel-trigger/jest.config.js
- packages-serverless/serverless-vercel-trigger/jest.setup.js
- packages-serverless/serverless-vercel-trigger/package.json
- packages-serverless/serverless-vercel-trigger/src/http.ts
- packages-serverless/serverless-vercel-trigger/src/index.ts
- packages-serverless/serverless-vercel-trigger/test/fixtures/http/index.ts
- packages-serverless/serverless-vercel-trigger/test/index.test.ts
- packages-serverless/serverless-vercel-trigger/tsconfig.json
> feat: vercel starter and trigger

- packages/decorator/src/common/decoratorManager.ts
- packages/ws/src/framework.ts
> fix: decorator manager singleton

- packages/core/src/baseFramework.ts
- packages/core/src/context/configuration.ts
- packages/core/src/interface.ts
- packages/core/src/service/configService.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/base-app-config-async-load/package.json
- packages/core/test/fixtures/base-app-config-async-load/src/config/config.default.ts
- packages/core/test/fixtures/base-app-config-async-load/src/config/config.unittest.ts
- packages/core/test/fixtures/base-app-config-async-load/src/configuration.ts
- packages/core/test/fixtures/base-app-config-object/package.json
- packages/core/test/fixtures/base-app-config-object/src/config/config.default.ts
- packages/core/test/fixtures/base-app-config-object/src/config/config.unittest.ts
- packages/core/test/fixtures/base-app-config-object/src/configuration.ts
- packages/decorator/src/annotation/configuration.ts
- packages/orm/src/configuration.ts
- packages/oss/test/index.test.ts
> feat: support object config load and async config

- packages/faas/src/interface.ts
> fix: update FaasMddleware interface.ts

- packages/axios/src/configuration.ts
- packages/axios/src/index.ts
- packages/axios/src/serviceManager.ts
> fix: post missing data

- packages-serverless/egg-layer/index.js
- packages-serverless/egg-layer/test/fixtures/midway-fc/src/controller/api.ts
- packages-serverless/egg-layer/test/index.test.js
- [  ] documentation is changed or added
- fix `TypeError [ERR_UNESCAPED_CHARACTERS] Request path contains unescaped characters` in serverless.
> fix: encode request path in serverless

- packages/web/src/base.ts
> fix: find egg plugin in cwd

- packages-serverless/express-layer/index.js
- packages-serverless/koa-layer/index.js
- packages/core/src/util/serviceFactory.ts
- packages/core/test/util/serviceFactory.test.ts
> fix: empty options in default

- packages/core/src/util/containerUtil.ts
- packages/faas/src/util.ts
Co-authored-by: legendecas <legendecas@gmail.com>
> feat: support pass container while initialize framework

- packages-serverless/faas-typings/typings/common.ts
- packages-serverless/serverless-http-parser/package.json
- packages-serverless/serverless-http-parser/src/context.ts
- packages-serverless/serverless-http-parser/test/index.test.ts
- packages/oss/jest.setup.js
- packages/oss/test/sts_client.ts
> feat: add ctx.throw for serverless app

- packages/logger/package.json
- packages/logger/src/fileStreamRotator.ts
- packages/logger/src/rotate.ts
- packages/logger/src/util.ts
- packages/logger/test/fixtures/cluster-rotate.ts
- packages/logger/test/stream-rotate.test.ts
> fix: winston rotate log size limit in cluster mode

- packages/cos/README.md
- packages/cos/jest.config.js
- packages/cos/jest.setup.js
- packages/cos/package.json
- packages/cos/src/config.default.ts
- packages/cos/src/configuration.ts
- packages/cos/src/index.ts
- packages/cos/src/manager.ts
- packages/cos/test/fixtures/base-app-single-client/package.json
- packages/cos/test/fixtures/base-app-single-client/src/config.default.ts
- packages/cos/test/fixtures/base-app-single-client/src/configuration.ts
- packages/cos/test/index.test.ts
- packages/cos/tsconfig.json
- packages/oss/test/index.test.ts
> feat: add cos component

- packages/bootstrap/test/fixtures/mix-app/bootstrap.js
- packages/bootstrap/test/fixtures/mix-app/src/service/remoteConfigService.ts
- packages/core/src/context/applicationContext.ts
- packages/core/src/context/midwayContainer.ts
- packages/core/src/functional/configuration.ts
- packages/core/src/interface.ts
- packages/core/test/context/container.test.ts
- packages/core/test/fixtures/app-with-functional-component/src/configuration.ts
- packages/decorator/src/common/decoratorManager.ts
- packages/decorator/src/util/index.ts
- packages/decorator/test/annotation/inject.test.ts
- packages/decorator/test/faas/fun.test.ts
- 1、修复 ioc 容器因为提前 require 导致丢失命名空间从而找不到模块的问题，特别是在测试的场景
- 2、支持了函数式写法的 onConfigLoad 并处理了定义
> fix: can't found id in test case

- lerna.json
- packages/core/package.json
- packages/core/src/context/requestContainer.ts
- packages/core/test/fixtures/issue-1277/package.json
- packages/core/test/fixtures/issue-1277/src/configuration.ts
- packages/core/test/issue.test.ts
- packages/oss/test/index.test.ts
- scripts/generate_rollback.js
> fix: requestContainer missing ctx inject in component

- packages-serverless/egg-layer/index.js
> fix: form-data for egg-layer

- packages/decorator/src/annotation/rule.ts
- packages/decorator/src/annotation/validate.ts
- packages/decorator/src/common/decoratorManager.ts
- packages/decorator/src/index.ts
- packages/decorator/src/util/dtoHelper.ts
- packages/decorator/test/util/dtoHelper.test.ts
Co-authored-by: legendecas <legendecas@gmail.com>
> feat: add ctx.throw for serverless app (#1262)

- packages/decorator/src/annotation/rule.ts
- packages/decorator/src/annotation/validate.ts
- packages/decorator/src/common/decoratorManager.ts
- packages/decorator/src/index.ts
- packages/decorator/src/util/dtoHelper.ts
- packages/decorator/test/util/dtoHelper.test.ts
Co-authored-by: legendecas <legendecas@gmail.com>
> feat: merge DTO Helper (#1250)

- packages-serverless/serverless-app/src/framework.ts
- packages-serverless/serverless-app/src/start.ts
- packages/bootstrap/src/bootstrap.ts
> fix: serverless app support applicationContext

- packages/core/src/util/serviceFactory.ts
- packages/socketio/test/fixtures/base-app-room/src/socket/api.ts
- packages/typegoose/src/index.ts
- packages/typegoose/test/fixtures/base-app/src/service/test.ts
> chore: remove export

- packages/core/src/functional/configuration.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-functional-component/src/configuration.ts
> fix: functional configuration load async code

- packages/task/README.md
task
Changing the cron expression to five `*` to match the comment which says 'run every minute'.
> docs(task): fix cron expression per comments

- packages/core/package.json
目前 `midway-test-component` 被带入了安装，影响包体积。
> mv `midway-test-component` to devDeps

- packages/orm/src/repository.ts
- packages/orm/test/fixtures/base-fn/src/configuration.ts
> fix: getCustomRepository bug

- packages/logger/package.json
- packages/logger/src/fileStreamRotator.ts
> feat: use dayjs instead moment

- packages/passport/README.md
- packages/passport/src/express.ts
- packages/passport/src/options.ts
- packages/passport/src/web.ts
- [] tests and/or benchmarks are included
> feat: passport add presetProperty

- packages/decorator/src/decorator/common/objectDef.ts
- packages/decorator/test/annotation/objectDef.test.ts
> chore: remove default scope value

- packages/bootstrap/src/bootstrap.ts
- packages/core/src/service/loggerService.ts
- packages/core/src/setup.ts
- packages/web/test/logger.test.ts
- packages/web/test/utils.ts
> fix: logger close before bootstrap close

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/src/service/decoratorService.ts
- packages/core/src/util/index.ts
- packages/core/src/util/webRouterParam.ts
- packages/core/test/util/util.test.ts
- packages/decorator/src/decoratorManager.ts
- packages/decorator/test/decoratorManager.test.ts
- packages/faas/src/configuration.ts
- packages/validate/package.json
- packages/web-express/src/configuration.ts
- packages/web-koa/src/configuration.ts
- packages/web-koa/test/fixtures/base-app/src/controller/param.ts
- packages/web/src/configuration.ts
- packages/web/test/fixtures/enhance/base-app-decorator/src/app/controller/param.ts
> feat: auto transform args to type

- packages/decorator/src/annotation/validate.ts
- packages/decorator/test/annotation/check.test.ts
> fix: throws http code 422 when validation failed

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- packages/core/src/common/filterManager.ts
- packages/core/src/interface.ts
- packages/core/src/util/index.ts
- packages/core/test/common/filterManager.test.ts
- packages/decorator/src/decorator/common/filter.ts
> fix: @match empty args

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/service/decoratorService.ts
- packages/core/src/util/index.ts
- packages/core/test/service/decoratorService.test.ts
- packages/decorator/src/decoratorManager.ts
- packages/validate/src/configuration.ts
- packages/validate/test/check.test.ts
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
- packages/web/src/framework/web.ts
> fix: class transformer method missing

- packages/redis/src/manager.ts
> chore: remove assert for redis db options

- packages/mongoose/src/configuration.ts
- packages/typegoose/src/configuration.ts
> fix: mongoose init before config load

- packages/orm/src/index.ts
> fix: EntityView support connectionArgs

- packages/decorator/src/decorator/framework/schedule.ts
- packages/decorator/src/decorator/microservice/consumer.ts
- packages/orm/src/decorator.ts
- packages/web-express/src/framework.ts
- packages/web-express/src/interface.ts
- packages/web-express/test/fixtures/base-app-middleware/src/configuration.ts
> fix: typeorm EntityView missing connectionName

- packages-serverless/egg-layer/index.js
- packages-serverless/serverless-worker-starter/package.json
- packages-serverless/serverless-worker-starter/src/runtime.ts
- packages/core/src/common/webRouterCollector.ts
- packages/core/src/context/container.ts
- packages/core/src/interface.ts
- packages/core/src/setup.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/app-with-configuration-config-object/package.json
- packages/core/test/fixtures/app-with-configuration-config-object/src/configuration.ts
- packages/core/test/setup.test.ts
- packages/decorator/src/decorator/common/configuration.ts
- packages/faas/src/configuration.ts
- packages/faas/src/framework.ts
> fix: faas missing config in framework

- packages/faas/src/framework.ts
- packages/mongoose/package.json
- packages/passport/src/proxy/framework/koa.ts
- packages/typegoose/package.json
- packages/web-express/src/framework.ts
- packages/web-express/src/interface.ts
- packages/web-koa/src/framework.ts
- packages/web-koa/src/interface.ts
- packages/web/src/base.ts
- packages/web/src/framework/web.ts
- packages/web/src/interface.ts
> fix: generate middleware typings

- packages/core/src/error/http.ts
- packages/web-express/src/framework.ts
- packages/web-express/test/fixtures/base-app-404/package.json
- packages/web-express/test/fixtures/base-app-404/src/config/config.default.ts
- packages/web-express/test/fixtures/base-app-404/src/configuration.ts
- packages/web-express/test/fixtures/base-app-404/src/controller/api.ts
- packages/web-express/test/fixtures/base-app-global-match/src/configuration.ts
- packages/web-express/test/index.test.ts
- packages/web-koa/src/framework.ts
- packages/web-koa/src/onerror.ts
- packages/web-koa/test/fixtures/base-app-404/package.json
- packages/web-koa/test/fixtures/base-app-404/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-404/src/configuration.ts
- packages/web-koa/test/fixtures/base-app-404/src/controller/api.ts
- packages/web-koa/test/fixtures/base-app-error-filter/package.json
- packages/web-koa/test/fixtures/base-app-error-filter/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-error-filter/src/configuration.ts
- packages/web-koa/test/fixtures/base-app-error-filter/src/controller/api.ts
- packages/web-koa/test/index.test.ts
- packages/web/src/framework/web.ts
- packages/web/test/feature.test.ts
- packages/web/test/fixtures/feature/base-app-404/package.json
- packages/web/test/fixtures/feature/base-app-404/src/config/config.default.ts
- packages/web/test/fixtures/feature/base-app-404/src/configuration.ts
- packages/web/test/fixtures/feature/base-app-404/src/controller/api.ts
- packages/ws/README.md
> feat: 404 error

- packages/core/src/service/decoratorService.ts
- packages/decorator/src/decoratorManager.ts
- packages/decorator/test/annotation/__snapshots__/pipeline.test.ts.snap
- packages/decorator/test/framework/__snapshots__/app.test.ts.snap
- packages/decorator/test/framework/__snapshots__/config.test.ts.snap
- packages/decorator/test/framework/__snapshots__/logger.test.ts.snap
- packages/decorator/test/framework/__snapshots__/plugin.test.ts.snap
- packages/decorator/test/web/__snapshots__/paramMapping.test.ts.snap
- packages/swagger/src/decorators/api-exclude-controller.decorator.ts
- packages/swagger/src/decorators/api-exclude-endpoint.decorator.ts
- packages/swagger/src/decorators/api-header.decorator.ts
- packages/swagger/src/decorators/api-operation.decorator.ts
- packages/swagger/src/decorators/api-response.decorator.ts
- packages/swagger/src/decorators/api-security.decorator.ts
- packages/swagger/src/decorators/helpers.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
> feat: add custom decorator filter

- packages-serverless/serverless-worker-starter/package.json
> chore: remove logger

- packages-serverless/serverless-app/src/configuration.ts
- packages-serverless/serverless-app/src/framework.ts
- packages/core/src/interface.ts
- packages/web-express/src/framework.ts
> fix: serverless app run

- packages/core/src/common/dataListener.ts
- packages/core/src/functional/configuration.ts
- packages/core/src/index.ts
- packages/core/src/service/configService.ts
- packages/core/test/common/dataListener.test.ts
> feat: add data listener

- doc/zh-cn/component/swagger.md
- packages/swagger/src/documentBuilder.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
> feat: compatible with @File/@Files/@Fields

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
> fix: @File/@Files schema no type bug

- docs/v2/zh-cn/koa.md
docs: md table format adjustment
> docs: md table format adjustment

- packages/swagger/src/documentBuilder.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.ctest.ts
- packages/swagger/test/fixtures/cats/src/configuration.ts
- packages/swagger/test/index.test.ts
- site/docs/extensions/swagger.md
> feat: swagger tags support ascii order

- site/src/components/EssentialsComponents.tsx
- site/src/components/Preview.tsx
> chore: site link

- packages/core/test/fixtures/singleton_sample.ts
- packages/processAgent/package.json
- packages/processAgent/src/configuration.ts
- packages/processAgent/src/decorator/primary.ts
- packages/sequelize/package.json
完善
```
@Provide()
@Scope(ScopeEnum.Singleton)
export class TestService {
data: any = 0;
@RunInPrimary()
async setData(b) {
this.data = b;
return this.data;
}
@RunInPrimary()
async getData() {
throw new Error("123")
return this.data;
}
}
```
类似当RunInPrimary里面有throw new Error的情况。
> chore: agent error

- packages/consul/src/configuration.ts
- packages/passport/src/service/passport.ts
> fix: move register to on server ready

- packages/core/src/interface.ts
- packages/core/src/setup.ts
- packages/core/test/setup.test.ts
- packages/core/test/util.ts
- packages/faas/test/util.test.ts
- packages/info/test/index.test.ts
- packages/mock/src/creator.ts
- packages/validate/test/check.test.ts
- packages/view/README.md
- packages/view/index.d.ts
- packages/view/src/config/config.default.ts
- packages/view/src/viewManager.ts
- packages/web-express/test/index.test.ts
- packages/web/src/utils.ts
- packages/web/test/utils.ts
- site/docs/extensions/render.md
- site/docusaurus.config.js
> feat: support multi root

- site/docs/midway_component.md
docs: update enabledEnvironment value
> docs: update enabledEnvironment value

- site/docs/error_filter.md
- [ x ] documentation is changed or added
doc only
typo: InternalServerErrorError
> typo: InternalServerErrorError

- packages/cross-domain/index.d.ts
- packages/express-session/index.d.ts
- packages/info/index.d.ts
- packages/upload/index.d.ts
> fix: config key required

- packages/tablestore/src/interface.ts
> fix: tablestore ref

- packages/i18n/src/i18nService.ts
- packages/i18n/src/interface.ts
- packages/i18n/src/middleware.ts
- packages/i18n/test/index.test.ts
> fix: i18n cookie set

- packages/cos/src/manager.ts
> fix: cos config

- packages/mock/src/creator.ts
- packages/mock/src/utils.ts
- packages/mock/test/fixtures/base-faas-3/f.yml
- packages/mock/test/fixtures/base-faas-3/package.json
- packages/mock/test/fixtures/base-faas-3/src/configuration.ts
- packages/mock/test/fixtures/base-faas-3/src/event.ts
- packages/mock/test/fixtures/base-faas-3/tsconfig.json
- packages/mock/test/new.test.ts
> fix: createFunctionApp

- packages/swagger/src/decorators/api-tags.decorator.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
- packages/swagger/test/index.test.ts
- site/docs/extensions/swagger.md
> fix: swagger not support more than one @Body

- package.json
- packages-serverless/serverless-worker-starter/package.json
- packages/bootstrap/package.json
- packages/core/package.json
- packages/core/test/logger.test.ts
- packages/faas/package.json
- packages/grpc/package.json
- packages/mock/package.json
- packages/mongoose/package.json
- packages/rabbitmq/package.json
- packages/socketio/package.json
- packages/task/package.json
- packages/typegoose/package.json
- packages/web-express/package.json
- packages/web-koa/package.json
- packages/web/package.json
- packages/ws/package.json
related: https://github.com/typegoose/typegoose/pull/669
> chore: fix typegoose install error and upgrade logger to 2.15

- packages/swagger/src/configuration.ts
- packages/swagger/src/documentBuilder.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/configuration.ts
> fix: swagger support globalprefix

- packages/task/index.d.ts
- site/docusaurus.config.js
> fix: task typings

- packages/mock/src/creator.ts
> fix: mock options

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
> fix: swagger query/param bug

- packages/tablestore/package.json
> fix: add missing dep

- site/docs/controller.md
> doc: import the missing `Post` decorator

- packages/web/src/configuration.ts
处理中间件时校验下变量 ` this.app.middleware`  类型及有效值
> fix(web): check type of variable this.app.middleware

- site/docs/extensions/orm.md
> docs: fix the link of `TypeORM Model Generator`

- site/docs/extensions/orm.md
> doc: fix the link of env config

- site/docs/extensions/orm.md
1. 代码用反引号包裹
2. 统一缩进为 2 个空格
3. 删除未使用的导入
4. 修正 `../entity/Photo.ts` 的导入路径
> doc: unify the coding style of CRUD examples

- packages/task/src/service/queueService.ts
> fix: queue service scope

- packages/passport/src/interface.ts
- packages/passport/test/fixtures/passport-express-jwt/src/test.controller.ts
- packages/passport/test/fixtures/passport-express-session/src/configuration.ts
- packages/passport/test/fixtures/passport-koa-jwt-global/package.json
- packages/passport/test/fixtures/passport-koa-jwt-global/src/config/config.default.ts
- packages/passport/test/fixtures/passport-koa-jwt-global/src/configuration.ts
- packages/passport/test/fixtures/passport-koa-jwt-global/src/jwt.middleware.ts
- packages/passport/test/fixtures/passport-koa-jwt-global/src/jwt.strategy.ts
- packages/passport/test/fixtures/passport-koa-jwt-global/src/test.controller.ts
- packages/passport/test/fixtures/passport-web/src/configuration.ts
- packages/passport/test/fixtures/passport-web/src/local.middleware.ts
- packages/passport/test/index.test.ts
> fix: passport middleware definition

- scripts/benchmark.sh
> fix: benchmark

- packages-serverless/serverless-worker-starter/src/index.ts
export asyncWrapper from runtime-engine for node.js environment.
> fix: export asyncWrapper from runtime-engine

- packages/core/package.json
- packages/core/src/error/framework.ts
- packages/core/src/index.ts
- packages/core/src/util/httpclient.ts
- packages/core/test/paramMapping.test.ts
- packages/core/test/util.ts
- packages/core/test/util/httpclient.test.ts
> refactor: add httpclient util method

- packages/processAgent/src/configuration.ts
- packages/processAgent/src/decorator/primary.ts
- packages/task/src/framework.ts
- packages/task/src/service/queueService.ts
- packages/task/test/fixtures/base-app/src/task/hello.task.ts
- packages/task/test/index.test.ts
> fix: missing getLocalTask method

- packages/core/src/util/index.ts
- packages/redis/src/manager.ts
- packages/redis/test/index.test.ts
> fix: redis on method missing

- packages/web/app/extend/context.js
- packages/web/src/interface.ts
- packages/web/test/fixtures/issue/base-app-setAttr/package.json
- packages/web/test/fixtures/issue/base-app-setAttr/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-setAttr/src/config/config.unittest.ts
- packages/web/test/fixtures/issue/base-app-setAttr/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-setAttr/src/controller/User.ts
- packages/web/test/issue.test.ts
> fix: egg missing setAttr and getAttr

- packages/web-express/src/interface.ts
- site/docs/extensions/egg.md
- site/docs/extensions/express.md
- site/docs/extensions/koa.md
> fix: missing express cookie parser typings

- packages/core/src/common/fileDetector.ts
- packages/core/src/context/container.ts
- packages/core/src/interface.ts
- packages/core/test/feature.test.ts
- packages/core/test/fixtures/app-with-configuration-detector/package.json
- packages/core/test/fixtures/app-with-configuration-detector/src/b.ts
- packages/core/test/fixtures/app-with-configuration-detector/src/configuration.ts
- packages/core/test/fixtures/app-with-configuration-detector/src/testing/a.ts
- packages/core/test/fixtures/app-with-functional-component/src/components/hooks/src/index.ts
- packages/decorator/src/decorator/common/configuration.ts
- packages/decorator/test/annotation/configuration.test.ts
> fix: remove configuration resolve handler and add detectorOptions

- packages/core/src/service/loggerService.ts
> fix: none level

- packages-serverless/serverless-worker-starter/src/runtime.ts
remove winston logger compatibility code
> fix: remove winston logger compatibility code

- packages/passport/README.md
- site/docs/extensions/passport.md
> doc: fix typo

- packages/rabbitmq/src/configuration.ts
- packages/rabbitmq/src/framework.ts
- packages/rabbitmq/src/interface.ts
- packages/rabbitmq/test/fixtures/base-app-direct/src/configuration.ts
- packages/rabbitmq/test/fixtures/base-app-fanout/src/configuration.ts
- packages/rabbitmq/test/fixtures/base-app-not-exist-channel/src/configuration.ts
- packages/rabbitmq/test/fixtures/base-app/src/configuration.ts
> fix: rabbitmq config key

- packages/core/src/util/index.ts
- packages/core/test/util/util.test.ts
> fix: not transform when RouteParam got undefined

- README.en-US.md
- README.md
> docs: Readme typo

- packages/core/src/baseFramework.ts
- packages/web-express/src/framework.ts
- packages/web-express/src/interface.ts
- packages/web-express/test/fixtures/base-app-router-path-middleware/package.json
- packages/web-express/test/fixtures/base-app-router-path-middleware/src/config/config.default.ts
- packages/web-express/test/fixtures/base-app-router-path-middleware/src/configuration.ts
- packages/web-express/test/index.test.ts
> fix: express use router and middleware

- packages-serverless/serverless-worker-starter/src/http-request.ts
- packages-serverless/serverless-worker-starter/src/runtime.ts
- packages-serverless/serverless-worker-starter/test/helper/request_response.ts
- packages-serverless/serverless-worker-starter/test/node-worker.test.ts
- packages-serverless/serverless-worker-starter/test/service-worker.test.ts
https://github.com/midwayjs/midway/pull/1768
增加测试用例
> feat: support event for worker starter

- packages/core/src/config/config.default.ts
- packages/core/src/service/loggerService.ts
- packages/info/test/__snapshots__/index.test.ts.snap
- packages/web/app.js
- packages/web/src/base.ts
- packages/web/src/logger.ts
> fix: default error dir and loadMidwayController

- packages/core/src/service/frameworkService.ts
- packages/core/src/setup.ts
- packages/web/src/configuration.ts
- packages/web/src/framework/lifecycle.ts
> fix: preload module position

- site/docs/container.md
> docs: fix container.md

- site/docs/extensions/cos.md
> docs: fix typo of COSService

- site/docs/extensions/socketio.md
import * as socketio from '@midwayjs/socket.io';
-修改两处错误代码->
import * as socketio from '@midwayjs/socketio';
> doc: update socketio.md

- packages/swagger/src/swaggerMiddleware.ts
> fix: remove swagger validator url

- packages/web/src/utils.ts
- packages/web/test/fixtures/cluster/base-app/src/agent.ts
- packages/web/test/fixtures/cluster/base-app/src/sdk.service.ts
- packages/web/test/fixtures/issue/base-app-agent-config/package.json
- packages/web/test/fixtures/issue/base-app-agent-config/src/agent.ts
- packages/web/test/fixtures/issue/base-app-agent-config/src/config/config.default.ts
- packages/web/test/fixtures/issue/base-app-agent-config/src/config/config.unittest.ts
- packages/web/test/fixtures/issue/base-app-agent-config/src/configuration.ts
- packages/web/test/fixtures/issue/base-app-agent-config/src/controller/api.ts
- packages/web/test/fixtures/issue/base-app-agent-config/src/sdk.service.ts
- packages/web/test/issue.test.ts
> fix: agent load config

- packages/core/src/context/container.ts
- packages/core/src/setup.ts
- packages/mock/src/creator.ts
- packages/otel/README.md
- packages/otel/index.d.ts
- packages/otel/jest.config.js
- packages/otel/jest.setup.js
- packages/otel/package.json
- packages/otel/src/configuration.ts
- packages/otel/src/decorator/tracer.decorator.ts
- packages/otel/src/index.ts
- packages/otel/src/service.ts
- packages/otel/test/fixtures/base-app/package.json
- packages/otel/test/fixtures/base-app/src/configuration.ts
- packages/otel/test/fixtures/base-app/src/user.service.ts
- packages/otel/test/index.test.ts
- packages/otel/tsconfig.json
> feat: add otel component

- packages/core/src/setup.ts
> fix: add a inject for @inject logger in singleton scope

- packages/web/src/interface.ts
> fix: EggAppConfig with PowerPartial

- packages/web/src/utils.ts
> fix: invoke method after agent overwrite method

- site/docs/logger.md
> docs: fix a spelling mistake in logger.md

- site/docs/how_to_install_nodejs.md
https://zhuanlan.zhihu.com/p/430580607
> docs: change npm mirror registry endpoint

- site/versioned_docs/version-2.0.0/extensions/cos.md
2.14.6 midway的cos组件config同步cos config，文档未更新
> doc: update cos.md

- packages/core/src/common/serviceFactory.ts
- packages/core/src/util/index.ts
- packages/core/test/common/serviceFactory.test.ts
- packages/orm/index.d.ts
- packages/orm/package.json
- packages/orm/src/configuration.ts
- packages/orm/src/hook.ts
- packages/orm/src/interface.ts
- packages/orm/test/fixtures/base-fn-multiple-db/src/configuration.ts
- packages/orm/test/fixtures/base-fn-multiple-db/src/hook.ts
> chore: add has method for service factory

- packages/midway-schedule/agent.ts
- packages/midway-schedule/app.ts
- packages/orm/src/configuration.ts
- packages/orm/src/hook.ts
- packages/orm/src/interface.ts
- packages/orm/test/fixtures/base-fn-multiple-db/src/configuration.ts
- packages/orm/test/fixtures/base-fn-multiple-db/src/hook.ts
- packages/orm/test/fixtures/base-fn/src/configuration.ts
- packages/orm/test/fixtures/base-fn/src/hook.ts
- packages/orm/test/index.test.ts
> fix: find uuid for v3

- packages/otel/test/index.test.ts
> fix: otel test

- packages-serverless/faas-typings/package.json
- packages-serverless/serverless-http-parser/package.json
- packages/session/package.json
- packages/web-koa/package.json
> chore: update cookie version

- packages/core/src/interface.ts
- packages/core/src/setup.ts
- packages/core/src/util/httpclient.ts
- packages/core/test/util/httpclient.test.ts
- packages/upload/src/middleware.ts
- packages/web/src/cluster.ts
> fix: throw error when cluster exec

- packages/swagger/src/decorators/helpers.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
- packages/swagger/test/index.test.ts
> fix: swagger getSchemaPath bug

- packages/info/package.json
> fix: typings missing

- packages/core/src/service/middlewareService.ts
- packages/web-koa/src/interface.ts
> fix: match and ignore method missing this

- packages/core/src/context/managedResolverFactory.ts
- packages/core/src/error/framework.ts
> fix: output error

- packages/core/src/service/middlewareService.ts
> chore(core): include middleware name when exception

- packages/core/src/service/mockService.ts
- packages/core/src/util/contextUtil.ts
- packages/core/test/service/mockService.test.ts
- packages/mock/src/mock.ts
- packages/mock/test/new.test.ts
- site/docs/built_in_service.md
- site/docs/extensions/orm.md
- site/docs/mock.md
- site/docs/req_res_app.md
- site/docs/sidebars.json
- site/docs/upgrade_v3.md
> fix: mock when app not start

- site/docs/quickstart.md
fix typo
- [x ] documentation is changed or added
- 连调：应该为联调
> doc: update quickstart.md

- site/docs/custom_decorator.md
> docs: fix custom decorator doc

- site/docs/sidebars.json
- site/docs/tool/awesome_midway.md
- site/package-lock.json
- [ x] documentation is changed or added
文档添加awesome midway， 鼓励为midway封装组件
> docs: add awesome midway document

- packages/core/src/service/configService.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/service/configService.test.ts
> fix: mapping prod and test config in object mode

- packages/web-koa/src/framework.ts
- packages/web-koa/src/interface.ts
- site/docs/extensions/koa.md
> feat: add koa init options

- site/src/components/EssentialsComponents.tsx
> fix: change mongodb page url

- packages/core/src/index.ts
- packages/core/src/util/index.ts
- packages/core/test/util/util.test.ts
- packages/redis/package.json
- packages/redis/src/manager.ts
> feat: upgrade ioredis to v5

- packages/core/src/service/frameworkService.ts
> refactor: ignore framework when it not imports

- packages/swagger/src/swaggerExplorer.ts
> fix: swagger_extend_bug

- packages/web-koa/index.d.ts
build progress showed lacks of cookies and BodyParserOption definition.
> fix: cookies and BodyParserOptions definition in Koa after #1856

- packages/core/src/baseFramework.ts
- packages/core/src/service/frameworkService.ts
> refactor: add default name for framework

- site/docs/tool/awesome_midway.md
> doc: update awesome_midway.md

- packages/web/app/extend/context.js
> fix: ctx.getLogger does not overwrite success

- site/docs/faq/git_problem.md
增加eslint报错Delete `␍`eslint(prettier/prettier) 的解决方案
> doc: update git_problem.md

- packages/passport/src/util.ts
> fix: is express method got error result

- site/docs/extensions/redis.md
> docs: fix redis ex args for definition

- packages/core/src/service/frameworkService.ts
> fix: register app before framework init

- packages/decorator/src/decorator/framework/index.ts
> fix: typings for app decorator

- packages-serverless/faas-typings/typings/common.ts
- packages-serverless/serverless-http-parser/src/context.ts
> fix: add original url proxy from url

- packages/core/src/error/framework.ts
- packages/core/src/service/configService.ts
- packages/core/test/service/configService.test.ts
- packages/core/test/service/fixtures/invalid_case/config.default.ts
> fix: throw error if config is invalid

- .github/workflows/nodejs.yml
> ci: ignore duplicate action

- packages/cos/src/manager.ts
- packages/cos/test/fixtures/base-app-single-client/src/config.default.ts
- packages/oss/src/interface.ts
- packages/oss/src/manager.ts
- site/docs/extensions/oss.md
> fix: oss cluster typings

- packages/oss/src/index.ts
- packages/oss/src/interface.ts
- packages/oss/src/manager.ts
> fix: oss cluster compatible

- site/docs/extensions/passport.md
> docs:fix JwtStrategy error path in extensions/passport

- site/docs/extensions/sequelize.md
> 修复关于sequelize介绍文档中示例代码引用错误，添加关于连表查询案例和示例仓库

- site/docs/tool/awesome_midway.md
> doc: add community example

- site/docs/tool/awesome_midway.md
一个包含 请求日志链路，统一响应体，统一异常处理，异常过滤器 + 三大主流 ORM 模型 (sequelize，typeORM，prisma)  的示例 ): 📃
> docs: update awesome_midway.md with midway-practice

- packages/session/src/interface.ts
> fix: session maxAge definition

- packages/web-express/index.d.ts
- packages/web-koa/index.d.ts
- packages/web/index.d.ts
- packages/web/src/interface.ts
> fix: egg missing session definition

- packages/http-proxy/src/middleware.ts
- packages/http-proxy/test/express.test.ts
- packages/http-proxy/test/faas.test.ts
- packages/http-proxy/test/fixtures/express/src/configuration.ts
- packages/http-proxy/test/fixtures/faas/src/configuration.ts
- packages/http-proxy/test/fixtures/koa/src/configuration.ts
- packages/http-proxy/test/fixtures/web/src/config/config.default.ts
- packages/http-proxy/test/koa.test.ts
- packages/http-proxy/test/web.test.ts
> fix: koa pipe

- site/docs/lifecycle.md
只对文档做了修改
container 前不加 await 会有类型错误
添加后：
> docs(lifecycle.md): fix demo type error

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
- packages/swagger/test/fixtures/cats/src/dto/create-cat.dto.ts
- packages/swagger/test/fixtures/cats/src/entities/cat.entity.ts
- packages/swagger/test/index.test.ts
> fix: compatible date type

- site/docs/serverless/serverless_yml.md
None.
修复了当前文档的 [f.yml 定义](https://midwayjs.org/docs/serverless/serverless_yml#%E5%AD%97%E6%AE%B5%E6%8F%8F%E8%BF%B0-1) 一章存在的结构紊乱问题。
- `Provider - 字段描述` 和 `events - 字段描述`
- 意外包裹在 info 里的文档
> docs: fix serverless_yml

- site/docs/data_listener.md
> docs:  fix data_listener error demo code

- site/docs/extensions/sequelize.md
- [ x] `npm test` passes
- [ x] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [x ] commit message follows commit guidelines
ref:[docs:typo sequlize](https://github.com/midwayjs/midway/issues/1997)
> docs: Update sequelize.md

- site/docs/testing.md
> docs: add alias paths support for mocha

- packages/i18n/src/interface.ts
- packages/i18n/src/middleware.ts
- packages/i18n/test/fixtures/base-app-express-close-resolver/package.json
- packages/i18n/test/fixtures/base-app-express-close-resolver/src/configuration.ts
- packages/i18n/test/fixtures/base-app-express-close-resolver/src/user.ts
- packages/i18n/test/fixtures/base-app-koa-close-resolver/package.json
- packages/i18n/test/fixtures/base-app-koa-close-resolver/src/configuration.ts
- packages/i18n/test/fixtures/base-app-koa-close-resolver/src/user.ts
- packages/i18n/test/index.test.ts
- packages/task/src/service/queueService.ts
> fix: i18 resolver and task typing

- packages/grpc/src/interface.ts
- packages/grpc/src/provider/framework.ts
> feat: add grpc server options

- packages/task/src/framework.ts
- packages/task/test/fixtures/base-app-duplicate-local-task/package.json
- packages/task/test/fixtures/base-app-duplicate-local-task/src/config/config.default.ts
- packages/task/test/fixtures/base-app-duplicate-local-task/src/configuration.ts
- packages/task/test/fixtures/base-app-duplicate-local-task/src/task/another.task.ts
- packages/task/test/fixtures/base-app-duplicate-local-task/src/task/hello.task.ts
- packages/task/test/fixtures/base-app-duplicate-task/package.json
- packages/task/test/fixtures/base-app-duplicate-task/src/config/config.default.ts
- packages/task/test/fixtures/base-app-duplicate-task/src/configuration.ts
- packages/task/test/fixtures/base-app-duplicate-task/src/task/another.task.ts
- packages/task/test/fixtures/base-app-duplicate-task/src/task/hello.task.ts
- packages/task/test/index.test.ts
> fix: add duplicate check for task

- packages/cache/index.d.ts
> fix: cache typings

- site/docs/extensions/redis.md
> docs: update redis.md

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/fixtures/cats/src/cats.controller.ts
- packages/swagger/test/fixtures/cats/src/entities/test.ts
- packages/swagger/test/index.test.ts
> fix: swagger items assign bug

- site/docs/tool/awesome_midway.md
> docs: update awesome_midway.md

- packages/task/src/framework.ts
> fix: throw error when task run fail and add task to fail queue

- packages/upload/README.md
- packages/upload/src/config/config.default.ts
- packages/upload/src/interface.ts
- packages/upload/src/middleware.ts
- packages/upload/src/parse.ts
- site/docs/extensions/upload.md
> fix: upload base64

- packages/web-koa/src/utils.ts
- packages/web-koa/test/fixtures/base-app-json-error/package.json
- packages/web-koa/test/fixtures/base-app-json-error/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-json-error/src/configuration.ts
- packages/web-koa/test/index.test.ts
- site/docs/custom_decorator.md
> fix: accepts method this missing

- site/docs/extensions/jwt.md
- site/docs/tool/awesome_midway.md
> docs(完善部分说明): 社区微服务中添加es组件,完善jwt使用说明，添加过滤匹配

- packages/sequelize/test/index.test.ts
- packages/sequelize/test/legacy.test.ts
> test: fix sequelize typings in unittest🧪

- site/docs/custom_decorator.md
> docs: fix createCustomPropertyDecorator and format 📃

- packages/axios/src/configuration.ts
- packages/axios/src/serviceManager.ts
- packages/axios/test/factory.test.ts
- packages/axios/test/index.test.ts
> fix: axios use factory to replace request scope

- packages/core/src/common/filterManager.ts
- packages/core/test/common/filterManager.test.ts
- packages/decorator/src/decorator/common/filter.ts
- packages/decorator/test/annotation/__snapshots__/filter.test.ts.snap
- packages/decorator/test/annotation/__snapshots__/framework.test.ts.snap
- packages/decorator/test/annotation/__snapshots__/middleware.test.ts.snap
- packages/decorator/test/annotation/__snapshots__/task.test.ts.snap
- packages/decorator/test/annotation/filter.test.ts
- packages/decorator/test/annotation/framework.test.ts
- packages/decorator/test/annotation/middleware.test.ts
- packages/decorator/test/annotation/pipeline.test.ts
- packages/decorator/test/annotation/task.test.ts
> feat: support match error with prototype

- packages/core/src/service/frameworkService.ts
- packages/core/test/fixtures/base-app-function/src/lib/service.ts
> fix: plugin inject with property name

- packages/redis/src/manager.ts
- packages/redis/test/index.test.ts
> fix: custom command defination

- packages/core/src/error/framework.ts
- packages/core/src/service/webRouterService.ts
- packages/core/test/fixtures/app-with-duplicate-controller-options/package.json
- packages/core/test/fixtures/app-with-duplicate-controller-options/src/config/config.default.ts
- packages/core/test/fixtures/app-with-duplicate-controller-options/src/config/config.prod.ts
- packages/core/test/fixtures/app-with-duplicate-controller-options/src/configuration.ts
- packages/core/test/fixtures/app-with-duplicate-controller-options/src/function/hello_aliyun.ts
- packages/core/test/fixtures/app-with-duplicate-controller-options/src/function/hello_tencent.ts
- packages/core/test/service/webRouterService.test.ts
> feat: add duplicate controller prefix check

- packages/core/src/interface.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
> refactor: use isAnyArrayBuffer instead isBuffer

- packages/static-file/src/configuration.ts
> fix: return buffer in serverless environment

- packages/task/src/configuration.ts
> fix: replace onReady to onServerReady

- packages/web/src/logger.ts
> fix: egg default custom logger level

- packages/core/src/service/middlewareService.ts
- packages/socketio/test/fixtures/base-app-middleware/src/socket/home.ts
> fix: ignore middleware when return undefined in resolve function

- packages/faas/src/framework.ts
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
> fix: faas close server

- site/docs/extensions/grpc.md
fix(docs): greeterService must be helloworld.GreeterClient类型
> docs: grpc client typings

- site/docs/awesome_midway.md
添加社区实例midway-boot https://github.com/bestaone/midway-boot
> docs: add midway-boot to  awesome_midway

- packages/core/src/baseFramework.ts
- packages/core/src/interface.ts
- packages/core/src/util/contextUtil.ts
- packages/core/test/baseFramework.test.ts
> feat: add get current context manager global method

- packages/rabbitmq/src/mq.ts
> fix: throw error when rabbitmq connect fail

- packages/core/src/common/fileDetector.ts
- packages/core/src/context/container.ts
- packages/core/src/service/webRouterService.ts
- packages/core/test/fixtures/app-with-conflict/base-app-decorator/src/configuration.ts
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/package.json
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/src/config/config.default.ts
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/src/config/config.prod.ts
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/src/configuration.ts
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/src/function/hello_aliyun.ts
- packages/core/test/fixtures/app-with-duplicate-controller-not-throw/src/function/hello_tencent.ts
- packages/core/test/service/webRouterService.test.ts
- packages/decorator/src/decorator/common/configuration.ts
- packages/web/test/fixtures/enhance/base-app-controller-conflicts/src/configuration.ts
> fix: class name and controller prefix conflict

- site/docs/extensions/upload.md
配置示例标题中，join 尚未明确怎么来，加上 import { join } from 'path'; 进行完善
> docs: Update upload.md

- packages/core/src/common/filterManager.ts
- packages/sequelize/index.d.ts
- packages/sequelize/test/fixtures/sequelize-new/src/service/user.ts
- site/docs/extensions/sequelize.md
> fix: sequelize typings and filter empty metadata

- packages/mock/src/index.ts
> fix: add createBootstrap export

- site/docs/awesome_midway.md
> docs: update awesome_midway.md with midway-vue3-ssr

- packages-legacy/orm/package.json
- packages-legacy/runtime-engine/package.json
- packages-legacy/runtime-mock/package.json
- packages-legacy/serverless-app/package.json
- packages-legacy/serverless-aws-starter/package.json
- packages-legacy/serverless-fc-starter/package.json
- packages-legacy/serverless-fc-trigger/package.json
- packages-legacy/serverless-scf-starter/package.json
- packages-legacy/serverless-scf-trigger/package.json
- packages-legacy/serverless-vercel-starter/package.json
- packages-legacy/serverless-vercel-trigger/package.json
- packages/core/src/context/container.ts
- packages/core/src/service/configService.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/base-app-config-filter/package.json
- packages/core/test/fixtures/base-app-config-filter/src/config/config.default.ts
- packages/core/test/fixtures/base-app-config-filter/src/config/config.unittest.ts
- packages/core/test/fixtures/base-app-config-filter/src/configuration.ts
- packages/core/test/service/configService.test.ts
- packages/decorator/src/decorator/common/configuration.ts
- packages/mock/src/creator.ts
- packages/mongoose/src/configuration.ts
- packages/sequelize/src/configuration.ts
- packages/sequelize/src/dataSourceManager.ts
- packages/typegoose/index.d.ts
- packages/typegoose/package.json
> fix: add config filter and modify sequelize & mongoose config

- packages/passport/src/passport/passport.service.ts
> fix: some passport strategy verify callback arguments length

- packages/rabbitmq/src/framework.ts
- packages/rabbitmq/src/mq.ts
- site/docs/extensions/sequelize.md
> fix: rabbit mq disconnect

- packages/validate/src/service.ts
> fix: add getSchema method for validate

- site/docs/data_source.md
> docs(site): update data_source.md

- packages/task/src/framework.ts
> fix(task): createClient config missing

- packages/core/src/service/slsFunctionService.ts
> fix: sls metadata npe

- packages/core/src/common/dataSourceManager.ts
> fix: unexpected token 'export' in load **.d.ts file in prod mode

- packages/core/src/common/dataSourceManager.ts
- packages/core/src/common/fileDetector.ts
- packages/core/src/interface.ts
> refactor: add more pattern

- packages/core/src/common/middlewareManager.ts
- packages/web-express/src/config/config.default.ts
- packages/web-express/src/configuration.ts
- packages/web-express/src/middlewareService.ts
- packages/web-express/test/fixtures/base-app-disable/package.json
- packages/web-express/test/fixtures/base-app-disable/src/config/config.default.ts
- packages/web-express/test/fixtures/base-app-disable/src/config/config.unittest.ts
- packages/web-express/test/fixtures/base-app-disable/src/configuration.ts
- packages/web-express/test/fixtures/base-app-disable/src/controller/api.ts
- packages/web-express/test/fixtures/base-app-disable/src/service/user.ts
- packages/web-express/test/index.test.ts
> fix: middleware disable in express

- site/docs/hooks/deploy.md
> docs: update deploy.md

- packages/typeorm/index.d.ts
> fix: typeorm config typings key

- packages/mikro/src/configuration.ts
> fix: support mikro-orm multi entities manager in request context

- packages/core/test/util/extend.test.ts
> test: add extend null case

- packages/core/src/common/fileDetector.ts
- packages/core/src/error/base.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/common/detector.test.ts
- packages/core/test/common/glob_dir/a.ts
- packages/core/test/common/glob_dir/b.d.ts
- packages/core/test/common/glob_dir/c.js
- packages/core/test/common/glob_dir_conflict/a.ts
- packages/core/test/common/glob_dir_conflict/c.ts
- packages/core/test/common/webGenerator.test.ts
- packages/core/test/functional/configuration.test.ts
- packages/passport/src/passport/request.ts
- packages/web-express/test/index.test.ts
- packages/web-koa/test/fixtures/base-app-query-parser/package.json
- packages/web-koa/test/fixtures/base-app-query-parser/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-query-parser/src/config/config.unittest.ts
- packages/web-koa/test/fixtures/base-app-query-parser/src/configuration.ts
- packages/web-koa/test/fixtures/base-app-query-parser/src/controller/home.ts
- packages/web-koa/test/index.test.ts
- packages/web/app/extend/request.js
- packages/web/src/config/config.default.ts
- packages/web/src/interface.ts
- packages/web/test/feature.test.ts
- packages/web/test/fixtures/feature/base-app-query-parser/package.json
- packages/web/test/fixtures/feature/base-app-query-parser/src/config/config.default.ts
- packages/web/test/fixtures/feature/base-app-query-parser/src/config/config.unittest.ts
- packages/web/test/fixtures/feature/base-app-query-parser/src/configuration.ts
- packages/web/test/fixtures/feature/base-app-query-parser/src/controller/home.ts
> fix: query parser with array

- site/docs/extensions/cos.md
Fix description error
cos写成了redis
> docs: cos.md

- packages/core/src/baseFramework.ts
> fix: middleware repeat execute in request

- packages/core/src/common/dataSourceManager.ts
如果获取的 data source 实例空，直接返回 false
> chore(core): return false if data source undefined within isConnected()

- site/docs/awesome_midway.md
> docs: fix repo typo error

- packages/mikro/package.json
- packages/mikro/test/index.test.ts
> fix: revert node 14 supported

- packages/bootstrap/src/bootstrap.ts
> fix: stop duplicate invoke

- packages/core/src/common/dataSourceManager.ts
> chore(core): clear code of DataSourceManager.initDataSource()

- packages/kafka/src/framework.ts
- packages/kafka/src/kafka.ts
> fix: catch kafaka start error

- site/docs/awesome_midway.md
> docs: add apollo

- site/docs/extensions/redis.md
> docs: remove unnecessary await

- site/docs/hooks/deploy.md
> docs: fix heading level problem

- packages/grpc/src/interface.ts
- packages/grpc/src/provider/framework.ts
> fix: grpc context typings

- packages/core/src/service/configService.ts
- packages/core/test/service/configService.test.ts
- packages/passport/src/passport/passport.service.ts
- scripts/benchmark.sh
> fix: passport strategy this missing

- site/docs/awesome_midway.md
> docs: add learning boilerplate

- site/docs/extensions/passport.md
Some code needs to be implemented and fixed in passport-github document.
> docs: passport combine passport-github document

- packages-serverless/serverless-http-parser/package.json
> chore: fix parseurl & type-is

- packages/core/src/error/framework.ts
- packages/core/src/index.ts
- packages/core/src/util/retry.ts
- packages/core/test/util/retry.test.ts
- packages/http-proxy/test/express.test.ts
- packages/http-proxy/test/faas.test.ts
- packages/http-proxy/test/koa.test.ts
- packages/http-proxy/test/web.test.ts
> feat: add retry wrapper for invoke some remote data

- packages-serverless/faas-typings/typings/common.ts
- packages/oss/index.d.ts
> fix: oss config typings

- scripts/benchmark.js
- scripts/benchmark.sh
- 优化 benchmark 输出显示
- 等待时长从 10s 增到到 15s，减少偶发的内存泄露误判
> chore(ci): update benchmark scripts

- site/docs/extensions/orm.md
> docs: update orm.md

- site/docs/extensions/axios.md
> docs(site): update axios.md

- site/docs/extensions/cross_domain.md
- site/docs/serverless/aliyun_faas.md
- site/docs/tool/cli.md
- site/versioned_docs/version-2.0.0/serverless/aliyun_trigger_http.md
> docs: cross domain

- packages/core/src/util/retry.ts
- packages/core/test/util/retry.test.ts
> feat: support receiver to bind this

- packages/core/src/common/dataSourceManager.ts
- packages/core/test/common/dataSourceManager.test.ts
- packages/core/test/common/glob_dir_pattern/abc/a.ts
- packages/core/test/common/glob_dir_pattern/abc/bcd/d.ts
- packages/core/test/common/glob_dir_pattern/b.d.ts
- packages/core/test/common/glob_dir_pattern/c.js
> fix: glob with pattern

- .github/workflows/nodejs.yml
- packages-legacy/orm/package.json
- packages/cos/package.json
- packages/grpc/package.json
- packages/kafka/package.json
- packages/mikro/package.json
- packages/mock/package.json
- packages/mongoose/package.json
- packages/oss/package.json
- packages/sequelize/package.json
- packages/socketio/package.json
- packages/swagger/package.json
- packages/tablestore/package.json
- packages/typegoose/package.json
- packages/typeorm/package.json
> chore: upgrade dep

- site/docs/extensions/otel.md
> docs(site): update otel example

- site/docs/error_filter.md
- site/docs/extensions/otel.md
> docs(site): update otel.md for development entry example

- packages-serverless/serverless-http-parser/package.json
- packages-serverless/serverless-http-parser/src/application.ts
- packages-serverless/serverless-http-parser/test/index.test.ts
- packages/i18n/src/middleware.ts
> fix: ctx.locals missing in faas

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/index.test.ts.snap
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
> fix: example missing in swagger

- site/docs/serverless/serverless_dev.md
> docs: update serverless_dev md

- site/docs/extensions/http-proxy.md
> docs: http-proxy config add proxyTimeout

- packages/view/src/contextView.ts
- packages/view/test/index.test.ts
> fix(view): fix setLocals

- packages-serverless/serverless-http-parser/src/http/req.ts
> fix: path parameters set

- site/docs/extensions/orm.md
> docs: update typeORM doc

- packages/security/README.md
- site/docs/extensions/security.md
> docs: optimise security csrf

- site/docs/decorator_index.md
> docs: update Files describe

- packages/swagger/src/swaggerExplorer.ts
- site/docs/extensions/swagger.md
优先从 `@ApiOperation` 读取参数，如果不存在定义尝试从 `@Get`,`@Post` 等路由注解信息上读取。
> fix(swagger): compatible with route annotation parameters

- packages/grpc/src/comsumer/clients.ts
> chore: make create client dynamic

- site/docs/extensions/sequelize.md
- site/docs/sidebars.json
- site/docs/tool/sequelize_generator.md
>  docs: add sequelize entity generator

- site/docs/extensions/mongodb.md
> docs(site): fix mongodb.md

- site/docs/custom_decorator.md
> docs(site): normalize statement 

- site/docs/custom_decorator.md
> docs(site): fix example code

- site/docs/deployment.md
> docs(site): normalize statement

- packages/prometheus/README.md
- packages/prometheus/package.json
- packages/prometheus/src/service/dataService.ts
> feat: support user to observe histogram value

- site/docs/deployment.md
> docs(stie): add additional references

- packages/web-koa/src/config/config.default.ts
- packages/web-koa/src/framework.ts
- packages/web-koa/src/interface.ts
- packages/web-koa/test/fixtures/base-app-server-timeout/package.json
- packages/web-koa/test/fixtures/base-app-server-timeout/src/config/config.default.ts
- packages/web-koa/test/fixtures/base-app-server-timeout/src/configuration.ts
- packages/web-koa/test/fixtures/base-app-server-timeout/src/controller/home.ts
- packages/web-koa/test/index.test.ts
> feat: add server timeout config

- packages-serverless/midway-fc-starter/package.json
- packages-serverless/midway-fc-starter/src/index.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/test/new.test.ts
- packages/mock/src/creator.ts
> perf: update triggerFunction args

- site/docs/extensions/passport.md
> docs: passport update

- packages/mock/src/creator.ts
> fix: init context missing when dev test

- packages/core/src/common/dataSourceManager.ts
- packages/core/src/interface.ts
- packages/core/test/common/dataSourceManager.test.ts
- packages/mikro/src/configuration.ts
- packages/sequelize/src/configuration.ts
- packages/typeorm/src/configuration.ts
> feat: support default data source name

- packages/upload/src/middleware.ts
- packages/upload/test/fixtures/koa-ext-null/src/configuration.ts
- packages/upload/test/koa.test.ts
> fix: upload whitelist set null

- site/docs/tool/cli.md
> docs(site): update cli.md

- site/docs/quick_guide.md
修改第510行的错别字beforeAlll为beforeAll
> docs: update quick_guide.md

- site/docs/extensions/orm.md
> docs(site): fix orm.md

- packages/sequelize/src/dataSourceManager.ts
- packages/sequelize/src/interface.ts
- site/docs/extensions/sequelize.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/sequelize.md
> fix: add config sync options

- packages/sequelize/package.json
> fix: remove dependencies and avoid multi-instance in npm

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
> fix: type property replace ts type

- site/docs/extensions/prometheus.md
> docs: Add grafana to docker-compose.yml

- .github/workflows/benchmark.yml
- packages-serverless/midway-fc-starter/src/index.ts
- packages-serverless/midway-fc-starter/src/mock.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/test/fixtures/base-app-event-middleware/src/func.ts
- packages/faas/test/new.test.ts
- packages/mock/src/creator.ts
- packages/mock/src/mock.ts
- scripts/benchmark/benchmark.mjs
> fix: getServerlessInstance add ctx hook

- packages/cos/package.json
> chore: pin cos version

- packages/typegoose/index.d.ts
> fix: duplicate mongoose import

- package.json
- packages-legacy/orm/package.json
- packages/async-hooks-context-manager/package.json
- packages/bootstrap/package.json
- packages/cache/package.json
- packages/core/package.json
- packages/decorator/package.json
- packages/grpc/package.json
- packages/jwt/package.json
- packages/mikro/package.json
- packages/mock/package.json
- packages/oss/package.json
- packages/rabbitmq/package.json
- packages/redis/package.json
- packages/sequelize/package.json
- packages/socketio/package.json
- packages/typeorm/package.json
- packages/version/package.json
- packages/web-express/package.json
- packages/web-koa/package.json
- packages/web/package.json
- packages/ws/package.json
- renovate.json
> chore: pin dep

- packages/bull/index.d.ts
> chore: add job typings export

- site/docs/awesome_midway.md
> docs(site): add a throttler like @nestjs/throttler to awesome_midway.md

- site/docs/awesome_midway.md
- site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
> docs(site): fix midway-throttler url link in awesome_midway.md

- site/docs/auto_run.md
> docs(site): update auto_run.md

- site/docs/env_config.md
- site/i18n/en/docusaurus-plugin-content-docs/current/env_config.md
> docs: fix remoteConfig in Life Cycle

- packages-serverless/midway-fc-starter/src/index.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/test/new.test.ts
- packages/mock/src/creator.ts
> chore: update faas  method

- packages/bull/package.json
- packages/bull/src/framework.ts
- packages/bull/src/index.ts
- packages/bull/src/interface.ts
- site/docs/extensions/bull.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
> fix: bull exports and typings

- packages/core/src/service/webRouterService.ts
- packages/core/test/fixtures/issue-2319/package.json
- packages/core/test/fixtures/issue-2319/src/configuration.ts
- packages/core/test/service/__snapshots__/webRouterService.test.ts.snap
- packages/core/test/service/webRouterService.test.ts
> fix: remove router cache and fix issue #2319

- packages/core/src/common/dataSourceManager.ts
- packages/core/test/common/dataSourceManager.test.ts
- packages/mikro/src/configuration.ts
- packages/mikro/src/decorator.ts
- packages/mikro/test/fixtures/base-fn-origin/src/config/config.default.ts
- packages/mikro/test/fixtures/base-fn-origin/src/configuration.ts
- packages/sequelize/src/configuration.ts
- packages/sequelize/src/decorator.ts
- packages/sequelize/test/fixtures/sequelize-new/src/config/config.default.ts
- packages/sequelize/test/fixtures/sequelize-new/src/configuration.ts
- packages/typeorm/src/configuration.ts
- packages/typeorm/src/decorator.ts
- packages/typeorm/test/fixtures/base-fn-origin/src/config/config.default.ts
- packages/typeorm/test/fixtures/base-fn-origin/src/configuration.ts
> feat: add injectDataSource for mikro/typeorm/sequelize

- .github/workflows/nodejs.yml
- packages/etcd/README.md
- packages/etcd/index.d.ts
- packages/etcd/jest.config.js
- packages/etcd/jest.setup.js
- packages/etcd/package.json
- packages/etcd/src/config.default.ts
- packages/etcd/src/configuration.ts
- packages/etcd/src/index.ts
- packages/etcd/src/manager.ts
- packages/etcd/test/fixtures/base-app-single-client/package.json
- packages/etcd/test/fixtures/base-app-single-client/src/config.default.ts
- packages/etcd/test/fixtures/base-app-single-client/src/configuration.ts
- packages/etcd/test/index.test.ts
- packages/etcd/tsconfig.json
> feat: add etcd component

- packages/core/src/common/dataSourceManager.ts
> fix: windows entity glob and close #2488

- packages/core/src/util/types.ts
> perf: remove babel isClass check

- packages/etcd/src/manager.ts
> fix: etcd support default instance name

- site/docs/extensions/consul.md
> doc(consul.md): fix port type error

- site/docs/awesome_midway.md
- site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
> docs(site): update awesome_midway.md

- site/docs/serverless/aliyun_faas.md
> docs: update the configuration description of AccessKey

- packages/sequelize/src/index.ts
> fix: sequelize inject data source forgot to export

- packages/swagger/src/configuration.ts
> fix: swagger global prefix without path

- packages/mikro/src/configuration.ts
- packages/sequelize/src/configuration.ts
- packages/typeorm/src/configuration.ts
> fix: data source find sequence

- packages/bull/src/decorator.ts
- packages/bull/src/framework.ts
> fix: add default job options when create queue

- packages/captcha/src/service.ts
- packages/mock/src/creator.ts
> fix: captcha store prefix

- packages-serverless/midway-fc-starter/src/index.ts
- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/test/new.test.ts
- packages/mock/src/creator.ts
> fix: event not format in faas

- packages/core/src/common/dataSourceManager.ts
- packages/core/test/common/dataSourceManager.test.ts
- packages/core/test/common/glob_dir_pattern/c.js
- packages/core/test/common/glob_dir_pattern/e.entity.ts
> fix: glob support more wildcard string

- packages/core/src/service/decoratorService.ts
> perf(core): reuse methodDecoratorHandler

- packages/bootstrap/package.json
- packages/bootstrap/src/bootstrap.ts
- packages/bootstrap/test/fixtures/mix-app/src/configuration.ts
- packages/core/src/common/loggerFactory.ts
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/src/service/loggerService.ts
- packages/core/src/setup.ts
- packages/core/test/util.ts
> feat: support custom logger

- packages/bootstrap/src/manager/base.ts
- packages/bootstrap/src/manager/thread.ts
- packages/bootstrap/test/fixtures/cluster-app/src/configuration.ts
- packages/bootstrap/test/fork/cp.test.ts
- packages/bootstrap/test/fork/thread.test.ts
> chore: add cluster exit binding

- packages/bull/index.d.ts
- packages/bull/src/config/config.default.ts
> fix: merge queue options and job options

- packages/axios/package.json
- packages/axios/test/factory.test.ts
- packages/axios/test/index.test.ts
- packages/typeorm/cli.js
- packages/typeorm/package.json
> feat: support typeorm migrate cli

- packages/typeorm/cli.js
> fix: add ts-node run in migrate

- packages/cross-domain/src/middleware/cors.ts
- packages/cross-domain/src/middleware/jsonp.ts
- packages/http-proxy/src/middleware.ts
- packages/static-file/src/configuration.ts
> fix: static with cors

- packages/bull/src/configuration.ts
- packages/bull/src/framework.ts
- packages/bull/test/fixtures/base-app-redis/src/configuration.ts
> fix: bull read new config after config load

- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
> fix: use lazy function to provide type

- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
- packages/validate/test/check.test.ts
> fix: swagger one of with type

- packages/core/src/baseFramework.ts
- packages/core/src/decorator/common/objectDef.ts
- packages/core/src/interface.ts
- packages/core/src/service/frameworkService.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/decorator/annotation/objectDef.test.ts
- packages/core/test/fixtures/base-app-multi-framework-shared/src/framework.ts
> feat: add @Singleton and get namespace api

- packages/core/src/service/lifeCycleService.ts
- packages/core/test/feature.test.ts
- packages/core/test/fixtures/base-app-configuration-stop-reverse/package.json
- packages/core/test/fixtures/base-app-configuration-stop-reverse/src/a/configuration.ts
- packages/core/test/fixtures/base-app-configuration-stop-reverse/src/b/configuration.ts
- packages/core/test/fixtures/base-app-configuration-stop-reverse/src/configuration.ts
> fix: run stop lifecycle with reverse

- packages/core/src/service/lifeCycleService.ts
> chore: update output for lifecycle output

- packages-serverless/midway-fc-starter/src/index.ts
- packages-serverless/serverless-http-parser/src/request.ts
- packages/core/src/decorator/faas/serverlessTrigger.ts
- packages/core/src/decorator/interface.ts
- packages/core/test/decorator/faas/__snapshots__/fun.test.ts.snap
- packages/core/test/decorator/faas/fun.test.ts
- packages/faas/src/decorator.ts
- packages/faas/src/framework.ts
- packages/faas/src/index.ts
- packages/faas/src/interface.ts
- packages/faas/src/starter.ts
- packages/faas/test/fixtures/base-app-event-decorator/package.json
- packages/faas/test/fixtures/base-app-event-decorator/src/configuration.ts
- packages/faas/test/fixtures/base-app-event-decorator/src/func.ts
- packages/faas/test/fixtures/base-app-event-decorator/src/index.ts
- packages/faas/test/new.test.ts
- packages/faas/test/starter.test.ts
- packages/mock/package.json
- packages/mock/src/creator.ts
- packages/mock/src/utils.ts
> feat: add ssr and custom trigger

- packages/kafka/test/utils.ts
- packages/mock/src/creator.ts
- packages/mock/src/interface.ts
- packages/mock/src/utils.ts
> feat: support app enable ssl in dev mode

- packages/core/src/baseFramework.ts
- packages/core/src/decorator/common/mock.ts
- packages/core/src/decorator/constant.ts
- packages/core/src/decorator/index.ts
- packages/core/src/interface.ts
- packages/core/src/service/lifeCycleService.ts
- packages/core/src/service/mockService.ts
- packages/core/src/setup.ts
- packages/core/test/common/applicationManager.test.ts
- packages/core/test/decorator/common/mock.test.ts
> feat: add simulator

- packages/core/src/service/loggerService.ts
> fix: logger async and egg will be start error with cluster mode

- packages/http-proxy/src/middleware.ts
- packages/http-proxy/test/fixtures/koa/src/configuration.ts
- packages/http-proxy/test/koa.test.ts
- packages/upload/src/interface.ts
> fix: remove content-length when proxy stream

- packages/typeorm/src/dataSourceManager.ts
> fix: create default logger when typeorm logger set undefined

- packages/core/src/decorator/web/paramMapping.ts
- packages/core/src/interface.ts
- packages/core/src/service/decoratorService.ts
- packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
- packages/core/test/decorator/web/paramMapping.test.ts
- packages/mock/src/creator.ts
> fix: missing pipes args in web param

- packages/core/src/decorator/web/paramMapping.ts
- packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
- packages/decorator/test/web/__snapshots__/paramMapping.test.ts.snap
- packages/validate/src/configuration.ts
- packages/validate/src/decorator/valid.ts
- packages/validate/src/pipe.ts
- packages/validate/test/check.test.ts
> fix: web param set wrong pipe position

- packages/cross-domain/src/jsonp.ts
- packages/cross-domain/test/express.test.ts
- packages/cross-domain/test/koa.test.ts
> Revert "fix: repair the impact of JSONP on normal requests(#2692)"

- packages/otel/index.d.ts
- packages/otel/src/configuration.ts
- packages/otel/src/service.ts
- packages/otel/test/fixtures/base-app/src/user.service.ts
- packages/otel/test/index.test.ts
> feat: add ctx.traceId

- packages/typeorm/src/dataSourceManager.ts
> fix: typeorm logging property

- packages/core/src/service/webRouterService.ts
- packages/core/test/service/webRouterService.test.ts
> fix: RouterService match router method all

- README.en-US.md
- README.md
Signed-off-by: frank-zsy <syzhao1988@126.com>
NONE
Add contribution leaderboard badge into README file.
> docs(site): add contribution leaderboard badge into README file.

- site/docs/extensions/validate.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/validate.md
> docs(site): update validate.md

- packages/validate/src/pipe.ts
> fix(validate): export ParsePipe from pipe.ts

- packages/faas/src/framework.ts
- packages/faas/src/interface.ts
- packages/faas/src/starter.ts
- packages/faas/test/fixtures/base-app-response-buffer/package.json
- packages/faas/test/fixtures/base-app-response-buffer/src/configuration.ts
- packages/faas/test/fixtures/base-app-response-buffer/src/func.ts
- packages/faas/test/fixtures/base-app-response-buffer/src/index.ts
- packages/faas/test/new.test.ts
> feat: support buffer response

- packages/cross-domain/index.d.ts
- packages/cross-domain/src/configuration.ts
- packages/cross-domain/src/middleware/jsonp.ts
- packages/cross-domain/test/express.test.ts
- packages/cross-domain/test/fixtures/express/src/configuration.ts
- packages/cross-domain/test/fixtures/koa/src/configuration.ts
- packages/cross-domain/test/koa.test.ts
- packages/validate/src/dtoHelper.ts
- site/docs/extensions/cross_domain.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/cross_domain.md
> fix: add ctx.jsonp for  cross-domain

- packages/mock/src/utils.ts
> fix: node 12 fs promise

- site/docs/custom_error.md
import { HttpStatus } from '@midwayjs/core'; 
---->
import { MidwayError } from '@midwayjs/core';
> doc:custom_error.md fix import

- packages/core/src/util/httpclient.ts
> chore: add generalization type

- packages/core/src/service/slsFunctionService.ts
- packages/faas/src/framework.ts
> fix: func name set

- site/docs/extensions/validate.md
> docs: fix pipe valid

- packages/bull/src/framework.ts
> fix: bull add default job options in decorator will be overriding args

- packages/code-dye/README.md
- packages/code-dye/src/config/config.default.ts
- packages/code-dye/src/configuration.ts
- packages/code-dye/src/interface.ts
- site/docs/extensions/code_dye.md
- site/docs/sidebars.json
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/code_dye.md
> chore: update codedye

- packages/validate/package.json
> fix: joi version for node 12/14

- packages/http-proxy/src/configuration.ts
> fix: wrong proxy namespace

- packages/cross-domain/src/middleware/cors.ts
- packages/cross-domain/test/faas.test.ts
- packages/cross-domain/test/fixtures/faas/src/configuration.ts
- packages/faas/src/framework.ts
> fix: cross domain with options request

- packages/mock/src/creator.ts
> fix: mock buffer base64 response

- packages-serverless/faas-typings/typings/common.ts
- packages-serverless/serverless-http-parser/src/context.ts
- packages-serverless/serverless-http-parser/src/http/res.ts
- packages-serverless/serverless-http-parser/test/index.test.ts
> chore: add context.streaming api for streaming api

- packages-serverless/serverless-http-parser/src/http/res.ts
> fix: set streaming property first

- packages/faas/src/framework.ts
> fix: faas content length

- packages/core/src/util/httpclient.ts
> fix: content-type set by headers options

- packages/web/src/utils.ts
> chore: add MIDWAY_SOURCE_DIR for egg

- packages/web/src/index.ts
> fix: egg missing export decorator

- package.json
- packages/faas/src/starter.ts
- packages/mock/src/creator.ts
- renovate.json
> fix: support worker starter options

- site/docs/extensions/kafka.md
- 修改kafka断开连接文档问题
- connect 返回是void，应该使用disconnect
> docs: update kafka disconnect

- packages/bull/src/decorator.ts
- packages/bull/src/framework.ts
feat: add queueOptions to the @Processor decorator
> feat: add queueOptions to the @Processor decorator

- packages/socketio/src/framework.ts
socketio
修复之前PR #2850 中重复记录的OnWSConnection问题。
> fix: fixed duplicated OnWSConnection

- packages/mock/src/utils.ts
> fix: change for support worker

- packages/casbin-redis-adapter/package.json
- packages/casbin-redis-adapter/test/fixtures/base-app/src/configuration.ts
- packages/casbin-typeorm-adapter/package.json
- packages/casbin-typeorm-adapter/test/fixtures/base-app/src/configuration.ts
- packages/casbin/package.json
> fix(deps): update dependency casbin to v5.26.1 

- site/docs/quickstart.md
> docs(site): update quickstart.md

- packages-legacy/orm/package.json
- packages/casbin-typeorm-adapter/package.json
- packages/casbin-typeorm-adapter/src/adapter.ts
- packages/casbin-typeorm-adapter/src/casbinMongoRule.ts
- packages/typeorm/package.json
> fix: compatible typeorm objectId changes

- packages/mock/src/creator.ts
> fix: createServerlessApp baseDir with undefined

- packages/core/src/util/httpclient.ts
> feat: add more http options

- packages/core/src/decorator/faas/serverlessTrigger.ts
- scripts/generate_version.js
> chore: support serverless function options any

- packages/typeorm/src/configuration.ts
> fix: model get different repository by type

- site/docs/extensions/validate.md
> docs:  fix validate.md  defaultValuePipe  variable name error

- packages/faas/src/starter.ts
- packages/mock/src/creator.ts
- packages/mock/src/interface.ts
- packages/mock/test/fixtures/base-faas-without-yaml/index.js
- packages/mock/test/fixtures/base-faas-without-yaml/package.json
- packages/mock/test/fixtures/base-faas-without-yaml/src/configuration.ts
- packages/mock/test/fixtures/base-faas-without-yaml/src/event.ts
- packages/mock/test/fixtures/base-faas-without-yaml/tsconfig.json
- packages/mock/test/new.test.ts
> feat: support new faas v3 entry

- packages/core/src/common/dataListener.ts
> fix: listener init data typings

- site/docs/extensions/cron.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/cron.md
修改文档【通用/本地任务】中对于【组件日志】默认日志文件的描述。
> docs: change cron logger default fileLogName

- site/docs/quickstart.md
- site/i18n/en/docusaurus-plugin-content-docs/current/quickstart.md
> docs: update quickstart.md

- site/docs/how_to_install_nodejs.md
- site/i18n/en/docusaurus-plugin-content-docs/current/how_to_install_nodejs.md
> docs(site): update how_to_install_nodejs.md

- packages/swagger/src/interfaces/index.ts
- packages/validate/src/dtoHelper.ts
> chore: remove function typings

- package.json
- packages/bull/src/framework.ts
- packages/bull/tsconfig.json
> fix: bull typings in interop mode

- packages/leoric/README.md
- packages/leoric/index.d.ts
- packages/leoric/jest.config.js
- packages/leoric/jest.setup.js
- packages/leoric/package.json
- packages/leoric/src/config/config.default.ts
- packages/leoric/src/configuration.ts
- packages/leoric/src/dataSourceManager.ts
- packages/leoric/src/decorator.ts
- packages/leoric/src/index.ts
- packages/leoric/test/dumpfile.sql
- packages/leoric/test/fixtures/basic/package.json
- packages/leoric/test/fixtures/basic/src/config/config.default.ts
- packages/leoric/test/fixtures/basic/src/configuration.ts
- packages/leoric/test/fixtures/basic/src/model/post.ts
- packages/leoric/test/fixtures/basic/src/model/user.ts
- packages/leoric/test/fixtures/basic/src/service/user.ts
- packages/leoric/test/index.test.ts
- packages/leoric/tsconfig.json
core subsystems not changed
added a component for using ORM library [leoric](https://leoric.js.org/zh) with midway
> feat(deps): support leoric as model layer

- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/index.test.ts.snap
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/index.test.ts
- site/docs/extensions/swagger.md
swagger 组件增加 operationId 生成，并且参考@nest/swagger，增加了`operationIdFactory`用于自定义 operationId
> feat: add swagger operationId

- packages/http-proxy/src/middleware.ts
only affected http-proxy module
fix http-proxy res finish event when readableStream.pipe(res)
> fix(http-proxy): readableStream.pipe(res) and res.on('finish')

- packages/bull/src/config/config.default.ts
- packages/cron/src/configuration.ts
> fix: bull logger typo

- site/docs/extensions/socketio.md
> docs: update socketio.md

- packages/core/src/util/index.ts
> fix: import json not support under node v16

- packages/core/src/util/index.ts
- packages/core/test/util/util.test.ts
> fix: load file missing file prefix under windows

- packages/core/src/setup.ts
- packages/web/src/cluster.ts
> fix: use original method name

- packages/swagger/src/swaggerMiddleware.ts
> fix: swagger revert require

- packages/bootstrap/package.json
- packages/bootstrap/src/manager/base.ts
> fix(deps): update dependency @midwayjs/event-bus to v1.9.4

- packages-serverless/serverless-http-parser/package.json
> fix: remove querystring module

- site/docs/extensions/passport.md
> docs(site): update passport.md

- packages/passport/src/passport/authenticator.ts
- packages/passport/src/passport/passport.service.ts
- site/docs/extensions/passport.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/passport.md
> fix: passport validate resolve is not executed under concurrency

- packages/swagger/src/decorators/api-property.decorator.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/index.test.ts.snap
- packages/swagger/test/fixtures/cats/src/entities/cat.entity.ts
- packages/swagger/test/fixtures/cats/src/entities/utils.ts
- packages/swagger/test/fixtures/cats/tsconfig.json
- packages/swagger/test/index.test.ts
- site/docs/extensions/swagger.md
> fix(swagger): api property should support $ref

- packages/bull/src/framework.ts
- packages/bull/test/fixtures/base-app-error-out-of-job/package.json
- packages/bull/test/fixtures/base-app-error-out-of-job/src/configuration.ts
- packages/bull/test/fixtures/base-app-error-out-of-job/src/task/hello.task.ts
- packages/bull/test/index.test.ts
> fix: catch error when bull framework create service

- site/docs/cookie_session.md
- site/i18n/en/docusaurus-plugin-content-docs/current/cookie_session.md
> docs(session): Supplementary explanation on SameSite = None

- packages/static-file/src/configuration.ts
> fix: static file component namespace

- packages/faas/src/interface.ts
- packages/passport/index.d.ts
- packages/web-koa/index.d.ts
- packages/web-koa/src/interface.ts
- packages/web/index.d.ts
- packages/web/src/interface.ts
- site/docs/extensions/egg.md
- site/docs/extensions/koa.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/koa.md
> fix: context.state property override when context typings merge

- packages/http-proxy/src/config/config.default.ts
- packages/http-proxy/src/configuration.ts
- packages/http-proxy/src/interface.ts
> feat: add enable config for http-proxy

- packages/core/src/config/config.default.ts
- packages/core/src/error/framework.ts
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/src/service/healthService.ts
- packages/core/src/service/lifeCycleService.ts
- packages/core/src/setup.ts
- packages/core/src/util/index.ts
- packages/core/test/feature.test.ts
- packages/core/test/fixtures/app-with-health-check-empty/package.json
- packages/core/test/fixtures/app-with-health-check-empty/src/configuration.ts
- packages/core/test/fixtures/app-with-health-check/package.json
- packages/core/test/fixtures/app-with-health-check/src/configuration.ts
- packages/core/test/util/util.test.ts
- packages/info/test/__snapshots__/index.test.ts.snap
- site/docs/built_in_service.md
- site/i18n/en/docusaurus-plugin-content-docs/current/built_in_service.md
> feat: add build-in healthService

- packages/core/src/service/frameworkService.ts
> fix: sort with imports sequence before framework run

- packages/web/src/logger.ts
> fix: core logger missing file log name

- packages/web/src/config/config.default.ts
> fix: web default config

- packages/bull/src/config/config.default.ts
- packages/cron/src/configuration.ts
- packages/typeorm/src/configuration.ts
- packages/web/src/config/config.default.ts
- packages/web/src/logger.ts
- packages/web/test/feature.test.ts
- packages/web/test/fixtures/feature/base-app-logger-v3/package.json
- packages/web/test/fixtures/feature/base-app-logger-v3/src/config/config.default.ts
- packages/web/test/fixtures/feature/base-app-logger-v3/src/config/config.unittest.ts
- packages/web/test/fixtures/feature/base-app-logger-v3/src/configuration.ts
> fix: remove logger v3 compatible

- site/docs/extensions/validate.md
> docs: update validate.md

- packages/web/src/utils.ts
> fix: wrong agent logger

- packages-serverless/serverless-http-parser/src/request.ts
- packages/mock/src/utils.ts
- packages/mock/test/util.test.ts
> fix: wrong protocol get in local

- packages/core/src/common/serviceFactory.ts
- packages/core/src/interface.ts
- packages/core/test/common/serviceFactory.test.ts
- packages/redis/src/configuration.ts
- packages/redis/src/index.ts
- packages/redis/src/manager.ts
- packages/redis/test/index.test.ts
> feat: support client priority

- packages/core/src/error/framework.ts
- packages/swagger/index.html
- packages/swagger/package.json
- packages/swagger/src/config/config.default.ts
- packages/swagger/src/index.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerMiddleware.ts
- packages/swagger/src/ui.ts
- packages/swagger/src/ui/render.ts
- packages/swagger/test/fixtures/cats/src/configuration.ts
- packages/swagger/test/index.test.ts
> feat: visit swagger json without include ui-dist & support custom ui

- packages/redis/src/manager.ts
- [ √] `npm test` passes
- [ √ ] tests and/or benchmarks are included
- [ √] documentation is changed or added
- [ √] commit message follows commit guidelines
> fix(redis): Check the status of the redis client before closing redis

- packages/upload/src/interface.ts
- packages/upload/src/middleware.ts
- packages/upload/test/check.test.ts
- packages/upload/test/koa.test.ts
related: https://github.com/midwayjs/midway/discussions/3497
> feat: support dynamic function white list

- packages/mikro/package.json
- packages/mikro/src/configuration.ts
- packages/mikro/src/dataSourceManager.ts
- packages/mikro/src/interface.ts
- packages/mikro/test/fixtures/base-fn-origin/sqlite-schema.sql
- packages/mikro/test/fixtures/base-fn-origin/src/config/config.default.ts
- site/docs/extensions/mikro.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/mikro.md
> feat: upgrade mikro to v6

- packages/swagger/src/config/config.default.ts
> fix: swagger-ui-dist require missing

- packages/core/src/service/healthService.ts
- packages/core/src/service/lifeCycleService.ts
> fix: lifecycle inject fail in configuration

- site/docs/extensions/egg.md
> docs: update egg.md

- packages/swagger/src/decorators/api-exclude-controller.decorator.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/src/swaggerMiddleware.ts
- packages/swagger/test/parser.test.ts
- packages/ws/package.json
- site/docs/extensions/swagger.md
- site/docs/extensions/ws.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/swagger.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/ws.md
> feat: custom Ignore swagger endpoint

- site/docs/extensions/http-proxy.md
> docs: update http-proxy.md

- packages/core/src/baseFramework.ts
- packages/core/src/common/loggerFactory.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/fixtures/base-app-custom-framework-logger/package.json
- packages/core/test/fixtures/base-app-custom-framework-logger/src/configuration.ts
- packages/core/test/fixtures/base-app-custom-framework-logger/src/framework.ts
- packages/core/test/util.ts
fix: https://github.com/midwayjs/logger/issues/116
> fix: ctx get logger with custom logger

- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/ui/render.ts
> fix: missing swagger ui render options

- packages/core/src/decorator/web/paramMapping.ts
- packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
> feat: support custom param decorator throw error

- packages/core/src/baseFramework.ts
- packages/core/src/common/serviceFactory.ts
- packages/kafka/src/configuration.ts
- packages/kafka/src/framework.ts
- packages/kafka/src/index.ts
- packages/kafka/src/kafka.ts
- packages/mqtt/README.md
- packages/mqtt/index.d.ts
- packages/mqtt/jest.config.js
- packages/mqtt/jest.setup.js
- packages/mqtt/package.json
- packages/mqtt/src/configuration.ts
- packages/mqtt/src/decorator.ts
- packages/mqtt/src/framework.ts
- packages/mqtt/src/index.ts
- packages/mqtt/src/interface.ts
- packages/mqtt/src/service.ts
- packages/mqtt/test/fixtures/base-app-no-pub-sub/package.json
- packages/mqtt/test/fixtures/base-app-no-pub-sub/src/configuration.ts
- packages/mqtt/test/fixtures/base-app/package.json
- packages/mqtt/test/fixtures/base-app/src/comsumer/userConsumer.ts
- packages/mqtt/test/fixtures/base-app/src/configuration.ts
- packages/mqtt/test/index.test.ts
- packages/mqtt/tsconfig.json
- packages/mqtt/typedoc.json
- packages/rabbitmq/src/configuration.ts
> feat: add mqtt module

- packages/swagger/src/constants.ts
- packages/swagger/src/decorators/api-exclude-endpoint.decorator.ts
- packages/swagger/src/decorators/api-header.decorator.ts
- packages/swagger/src/decorators/api-operation.decorator.ts
- packages/swagger/src/decorators/api-response.decorator.ts
- packages/swagger/src/decorators/api-security.decorator.ts
- packages/swagger/src/decorators/helpers.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
- site/docs/extensions/swagger.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/swagger.md
> feat: add ApiExcludeSecurity decorator

- packages/bull/src/framework.ts
> fix: use bull logger when queue emit error

- site/docs/extensions/bull.md
<https://github.com/OptimalBits/bull/issues/2606>
> docs: bull incompatibility with aliyun redis proxy mode

- site/docs/awesome_midway.md
> docs: pdate awesome_midway.md

- packages/axios/src/index.ts
- packages/axios/src/interface.ts
> chore: use Axios for interface export

- packages/mikro/src/configuration.ts
- packages/mikro/src/index.ts
- packages/mikro/src/mikro.middleware.ts
- packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts
- packages/mikro/test/fixtures/multi-enitymanager/src/mikro-orm.config.ts
对比了nestjs的版本，因为缺少了RequestContext的中间件，所以所有情况下mikro-orm的em都是全局示例。
参考了mikro-orm的文档和nestjs的实现，补充mikro-orm的中间件
> fix(mikro): RequestContext middleware

- packages/bull/src/framework.ts
- packages/bull/test/index.test.ts
> fix: bullLogger with undefined value when emit error

- packages/mikro/src/configuration.ts
- packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts
- packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/controller/m1.controller.ts
- packages/mikro/test/index.test.ts
> fix(mikro): Ensure dataSourceName/contextName used in InjectRepository

- packages/cache-manager/src/configuration.ts
- packages/cache-manager/test/fixtures/cache-decorator/src/service/user.service.ts
- packages/cache-manager/test/index.test.ts
> fix: cache manager cache key overwrite when use custom logic

- packages/faas/src/config.default.ts
> fix: enable console transport in serverless env

- packages/upload/src/interface.ts
- packages/upload/src/middleware.ts
`upload`组件
`src/config/config.default.ts`中支持`whitelist`参数传入函数，动态返回白名单
> fix(upload):parameter "whitelist" supports the function type

- packages/upload/src/interface.ts
- packages/upload/src/middleware.ts
- packages/upload/test/fixtures/koa-function-whitelist/src/configuration.ts
- packages/upload/test/koa.test.ts
> feat: support upload mime type white list using function type

- packages/socketio/src/framework.ts
- packages/socketio/test/fixtures/base-app-namespace-regexp/package.json
- packages/socketio/test/fixtures/base-app-namespace-regexp/src/configuration.ts
- packages/socketio/test/fixtures/base-app-namespace-regexp/src/service/user.ts
- packages/socketio/test/fixtures/base-app-namespace-regexp/src/socket/api.ts
- packages/socketio/test/index.test.ts
> fix: socket with regexp namespace

- packages/web-express/src/framework.ts
- packages/web-express/src/interface.ts
- packages/web-koa/src/framework.ts
- packages/web-koa/src/interface.ts
- packages/web/src/framework/web.ts
- packages/web/src/interface.ts
> feat Support http server opts

- packages/bull-board/src/board.manager.ts
- packages/bull-board/src/board.middleware.ts
- packages/bull-board/src/index.ts
- packages/bull-board/test/index.test.ts
- site/docs/extensions/bull.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
> refactor: add the bullBoardManager class along with documentation

- packages/express-session/README.md
- packages/express-session/src/store.ts
- packages/express-session/test/index.test.ts
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
- packages/web/src/framework/web.ts
> fix: certificate error in web scene

- packages/core/src/service/healthService.ts
- packages/core/test/fixtures/app-with-health-check/src/configuration.ts
> fix: health check missing this resolver

- packages/core/src/service/decoratorService.ts
> feat: add instance args for parameter decorator options

- packages/tenant/src/index.ts
- site/docs/extensions/tenant.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/tenant.md
> fix: export named error for tenant component

- site/docs/extensions/tenant.md
> docs: update tenant.md

- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/tenant.md
> docs: update en version tenant.md

- site/docs/release_schedule.md
- [x ] commit message follows commit guidelines
> docs: update release schedule docs, mark v2 as EOL

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
fix： https://github.com/midwayjs/midway/discussions/3883
> fix(swagger): miss dto required from schema

- packages/cache-manager/src/store.ts
- packages/cache-manager/test/store.test.ts
> fix: get origin value from redis store

- packages/core/test/logger.test.ts
- packages/core/test/util.ts
> fix: main ci

- packages/upload/src/parse.ts
- packages/upload/test/koa.test.ts
> fix: single field when allowFieldsDuplication enabled

- packages/sequelize/src/configuration.ts
- packages/sequelize/src/dataSourceManager.ts
- packages/sequelize/test/index.test.ts
> fix: remove authenticate when create data source

- site/docs/extensions/koa.md
> docs: extensions koa typo

- packages/core/src/interface.ts
- packages/core/src/response/base.ts
- packages/core/src/response/http.ts
- packages/core/src/response/sse.ts
- packages/core/src/response/stream.ts
- packages/core/test/response/base.test.ts
- packages/core/test/response/http.test.ts
> feat: add ctx for the static tpl of response

- packages/swagger/src/config/config.default.ts
- packages/swagger/src/documentBuilder.ts
- packages/swagger/src/interfaces/index.ts
- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
> fix: swagger api tag for router

- packages/swagger/src/swaggerExplorer.ts
- packages/swagger/test/__snapshots__/parser.test.ts.snap
- packages/swagger/test/parser.test.ts
> fix: swagger body array type

- packages/core/src/common/dataSourceManager.ts
- packages/mongoose/src/configuration.ts
- packages/mongoose/test/index.test.ts
> fix: dataSourcePriority missing default value

- packages/core/src/util/httpclient.ts
- packages/core/test/util/httpclient.test.ts
> fix: http client will be override default options

- packages/mock/app.js
- packages/web-express/src/framework.ts
- packages/web-koa/src/framework.ts
- packages/web/src/framework/web.ts
> fix: showcase of ssl with mwtsc

- packages/core/src/service/environmentService.ts
- packages/core/test/service/environmentService.test.ts
- packages/static-file/src/middleware/static.middleware.ts
for #4166
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/midwayjs/midway/pull/4180?shareId=4d8d0260-9159-4bc8-811a-2926e90bf16f).
> fix: static file path handling in pkg environment

- .eslintrc.json
- packages/core/src/common/performanceManager.ts
- packages/core/src/index.ts
- packages/core/src/service/frameworkService.ts
- packages/core/src/service/lifeCycleService.ts
- packages/core/src/setup.ts
- packages/core/test/common/performanceManager.test.ts
- packages/mock/app.js
- packages/mock/function.js
> feat: add performance manager

- packages/core/src/service/mockService.ts
- packages/core/test/service/mockService.test.ts
- packages/mock/src/mock.ts
- site/docs/built_in_service.md
- site/docs/mock.md
- site/i18n/en/docusaurus-plugin-content-docs/current/built_in_service.md
- site/i18n/en/docusaurus-plugin-content-docs/current/mock.md
for https://github.com/midwayjs/midway/discussions/3951
@cyjake
> feat: add grouping for mock data

- packages/captcha/package.json
- packages/captcha/src/interface.ts
- packages/captcha/src/service.ts
- site/docs/extensions/captcha.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/captcha.md
> fix: use security svg-captcha and add more options

- packages/swagger/src/swaggerExplorer.ts
> fix(swagger): correct typo from 'text/plan' to 'text/plain'

- packages/kafka/src/configuration.ts
> fix: KafkaProducerFactory not init from decorator

- packages/core/src/context/container.ts
- packages/core/src/context/definitionRegistry.ts
- packages/core/src/context/dynamicContainer.ts
- packages/core/src/context/managedResolverFactory.ts
- packages/core/src/context/requestContainer.ts
- packages/core/src/definitions/objectCreator.ts
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/test/baseFramework.test.ts
- packages/core/test/context/dynamicContainer.test.ts
- packages/core/test/context/managedResolverFactory.test.ts
- packages/mock/src/creator.ts
> feat: try to support HMR

- .run/All Tests in event-emitter.run.xml
- packages/core/src/context/container.ts
- packages/core/src/decorator/metadataManager.ts
- packages/core/src/service/decoratorService.ts
- packages/event-emitter/README.md
- packages/event-emitter/index.d.ts
- packages/event-emitter/jest.config.js
- packages/event-emitter/jest.setup.js
- packages/event-emitter/package.json
- packages/event-emitter/src/configuration.ts
- packages/event-emitter/src/const.ts
- packages/event-emitter/src/decorator.ts
- packages/event-emitter/src/index.ts
- packages/event-emitter/src/interface.ts
- packages/event-emitter/src/service.ts
- packages/event-emitter/test/index.test.ts
- packages/event-emitter/tsconfig.json
- packages/event-emitter/typedoc.json
- pnpm-lock.yaml
- site/docs/extensions/events.md
- site/docs/sidebars.json
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/events.md
- site/package-lock.json
- site/package.json
> feat: add events component

- packages/bull-board/src/board.middleware.ts
- packages/bullmq/src/interface.ts
修复这个 [discussion](https://github.com/midwayjs/midway/discussions/3629) 中的问题
> fix(bull-board): init bull board in resolve

- site/docs/deployment.md
> docs: fix typo of deployment.md

- packages/bull-board/src/board.middleware.ts
- packages/bull/src/framework.ts
- packages/bull/src/interface.ts
- packages/bullmq/src/framework.ts
- packages/busboy/src/interface.ts
- packages/busboy/src/middleware.ts
- packages/busboy/test/index.test.ts
- packages/core/src/common/applicationManager.ts
- packages/cron/src/framework.ts
- packages/cron/test/index.test.ts
- packages/validate/src/configuration.ts
- site/docs/extensions/bull.md
- site/docs/extensions/bullmq.md
处理一些 v4 开发期间 v3 的问题聚合。
#4295
#4293
#4299
#4294
> fix: #4295 #4293 #4299 #4294

- packages/session/package.json
- packages/web-koa/package.json
- packages/web-koa/src/config/config.default.ts
- packages/web-koa/src/framework.ts
> feat: support new cookies options

- packages/bull-board/src/board.middleware.ts
- packages/bullmq/package.json
- packages/web-koa/src/config/config.default.ts
- packages/web-koa/src/framework.ts
> chore: upgrade bullmq version and update cookie extra options

- packages/bull-board/package.json
- packages/bull-board/src/index.ts
- packages/bull-board/test/index.test.ts
- site/docs/extensions/bull.md
- site/docs/extensions/bullmq.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bullmq.md
> fix: bull-board missing export adapter

- site/docs/esm.md
- site/i18n/en/docusaurus-plugin-content-docs/current/esm.md
> docs: update the wrong spelling of DefaultConfig

- packages/ws/src/framework.ts
- packages/ws/src/interface.ts
- packages/ws/test/fixtures/base-app-upgrade-auth/package.json
- packages/ws/test/fixtures/base-app-upgrade-auth/src/configuration.ts
- packages/ws/test/fixtures/base-app-upgrade-auth/src/socket.ts
- packages/ws/test/index.test.ts
- packages/ws/test/utils.ts
- site/docs/extensions/ws.md
- site/i18n/en/docusaurus-plugin-content-docs/current/extensions/ws.md
> feat: add ws upgrade handler

- packages/ws/package.json
- packages/ws/src/framework.ts
- packages/ws/test/index.test.ts
> fix: heartbeat does not take effect in koa scenario

- packages/cron/package.json
- packages/cron/src/framework.ts
- packages/cron/src/interface.ts
仅更新 cron 插件依赖
升级到 3.5.0 以支持 `waitForComplete`
> breaking: upgrade cron to 3.5.0, support waitForComplete
